### ISSUE TITLE
error: Name "Sequence" is not defined

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#1022]
# Bug report

There's a discussion in gh-709 about a new bug, which seems to output nonsense `error: Name "Sequence" is not defined` errors. @ljodal has suggested that the regression was introduced in https://github.com/typeddjango/django-stubs/pull/991, and they've reproduced the issue in https://github.com/typeddjango/django-stubs/pull/1021 and https://github.com/ljodal/django-stubs-regression-test.

## System information

- OS:
- `python` version: 3.10.x
- `django` version: 3.2.x
- `mypy` version: 0.962
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by christianbundy** [comment]
Here's a quick reproduction [ab]using a Docker to make this easy for anyone to test:

```shell
docker build -f - . << EOF
FROM python:3.10

RUN apt-get update && apt-get install git

RUN git clone https://github.com/ljodal/django-stubs.git

WORKDIR ./django-stubs

RUN git checkout 1ec8c44946c3de25cf88751dcd34c0ba58770ccf

RUN pip install -U pip setuptools wheel \
    && pip install -r ./requirements.txt

RUN pytest --mypy-ini-file=mypy.ini -k from_queryset_custom_auth_user_model
EOF
```

**Comment by flaeppe** [comment]
Just dropping by with some additional, related, discussion:

- https://github.com/typeddjango/django-stubs/pull/991#issuecomment-1164708451 and downwards
- #820 Resolved similar phantom errors, but for custom queryset methods (resolution for #709 )

**Comment by ljodal** [comment]
I also suspect that https://github.com/typeddjango/django-stubs/issues/958 might be caused by the same underlaying bug, as it's similar in it appearance (something is wrong with types after copying). It happens whenever we use `Model.objects.using()` (but only when used directly on the manager I think, not on a query set) on models with a custom queryset

**Comment by flaeppe** [comment]
> I also suspect that https://github.com/typeddjango/django-stubs/issues/958 might be caused by the same underlaying bug ...


Yep, I'd say you're right. Recognizing that _SpecialCase, from when anal_type has run.
