### ISSUE TITLE
Problem with manager created using .from_queryset() and imported from other module

### ISSUE THREAD

**Issue by ngnpope** [typeddjango/django-stubs#1032]
# Bug report

When a manager is created using `.from_queryset()` and imported from another module, it's type is `Any`, but only when the `QuerySet` subclass has its generic specified as `["MyModel"]`.

## What's wrong

I took [this test case](https://github.com/typeddjango/django-stubs/blob/214b0c7439d67b423815515c49eda8ecf0d62bfa/tests/typecheck/managers/querysets/test_from_queryset.yml#L25-L72) and adapted it to move the `NewManager = BaseManager.from_queryset(ModelQuerySet)` line into `myapp/querysets.py` and imported `NewManager` into `myapp/models.py` instead of `ModelQuerySet`.

See this diff: [from_queryset-extra-tests.txt](https://github.com/typeddjango/django-stubs/files/9005556/from_queryset-extra-tests.txt)

Applying this to the current `master` results in the following two tests failing:
- `from_queryset_using_basemanager_with_manager_imported_from_other_module`
- `from_queryset_using_manager_with_manager_imported_from_other_module`

If I change the following in `myapp/querysets.py` for these tests then they pass:

```python
-                class ModelQuerySet(models.QuerySet["MyModel"]):
+                class ModelQuerySet(models.QuerySet):
```

Weird.

As far as I could work out `get_dynamic_class_hook` is being called for `myapp.models.NewManager`, but then `get_function_hook`/`get_method_hook` doesn't seem to get called for methods on the manager in the failure case.  

## How is that should be

When `NewManager` is created using `.from_queryset()` and is imported from another module it shouldn't resolve to `Any` when `Queryset["MyModel"]` is used as the subclass, but should be the same as when only `QuerySet` is used as the subclass or `NewManager` is created in `myapp/models.py`.

## System information

- OS:
- `python` version: 3.9.5
- `django` version: 3.2.13
- `mypy` version: 0.961
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by flaeppe** [comment]
Interestingly enough, the hook is called if I do `class ModelQuerySet(models.QuerySet[models.Model])` as well.

**Comment by ngnpope** [comment]
Hmm. Yes. And it also works if I do `class ModelQuerySet(models.QuerySet["models.Model"])`, so it's not specifically to do with string annotations. Most likely something to do with the circular dependency and the order things are resolved - maybe we need to defer for an extra pass somewhere?

**Comment by flaeppe** [comment]
I'm suspecting it has to do with this change: https://github.com/typeddjango/django-stubs/pull/999#discussion_r899525241

Or at least that it takes that path to add the manager. I have a change in #1025 that might resolve it. I could try if that's a correct assumption

**Comment by flaeppe** [comment]
Yep, seems that it worked. See #1033
