### ISSUE TITLE
type narrowing with queryset.exists()

### ISSUE THREAD

**Issue by AdrienLemaire** [typeddjango/django-stubs#1048]
# Bug report

## What's wrong

When adding a `if queryset.exists()` condition, the following `queryset.first()` is typed `Optional[Model]`

```py
if self.plan_set.exists():
    first_plan = self.plan_set.first()   # typed Optional[Plan]
```

I have to force a cast to overcome this issue for now:
```py
if self.plan_set.exists():
    first_plan = cast(Plan, self.plan_set.first())  # typed Plan
```

## How is that should be

Expecting the following `queryset.first()` assignment to be typed `Model`.

```py
if self.plan_set.exists():
    first_plan = self.plan_set.first()  # typed Plan
```

## System information

- OS: Arch linux
- `python` version: 3.10.1
- `django` version: 3.2.13
- `mypy` version: 0.961
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by ljodal** [comment]
This would not be safe. Between the time you run `.exists()` and `.first()` someone else could have deleted the item in the database and you'd still get `None`.

**Comment by AdrienLemaire** [comment]
@ljodal I see. I understand that the following approach would be safer then:

```py
first_plan = self.plan_set.first()
if first_plan:
   ...
```

Thanks for the feedback

**Comment by ljodal** [comment]
Yeah, alternative you could do something like this:

```python
if qs.exists():
    return qs[:1].get()
```

That has slightly different semantics though. You risk an `ObjectDoesNotExist` at runtime if you have race conditions (might not be a problem, depending on your use case), but it also doesn't enforce ordering (better performance, again depending on your use case)
