### ISSUE TITLE
_MonkeyPatched*Response.context is typed incorrectly

### ISSUE THREAD

**Issue by tilsche** [typeddjango/django-stubs#1056]
# Bug report

The `context` in the return types of `test.client.Client.get` etc. functions cannot be intuitiively used.

## What's wrong

`_MonkeyPatchedWSGIResponse` and `_MonkeyPatchedASGIResponse` use 
```
context: List[Dict[str, Any]]
```

Therefore, it is not possible to do

```
response.context["some_string"]
```

## How is that should be

The type should be
```
context: ContextList
```

This does depend on `ContextList` working properly, see #1055 

## System information

- `django-stubs` version: [e8d52fe](https://github.com/typeddjango/django-stubs/commit/e8d52fe7daf88cfe7db5d0dd312e1b5946577051)

**Comment by sjdemartini** [comment]
Looks like this should be fixed by https://github.com/typeddjango/django-stubs/pull/1100 (which has been recently merged)

**Comment by adamchainz** [comment]
Yes I think I got it right 😅
