### ISSUE TITLE
Support mypy 0.971

### ISSUE THREAD

**Issue by DamianZaremba** [typeddjango/django-stubs#1064]
mypy 0.971 was released a short while ago (https://github.com/python/mypy/releases/tag/v0.971).

`django-stubs` currently enforces a version less than 0.970 (https://github.com/typeddjango/django-stubs/blob/master/setup.py#L34), please enable support for 0.971.

Due to changes https://github.com/python/mypy/pull/11143 the tests currently fail when path appending;
* https://github.com/typeddjango/pytest-mypy-plugins/blob/master/pytest_mypy_plugins/item.py#L388 appending to the path
* https://github.com/typeddjango/django-stubs/blob/master/tests/typecheck/test_config.yml#L62

A scratch branch which updates the requirements while patching out the tests is @ https://github.com/DamianZaremba/django-stubs/tree/bump-mypy-0.970, as I'm not sure of your preferred way to deal with the tests.

**Comment by adamchainz** [comment]
Thanks for the report. The problems introduced by Mypy 0.971 were fixed in #1108 after some wrestling by @sobolevn .

We haven't made a release with support yet, but until then you can install from Git ([example](https://github.com/typeddjango/django-stubs/issues/1095#issuecomment-1241967327)).
