### ISSUE TITLE
error: `BaseCache` has no attribute `lock` / `keys` / ...

### ISSUE THREAD

**Issue by UnknownPlatypus** [typeddjango/django-stubs#1082]
# Bug report

## What's wrong

Thanks to #998 , we have a more accurate type for `django.core.cache.cache` -> `BaseCache`.

However, this is a problem for third-party/custom cache backend that implement other methods. 
For example [django-redis](https://github.com/jazzband/django-redis) `lock`/`keys`/... methods.

## How is that should be

I'm not sure how to deal with this, and how to declare that my cache backend is using a different type (`RedisCache` for ex.)
Any idea how I can address this issue ? This is a blocker for me as my project heavily rely on `django-redis`.

## System information

- OS:
- `python` version: 3.8
- `django` version: 3.2.14
- `mypy` version: 0.971
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by adamchainz** [comment]
Adding a [type-narrowing assert](https://adamj.eu/tech/2021/05/17/python-type-hints-how-to-narrow-types-with-isinstance-assert-literal/) at the module level should do the trick:

```python
from django.core.cache import caches
from djagno_redis.cache import RedisCache
cache = caches["default"]  # or whatever the name of your cache is
assert isinstance(cache, RedisCache)
# from here on, Mypy knows it's a RedisCache
```

Hope that helps!

**Comment by UnknownPlatypus** [comment]
This should work, but that's a bit annoying to have to do that multiple time.
(Won't work for django-redis tho because they [lack type hints](https://github.com/jazzband/django-redis/issues/591))

Anyway, I don't have better idea for now. 
Thanks for the idea

**Comment by adamchainz** [comment]
You can always create `myapp.cache` and import the cache object, that uses the above type narrowing, and import from there throughout your code base.

django-redis is kinda outdated since the Redis backend was introduced to Django core. There's perhaps space to add some extra functions to Django core's redis backend, if you propose it. Otherwise you could consider a package that extends the built-in backend.
