### ISSUE TITLE
EmailValidator throws false alarm on Django 4.1.0?

### ISSUE THREAD

**Issue by Thorbenl** [typeddjango/django-stubs#1088]
## What's wrong

```python
/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/site-packages/django-stubs/core/validators.pyi:52: note: "EmailValidator" defined here
mailchimp/api.py:177: error: Unexpected keyword argument "allowlist" for
"EmailValidator"  [call-arg]
            email_validator = EmailValidator(allowlist=[])
```

## How is that should be

`whitelist` got deprecated in favor of `allowlist`, but mypy/stubs complains now, because it doens not know about it.
However, after checking the codebase from stubs, it should technically not be a problem.

## System information

- OS:
- `python` version: 3.10.5
- `django` version: 4.1.0
- `mypy` version: 0.931
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version:

**Comment by adamchainz** [comment]
`allowlist` was added to the stubs in f69e0639c74fee0e8ad3d165790ac9804ea4a3f2, released in v1.11.0, please upgrade :)
