### ISSUE TITLE
Inconsistent behavior depending on cache

### ISSUE THREAD

**Issue by ynikulin** [typeddjango/django-stubs#110]
Hello,

```
Python 3.7.3

django==2.2.1
mypy==0.710
django-stubs==0.12.1
```

When I run `mypy .` I got **113** errors, but if I will run it again I got **371** errors. 

To fix it - I remove local `.mypy_cache` and all fine, I got base **113** errors.

Can you please give me some advice :) Thanks.

**Comment by sobolevn** [comment]
@ynikulin thanks for using this library and reporting and issue! Currently the big rewrite process is going on. 

The best advice I can give is to wait for it to be released and use it.

I am not sure that your problem will be solved in the old version.

**Comment by ynikulin** [comment]
Thanks, for the answer! Good luck! Will wait :)

**Comment by ynikulin** [comment]
Hello,

Now all works fine! Thanks!

I will close an issue.

**Comment by sobolevn** [comment]
Thanks for reporting!
