### ISSUE TITLE
Plugin calls `ready` of all installed apps

### ISSUE THREAD

**Issue by orsinium** [typeddjango/django-stubs#1115]
# Bug report

## What's wrong

django-stubs calls `apps.populate(settings.INSTALLED_APPS)` which in turn calls `ready` on all apps. And that requires all imports to be present and even can execute SQL queries.

```python
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/main.py", line 71, in __init__
    self.django_context = DjangoContext(self.plugin_config.django_settings_module)
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 97, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 81, in initialize_django
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
...
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "..." does not exist
```

## How is that should be

What's the purpose of calling `apps.populate`? would it be possible to avoid calling `ready` on apps and still do what django-stubs needs to do? If I understand correctly, you need only imports to be executed, right? If it sounds interesting I could look into mocking `app_config.ready()` calls.

Related: #1060

## System information

- OS: Linux Mint
- `python` version: 3.8.13
- `django` version: 3.2.15
- `mypy` version: 0.971
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by orsinium** [comment]
I'm speaking not out of my laziness to create a proper environment with a DB to run mypy but rather because this little maneuver costs us 20+ seconds on each run.

**Comment by flaeppe** [comment]
As mentioned in #1060 it's the _plugin_ that needs apps ready. If you turn off the plugin, it won't happen. If you want the plugin, you're probably gonna have to live with it running apps ready.

> What's the purpose of calling `apps.populate`?

Django trigger a lot of things, for instance registering and preparing stuff for database models. Populating settings etc.

A lot of those things are dynamical. As some kind of example, have a look at the model processing in the plugin: https://github.com/typeddjango/django-stubs/blob/3ac34f110800e555a380b80ea2fb8758c19ebea2/mypy_django_plugin/transformers/models.py#L621-L632

There's a lot of stuff there that can't be done(or is a lot more difficult to do) without apps ready having been run.

**Comment by orsinium** [comment]
Clear, thank you. What if we set an env var during this population time, so that apps can skip on their side some heavy steps that aren't needed for django-stubs?

```
def ready():
    if os.environ.get('DJANGO_STUBS'):
        return
    ...
```

**Comment by flaeppe** [comment]
What's wrong with using `TYPE_CHECKING`?

```python
if not typing.TYPE_CHECKING:
    ...
```

**Comment by orsinium** [comment]
Good question. I've considered it. If we set it to True at runtime, it will mess up with how it is always assumed to be False at runtime. For instance, it is a good practice to have some imports hidden under `if TYPE_CHECKING`, which, if executed, will cause cyclic imports.

**Comment by orsinium** [comment]
I've just added `if 'mypy_django_plugin' not in sys.modules:` check 🧠 It looks quite dirty but should be safe enough since django-stubs doesn't come on the production anyway. It should be sufficient for my needs. If anyone wants to have a proper flag, feel free to re-open the issue.

**Comment by flaeppe** [comment]
I'm still wondering why below wouldn't work?

```python
if typing.TYPE_CHECKING:
    return
```

**Comment by orsinium** [comment]
Depends on what case you mean. Because `TYPE_CHECKING` is always `False`?

**Comment by orsinium** [comment]
```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .categories import Category  # line 3

def ready():
    if TYPE_CHECKING:
        return
    raise RuntimeErrror('very slow operation, avoid')  # line 8
```

+ If `TYPE_CHECKING is True`,  line 3 will raise `ImportError` because of cyclic imports (TYPE_CHECKING is always assumed to be False and is used to hide expensive or cyclic imports).
+ If `TYPE_CHECKING is False`,  line 8 will be executed and raise RuntimeError, and we want to avoid that.

So, you shouldn't mess with `TYPE_CHECKING`. It is assumed to be False, and should always stay that way. It may hide expensive imports, cyclic imports, and even type vars definitions in a syntax unsupported by the current version of Python (like `MaybeStr = str | None`).

**Comment by orsinium** [comment]
So, in short, I wouldn't recommend messing with `TYPE_CHECKING`. But hey, you shouldn't trust me! Give it a try, run it on a real-world app, and see what happens.

**Comment by flaeppe** [comment]
From the docs:

> A special constant that is assumed to be True by 3rd party static type checkers. It is False at runtime. [...]

https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

I think you can trust it. But using `if 'mypy_django_plugin' not in sys.modules:` probably works just as well too.

**Comment by orsinium** [comment]
Type checkers never actually execute code. Mypy will "execute" the content of the `if TYPE_CHECKING` block, meaning that it will use definitions from there, but it will never actually set TYPE_CHECKING to True. Even more, you can just use `if False:` block with exactly the same effect. And that's what people used to do in the early days of type checking before TYPE_CHECKING was introduced in Python 3.5. You still can find custom definitions of this constant in some old libraries, something like `TYPING = False`. And that makes total sense because, as I said, the contents of this block are never meant to be executed, they are here only for type checkers to get some type definitions that cannot be gotten otherwise.

**Comment by orsinium** [comment]
And that's the big difference between mypy and django-stubs. The latter actually executes the code, and so potentially suffers from all possible slow-downs, loops, and side-effects. And the issue is about finding a way to avoid it.

**Comment by flaeppe** [comment]
Haha, yes, you're right. It's me being confused, mixing up what's runtime and not
