### ISSUE TITLE
Add pull request template for github

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#112]
We need to ask for docs to the original source when types are updated.
We would also want to know which version are affected: 2.1, 2.22, 2.2+, etc

Example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/.github/pull_request_template.md

**Comment by mkurnikov** [comment]
@sobolevn If/when you're going to work on that, could you also add an issue template with 
1. request to check on master first
2. provide failing test case, like it's done in https://github.com/typeddjango/django-stubs/pull/120, it's immensely helpful

**Comment by sobolevn** [comment]
Sure.

**Comment by sobolevn** [comment]
@mkurnikov I will write a guide about writing tests with `pytest-mypy-plugin`. Because currently a lot of people might be confused with the syntax and usage.

First iteration of templates is ready. Check the PR.
