### ISSUE TITLE
Django stubs is crashing for the filed name type

### ISSUE THREAD

**Issue by NeurlAP** [typeddjango/django-stubs#1120]
# Bug report

## What's wrong
django stubs is crashing with the below errror when I'm naming the field name ```type```  to models.CharField django model.
error traceback
```
raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
FieldDoesNotExist: StorePage has no field named 'type' 
``` 
eg: field
```
type = models.CharField(max_length=50, null=True, choices=TYPE_CHOICES)
```

## System information

- OS:
- `python` version: 3.9
- `django` version: 3.2.14
- `mypy` version: 0.961
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by flaeppe** [comment]
This is an old issue now and there's not really much information to go on here. I'm going to close it, you're welcome to open a new issue with more information or provide it here
