### ISSUE TITLE
Don't make psycopg2 a dependency

### ISSUE THREAD

**Issue by kylebebak** [typeddjango/django-stubs#114]
Installing `pscyopg2` can be difficult on many platforms.

Making this a dep for type stubs seems **really** excessive to me.

**Comment by sobolevn** [comment]
One can also use `psycopg2-binary` and they might conflict.

**Comment by kylebebak** [comment]
Awesome @mkurnikov 

Thanks for the quick response, and thanks for these awesome type stubs =)
