### ISSUE TITLE
Sitemap type anotation is too restrictive

### ISSUE THREAD

**Issue by UnknownPlatypus** [typeddjango/django-stubs#1192]
# Bug report

## What's wrong

I'm having a similar issue to #1000 when type annotating django sitemaps.

The following is not passing:

```python
class OfferSitemap(Sitemap):
    priority = 1
    changefreq = "always"

    def items(self) -> QuerySet[Offer]:
        return Offer.objects.all()

    def location(self, item: Offer) -> str:
        return reverse(
            "myapp:detail-offer",
            kwargs={
                "provider_name": item.provider.url_name,
                "offer_name": item.url_name,
            },
        )

# error: Argument 1 of "location" is incompatible with supertype "Sitemap"; supertype defines the argument type as "Model"
# note: This violates the Liskov substitution principle
```

## How is that should be

From the docs: 

> [items()](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.items) is a method that returns a [sequence](https://docs.python.org/3/glossary.html#term-sequence) or QuerySet of objects. The objects returned will get passed to any callable methods corresponding to a sitemap property ([location](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.location), [lastmod](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.lastmod), [changefreq](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.changefreq), and [priority](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.priority)).

I think the type could be more generic because the `items` method is the one that determines the type of the `item` variable every other methods are using. Maybe taking a similar approach to #800 with an `_Item` Typevar ?

Let me know if you think this is a correct approach and I'll be happy to submit a PR to address that.

Cheers

## System information

- OS: **ubuntu20.04**
- `python` version: **3.8**
- `django` version: **3.2.15**
- `mypy` version: **0.950**
- `django-stubs` version: **1.11.0**
- `django-stubs-ext` version: **0.5.0**

**Comment by adamchainz** [comment]
Using a `TypeVar` seems correct to me, please do submit a PR. That should fix #1000 as well.
