### ISSUE TITLE
`Manager.bulk_update` expects fields to be `Sequence[str]`

### ISSUE THREAD

**Issue by kezabelle** [typeddjango/django-stubs#1195]
The `bulk_update` definition for `BaseManager` is:
https://github.com/typeddjango/django-stubs/blob/36002a20874a4f1d5671e2f784c7257eb50fe691/django-stubs/db/models/manager.pyi#L79

Note: `fields: Sequence[str]`

which AFAIK is incorrect, and has already been fixed for `_QuerySet` in:
- #822
- #868

https://github.com/typeddjango/django-stubs/blob/36002a20874a4f1d5671e2f784c7257eb50fe691/django-stubs/db/models/query.pyi#L83

Note: `fields: Iterable[str]`

------

It seems to me that they should both be the same, and that for example `{"a", "b", "c"}` (a `Set[str]`) should pass on both (because internally to Django, the `fields` is consumed by iteration and re-cast to a list of Field instances IIRC)

**Comment by adamchainz** [comment]
Yup seems right, would you like to make a PR?

We could probably do with a test that methods are in sync between `BaseManager` and `_QuerySet`.

**Comment by 93578237** [comment]
https://github.com/typeddjango/django-stubs/pull/1114/ covers it

**Comment by kezabelle** [comment]
Good eye 🔍 
Happy to close this as a duplicate if that PR is going to solve the issue (especially as I haven't gotten around to opening a PR myself yet; the eternal backlog 😄)
 
As a data point, though I think it unrelated, I encountered the typing discrepancy on a `3.2` project.
