### ISSUE TITLE
django.db.models.base.model_unpickle missing

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#1207]
apologies for cutting out the template -- most of the fields weren't relevant to my issue

I'm not sure what the correct typing of this is (I'm not all that familiar with django) https://github.com/django/django/blob/de2c2127b66e77a034c01c81753c5c08e651a5b4/django/db/models/base.py#L2464-L2471

but any access of this is giving an `[attr-defined]` error in mypy:

```python
django.db.models.base.model_unpickle
```

```
error: Module has no attribute "model_unpickle"  [attr-defined]
```

**Comment by adamchainz** [comment]
Interesting that code would need to touch the unpickling process, what’s the use case?

**Comment by asottile-sentry** [comment]
from what I can tell we've got some terrible django compat monkeypatching stuff https://github.com/getsentry/sentry/blob/c566e70d5df7da48d8fa484111526a9d22b3a4d7/src/sentry/runner/initializer.py#L477-L485

**Comment by adamchainz** [comment]
Django 1.10 is some time ago, I’d be pretty sure you can drop that code path now. Unlikely you have any pickles sitting around from that time, pickling is normally used only for caching in  Django. Guess you have a metric you can check with.
