### ISSUE TITLE
Forms: modification of ChoiceField `choices` flagged as attr-defined

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#1208]
# Bug report

## What's wrong

```python
from typing import Any
from django import forms

class F(forms.Form):
    f = forms.ChoiceField(choices=())

    def __init__(self, *args: Any, choices: tuple[str, ...], **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        self.fields["f"].choices = choices
        self.fields["f"].widget.choices = self.fields["f"].choices
```

(this is distilled from a larger example just to demonstrate the issue)

## How is that should be

this probably needs custom plugin support -- it would be nice if `self.fields` were a `TypedDict` based on the attributes of the class

## System information

- OS:
- `python` version: 3.10.7
- `django` version: 4.1.2
- `mypy` version: 0.982
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by intgr** [comment]
There are tricks to make this more type-safe, like:
```python
    def __init__(self, *args: Any, choices: tuple[str, ...], **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        f_field = self.fields["f"]
        assert isinstance(f_field, forms.ChoiceField)  # mypy takes this as a type hint

        f_field.choices = choices
        f_field.widget.choices = f_field.choices
```

**Comment by asottile-sentry** [comment]
putting a narrowing assert isn't "making this more type safe" -- it's overriding the type checker

**Comment by intgr** [comment]
You may not like it, but it's just the everyday reality of using type hints with frameworks like Django. There is a lot of magic that happens in Django and the vast majority of that magic isn't covered by custom plugin logic.

So it's either using tricks like this or writing type-unsafe code.

**Comment by asottile-sentry** [comment]
a mypy plugin should be able to do this correctly -- that's the point of making this issue.  an `assert` **is** type-unsafe code (it's a runtime narrowing that the type checker understands)

**Comment by delfick** [comment]
was this issue closed by mistake?

**Comment by UnknownPlatypus** [comment]
There where just 2 different issue on the same topic so the author closed this one.
This problem is tracked in #1514 now

**Comment by delfick** [comment]
ah cool, thanks :)
