### ISSUE TITLE
GitHub Discussions? StackOverflow tag?

### ISSUE THREAD

**Issue by tony** [typeddjango/django-stubs#1248]
## StackOverflow

We can link up [`[django-stubs]`](https://stackoverflow.com/questions/tagged/django-stubs). There's a tag!

## GitHub discussions

In re:

> We have Gitter here: https://gitter.im/mypy-django/Lobby If you think you have more generic typing issue, please refer to https://github.com/python/mypy and their Gitter.

Gitter is fine.

Can we also have a GitHub discussions so we can stay on top of undocumented nuances, e.g. https://github.com/typeddjango/django-stubs/pull/1163#issuecomment-1259114502

**Comment by adamchainz** [comment]
> We can link up [`[django-stubs]`](https://stackoverflow.com/questions/tagged/django-stubs). There's a tag!

There is already a link in the badges at the top of the README. But perhaps it could be made more prominent.

**Comment by sobolevn** [comment]
I personally don't like GitHub Discussions compared to StackOverflow.
Because the later has more active users who just answer questions. And GitHub Discussions are like "blamed" on maintainers.

Back in the days, when I was active on SO, I sometimes learned something new specifically to answer interesting questions 😆

**Comment by tony** [comment]
> There is already a link in the badges at the top of the README. But perhaps it could be made more prominent.

Good catch @adamchainz, I see you around many issues on GitHub, 👋 

I think making it more prominent would be a plus - I missed it.

> Because the later has more active users who just answer questions. And GitHub Discussions are like "blamed" on maintainers.

@sobolevn, I suppose pinning a topic that it's end-user between downstream users and not necessarily a direct line to maintainers (If they wanted that, it sounds like they'd need a commercial support contract)

Due to how fast paced django-stubs / mypy is relative to django itself, SO can end up having stale conversations easily. 

On the flip side, viewed optimistically:
- a place for downstream users to congregate with workarounds / best practices
- avoids noisiness in issue tracker itself

**Comment by adamchainz** [comment]
> I think making it more prominent would be a plus - I missed it.

My own projects use a larger badge style, which you could copy: https://github.com/adamchainz/apig-wsgi/blob/main/README.rst - if you’d like to make a PR here.

**Comment by tony** [comment]
> My own projects use a larger badge style, which you could copy: https://github.com/adamchainz/apig-wsgi/blob/main/README.rst - if you’d like to make a PR here.

Communication clarification! 😄 

I see this was quoting a remark of mine regarding linking to StackOverflow tags:

> I think making it more prominent would be a plus - I missed it.

Are you suggesting adding bigger badges to the django-stubs README (not necessarily limited to the StackOverflow tag itself)?  Feel free to clarify

**Comment by tony** [comment]
As for GitHub discussions - I suppose we don't really know unless we flip it on. If it putters out or isn't helpful it can be turn off

There's nothing wrong politely reminding posters that the license says no warranty - and the existsence of disscussion is community help, not a direct line to maintainers or free support

**Comment by sobolevn** [comment]
> I suppose we don't really know unless we flip it on. If it putters out or isn't helpful it can be turn off

I have several other projects where we have discussions on. It creates a lot of noise.

**Comment by tony** [comment]
@sobolevn that's fine

I feel this was sufficiently discussed for now.  I don't have more to add

For now I will close this, but if it's raised again with more information or GH discussions gets more convenient, it's fine to cite this
