### ISSUE TITLE
Django 4.1 constraints violation_error_message

### ISSUE THREAD

**Issue by martinlehoux** [typeddjango/django-stubs#1262]
Hi there,

I dont think there is an implementation of the new https://docs.djangoproject.com/fr/4.1/ref/models/constraints/#violation-error-message on constraints types.

Is there another issue tracking this that I'm missing? Or is that okay if I work on this?

**Comment by sobolevn** [comment]
@martinlehoux yes, sure! Thank you.

**Comment by martinlehoux** [comment]
Hi @sobolevn I just submitted a PR for this
