### ISSUE TITLE
Add GetResponseAsyncCallable? / typing of MiddlewareMixin

### ISSUE THREAD

**Issue by blueyed** [typeddjango/django-stubs#1269]
Given the following middleware, type checking fails:

> error: Incompatible types in "await" (actual type "HttpResponse", expected type "Awaitable[Any]")  [misc]
> error: Returning Any from function declared to return "HttpResponse"  [no-any-return]

```python
from django.utils.decorators import async_only_middleware
from django.utils.deprecation import GetResponseCallable


@async_only_middleware
def my_middleware(get_response: "GetResponseCallable"):
    async def middleware(request: "HttpRequest") -> "HttpResponse":
        response = await get_response(request)
        # …
        return response
    return middleware
```

Adding and using `AsyncGetResponseCallable` fixes this:
```diff
diff --git i/django-stubs/utils/deprecation.pyi w/django-stubs/utils/deprecation.pyi
index e15e0ae0..fa5a8d5d 100644
--- i/django-stubs/utils/deprecation.pyi
+++ w/django-stubs/utils/deprecation.pyi
@@ -1,5 +1,5 @@
 from collections.abc import Callable
-from typing import Any, Protocol
+from typing import Any, Awaitable, Protocol

 from django.http.request import HttpRequest
 from django.http.response import HttpResponse
@@ -32,6 +32,9 @@ class DeprecationInstanceCheck(type):
 class GetResponseCallable(Protocol):
     def __call__(self, __request: HttpRequest) -> HttpResponse: ...

+class AsyncGetResponseCallable(Protocol):
+    def __call__(self, __request: HttpRequest) -> Awaitable[HttpResponse]: ...
+
 class MiddlewareMixin:
     get_response: GetResponseCallable
     def __init__(self, get_response: GetResponseCallable = ...) -> None: ...
```

This could also be handled in `GetResponseCallable` directly (via union), but would be less explicit then.

Maybe it is also a good idea to add support to it to MiddlewareMixin, where it would be typed based on the input of `get_response` passed to `__init__` then.

**Comment by intgr** [comment]
Sounds good. I think this type should live in `django.utils.decorators`, not `deprecation`.

In fact, the `sync_and_async_middleware`, `sync_only_middleware` and `async_only_middleware` decorators could have a stricter bound to ensure that the decorated function accepts the correct type of argument.

**Comment by RyanWalker277** [comment]
> In fact, the `sync_and_async_middleware`, `sync_only_middleware` and `async_only_middleware` decorators could have a stricter bound to ensure that the decorated function accepts the correct type of argument.

Looking at the definition here

https://github.com/django/django/blob/073b5fd40035759afaebe5c77de5269aee851643/django/utils/decorators.py#LL166-L190C16

`sync_and_async_middleware`, `sync_only_middleware` and `async_only_middleware` being decorators, take in a function and return the same so the type is preserved, hence the current definition looks good to me.

https://github.com/typeddjango/django-stubs/blob/04d5696f15e05f569fccd51893db58e0b04fe557/django-stubs/utils/decorators.pyi#L17-L19 

Please let me know if I am missing something. I'll raise a PR adding the `AsyncGetResponseCallable` stub after this.

**Comment by intgr** [comment]
Huh? I think the https://github.com/typeddjango/django-stubs/pull/1425 PR is incomplete.

`AsyncGetResponseCallable` was added, but was not used anywhere. This isn't something that exists in Django, but the point was to use it to typehint Django's decorators, no?

**Comment by intgr** [comment]
* Fixed in https://github.com/typeddjango/django-stubs/pull/1575
