### ISSUE TITLE
Bug: Module 'django.contrib.admindocs' has no attribute 'urls'

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#127]
Source:

```python
from django.contrib.admindocs import urls as admindocs_urls
```

```
server/urls.py:16: error: Module 'django.contrib.admindocs' has no attribute 'urls'
```

Ref: https://github.com/wemake-services/wemake-django-template/blob/81f162b8ce26671429c32dfa2701648c8ddcb038/%7B%7Bcookiecutter.project_name%7D%7D/server/urls.py#L16
Real source: https://github.com/django/django/blob/master/django/contrib/admindocs/urls.py

**Comment by sobolevn** [comment]
@mkurnikov can you please advise me where to look for the solution here? 

I am looking at `from django.contrib.admin`: but it does not have `urls.pyi` neither.
But it works. While `from django.contrib.admindocs import urls` raises.

**Comment by mkurnikov** [comment]
There's no `urls.py` in `django.contrib.admin` https://github.com/django/django/tree/master/django/contrib/admin
Not sure what you're talking about. 

You can add `urls.pyi` to `django.contrib.admindocs` here if it affected you, why not. Then it should fix the problem. 

I'm [OOOS](https://discuss.python.org/t/mariatta-will-be-ooos-out-of-open-source-starting-march-18-may-9th-2019/973) till the end of next week, sorry, will be responding/reviewing very slowly, if ever, until that time.

**Comment by sobolevn** [comment]
Oh, I am sorry. I have missed this part:

```python
from django.contrib import admin

... 

     url(r'^admin/', admin.site.urls),
```

That's why it works. PR with the fix is incoming.
