### ISSUE TITLE
`Collector.data` and `NestedObjects.data` have different types, and are incorrect

### ISSUE THREAD

**Issue by kezabelle** [typeddjango/django-stubs#1271]
`NestedObjects` currently has:
https://github.com/typeddjango/django-stubs/blob/fa972f1632fb69861c913f2bf359fcf4d2284d7a/django-stubs/contrib/admin/utils.pyi#L33

`Collector` currently has:
https://github.com/typeddjango/django-stubs/blob/fa972f1632fb69861c913f2bf359fcf4d2284d7a/django-stubs/db/models/deletion.pyi#L60

_AFAIK_ `NestedObjects.data` is closer to correct, but I think is wrong, insofar as it's actually something like:
```
Dict[Type[Model], Set[Model] | List[Model]]
```

That is:
- the keys are the model **classes**,
- the values are _initially_ a `set` of model **instances**, but certain methods (notably, `sort` and `delete`) will mutate it into a `list` instead.

[See in Django main](
https://github.com/django/django/blob/855f5a36e7c8e7a8ce3f62d6ef8c9ae3e073ae3d/django/db/models/deletion.py#L101-L102), but this looks the same at least as far back as `3.2` (and possibly ... forever?):
```
# Initially, {model: {instances}}, later values become lists.
self.data = defaultdict(set)
```

Again AFAIK, `NestedObjects` doesn't actually modify the concept of the `data` attribute in any way, so should be the same as `Collector`

Closest vaguely related ticket I could find was:
- #842 which doesn't seem like a good overlap 🤷

**Comment by intgr** [comment]
Thanks! I think you're correct. There are plenty of inaccuracies in the stubs for rarely used features like `Collector`.

Feel free to submit a PR.

**Comment by RyanWalker277** [comment]
Hey @intgr @adamchainz! I would like to work on this one. Let me know if I can proceed and work on a patch.

**Comment by intgr** [comment]
Yes please 👍 I don't think anyone is working on this yet.

No need to ask for permission in the future, just leave a comment when you're working on it to avoid duplication.

**Comment by RyanWalker277** [comment]
Thanks @intgr! I have raised a pr #1366. I would appreciate any feedback or reviews on my approach to ensure that it meets the project's guidelines and standards. Thanks in advance for your time and consideration.
