### ISSUE TITLE
Setup flake8-pyi to lint stubs

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#128]
It will enforce `...` instead of `None`, find useless nodes for annotations, etc.
https://github.com/ambv/flake8-pyi

**Comment by hoefling** [comment]
@sobolevn does the decision on not using `flake8-pyi` still hold? (If I am reading #132 correctly) IMO making the stubs compliant to PEP 585, PEP 604, PEP 613 & friends would improve stubs quality, `flake8-pyi` also can prevent commits containing unused imports etc etc.

**Comment by sobolevn** [comment]
> There are so many violations out there.

If you have free time to introduce `flake8-pyi` and refactor all existing problems - you are **more** than welcome :)

**Comment by hoefling** [comment]
@sobolevn let me give it a try then. Most of the findings can be eliminated in an automated fashion - I already did this for PEP 604 imports in `typeshed` in https://github.com/python/typeshed/pull/5564 and https://github.com/python/typeshed/pull/5915, the scripts should be still functional.

**Comment by sobolevn** [comment]
Thank you! This will impove our code quality :)

**Comment by intgr** [comment]
If you're in for an extra challenge, you can do the same to https://github.com/typeddjango/djangorestframework-stubs repository too. :)

**Comment by hoefling** [comment]
@intgr gladly, but let's discuss #1253 first, I can then apply the same rules for DRF stubs
