### ISSUE TITLE
`_get_FIELD_display`

### ISSUE THREAD

**Issue by adnathanail** [typeddjango/django-stubs#1280]
# Bug report

## What's wrong

I have a model with a `CharField` with `choices` and I want to get the human-readable version of the field in the `__str__` function.

Django automatically creates model functions to do this, e.g. for a field called `fruit` there would be a function defined called `get_fruit_display`.

The definition for this function is [here](https://github.com/django/django/blob/eccda63a49b92ab14d523d69da2a3b3246cf91d1/django/db/models/base.py), and it is assigned to the model [here](https://github.com/django/django/blob/eccda63a49b92ab14d523d69da2a3b3246cf91d1/django/db/models/fields/__init__.py#L877)

Here is a failing test case

```python
from django.db import models

class AppLabelTextChoices(models.TextChoices):
    APP1 = "app1", _("Long app name")
    APP2 = "app2", _("Other long app name")

class PushNotificationToken(models.Model):
    mobile_app = models.CharField(max_length=25, choices=AppLabelTextChoices.choices)

	def __str__(self):
        return self.get_mobile_app_display()
```

Which produces the following error

```
accounts/models.py:345: error: "PushNotificationToken" has no attribute "get_mobile_app_display"  [attr-defined]
```

## How is that should be

It should be possible to infer that the `get_mobile_app_display` function will be defined (and will return a string), based on the presence of a field with `choices` called `mobile_app`.

## System information

- OS: macOS
- `python` version: 3.10
- `django` version: 3.2.15
- `mypy` version: 0.971
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

**Comment by adnathanail** [comment]
I'm no longer getting this error.

I'm not quite sure what was going on, but the `get_FIELD_display` is definitely being defined so I'll close this!

**Comment by danjac** [comment]
I can confirm this is not working currently:

Python 3.14

* `basedpyright`: 1.38.2
* 'django`: 6.0.2
* `django-stubs`: 5.2.9

**Comment by UnknownPlatypus** [comment]
@danjac this is expected if you use pyright/ty/pyrefly. This only works with mypy because it requires plugin code

**Comment by danjac** [comment]
Good to know, thanks!
