### ISSUE TITLE
Item "AbstractBaseUser" of "Union[AbstractBaseUser, AnonymousUser]" has no attribute "is_superuser"

### ISSUE THREAD

**Issue by Archmonger** [typeddjango/django-stubs#1282]
# Bug report

## What's wrong

`AbstractBaseUser` does not appear to be properly type hinted

```python
# This causes the following MyPy error...
# Item "AbstractBaseUser" of "Union[AbstractBaseUser, AnonymousUser]" has no attribute "is_superuser"
@method_decorator(user_passes_test(lambda u: u.is_superuser), name="dispatch")
class GeneralSettingsView(UpdateView):
    ...
```

## How is that should be

All expected attributes off [`AbstractBaseUser`](https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser) should be exposed to MyPy

## System information

- OS:
- `python` version: 3.10
- `django` version: 4.1
- `mypy` version: 0.982
- `django-stubs` version: 1.13
- `django-stubs-ext` version: 0.7.0

**Comment by sobolevn** [comment]
pr is welcome!

**Comment by Archmonger** [comment]
Some additional digging tells me that `is_superuser` is not a valid field of `AbstractBaseUser`. So the issue I'm experiencing appears to be #1058.

However, I did notice that the `clean` field is currently not defined within the `AbstractBaseUser` type hints.

Is it worth PRing this if the definition is only `def clean(self) -> None: ...`?

Technically unneeded, but depends on if this repo prioritizes completeness or not.

**Comment by Archmonger** [comment]
Closing in favor of #1058
