### ISSUE TITLE
The stub for AbstractBaseSession() get_decoded() is Dict[str, int] but should include str

### ISSUE THREAD

**Issue by danielmoessner** [typeddjango/django-stubs#1289]
# Bug report

I found a wrong stub.

## What's wrong

The file `base_session.pyi` contains the stubs for AbstractBaseSession. The stub for the method `get_decoded` is wrong.
It is `Dict[str, int]` but obviously the decoded session can also contain strings.

## How is that should be

Steps to reproduce:

1. Have any django project running with session login. 
2. Login so that there is at least one session in the database.
3. Open the python shell with `python manage.py shell`

Run the following code from within the shell:
```
from django.contrib.sessions.models import Session
s = Session.objects.first()
s.get_decoded()

# Example response:
# {'_auth_user_id': '1', '_auth_user_backend': 'django.contrib.auth.backends.ModelBackend', '_auth_user_hash': '1c92e5298f2609bd14615aef4f2bd07a13a7e741b8acc475623ae3f1386d4879'}
```

As you can see event the auth_user_id is a string. Therefore I think the stub should be `Dict[str, str]` but at the moment I'm not sure if it can include numbers, so `Dict[str, Union[str, int]]` might also be correct.

## System information

django-stubs==1.13.0

**Comment by intgr** [comment]
It looks like it's currently `dict[str, Any]`

https://github.com/typeddjango/django-stubs/blob/16fde01583fafd496c8f3c7587a7630925e191de/django-stubs/contrib/sessions/base_session.pyi#L20

Ideally this would be a `TypedDict`, if the dict keys are always the same. PRs welcome.

**Comment by danielmoessner** [comment]
That seems fine, probably the most correct. I didn't notice that it changed recently. I'm not sure if TypedDict is the correct way to go, as the session can be extended with any key you want. In my opinion this issue can be closed.

**Comment by ngnpope** [comment]
I'm not sure this makes sense to change from `dict[str, Any]`, especially as `TypedDict` doesn't always play nicely. People may not use `django.contrib.auth` or the session may be empty, so keys added to support session variables added there would need to be `NotRequired`, or we can use `total=False` for the whole `TypedDict`:

```python
from typing import TypedDict

class _DecodedSession(TypedDict, total=False):
    _auth_user_id: str
    _auth_user_backend: str
    _auth_user_hash: str
    _csrftoken: str
    _password_reset_token: str
```

Unfortunately, the session can also contain virtually anything. It's not limited to what `django.contrib.auth` adds. Until `TypedDict` supports extra values that are not defined we cannot change from `dict[str, Any]`.

See https://github.com/python/mypy/issues/4617

**Comment by danielmoessner** [comment]
I would close this issue and come back to it once TypedDict supports extra values.
