### ISSUE TITLE
collecstatic methods should accept any `Storage`

### ISSUE THREAD

**Issue by antonagestam** [typeddjango/django-stubs#130]
In `django.contrib.staticfiles.management.commands.collectstatic`, the `source_storage` argument is annotated as `django.core.files.storage.FileSystemStorage`. I believe this is incorrect and should actually be `django.core.files.storage.Storage`.

https://github.com/typeddjango/django-stubs/blob/master/django-stubs/contrib/staticfiles/management/commands/collectstatic.pyi#L26

**Comment by sobolevn** [comment]
Yes, that's a bug. Thanks!

**Comment by antonagestam** [comment]
@sobolevn Thanks for that incredibly quick acknowledgment and fix ✨
