### ISSUE TITLE
"OGRGeometry" has no attribute "__iter__" (not iterable)

### ISSUE THREAD

**Issue by StefanBrand** [typeddjango/django-stubs#1333]
# Bug report

## What's wrong

Iterating on the return type of `Layer.get_geoms` throws:

`"OGRGeometry" has no attribute "__iter__" (not iterable)`

I think these lines are wrong:

https://github.com/typeddjango/django-stubs/blob/2e504dff6042a792c2a4f6f1b85e77a02c9029d6/django-stubs/contrib/gis/gdal/layer.pyi#L43-L46

## How is that should be

```py 
>>> type(layer.get_geoms())
<class 'list'>
>>> type(layer.get_geoms()[0])
<class 'django.contrib.gis.gdal.geometries.Polygon'>
>>> type(layer.get_geoms(geos=True)[0])
<class 'django.contrib.gis.geos.polygon.Polygon'>
```

I think the type definitions should be as follows (mind also the switched `geos` parameter):

```py
    @overload
    def get_geoms(self, geos: Literal[False] = ...) -> list[OGRGeometry]: ...
    @overload
    def get_geoms(self, geos: Literal[True]) -> list[GEOSGeometry]: ...
```
What do you think, @ciscorn? 

## System information

- OS: Docker image `python:3.9.16-bullseye`
- `python` version: 3.9.16
- `django` version: 4.1.4
- `mypy` version: 0-991
- `django-stubs` version: 1.13.2

**Comment by intgr** [comment]
Related PR: #1299

**Comment by ciscorn** [comment]
@StefanBrand @intgr 
Thank you for reporting. I've made a PR.
