### ISSUE TITLE
error: "bytes" has no attribute "tobytes" 

### ISSUE THREAD

**Issue by StefanBrand** [typeddjango/django-stubs#1336]
# Bug report

## What's wrong

mypy: `error: "bytes" has no attribute "tobytes" `

Contrary to `shapely.LineString` the `wkb` property of `django.contrib.gis.geos.LineString` is not of type `bytes`, but of type `memoryview`.

```py
>>> type(geometry.boundary)
<class 'django.contrib.gis.geos.collections.MultiLineString'>
>>> type(geometry.boundary.wkb)
<class 'memoryview'>
>>> type(geometry.boundary.wkb.tobytes())
<class 'bytes'>
```

https://github.com/typeddjango/django-stubs/blob/2e504dff6042a792c2a4f6f1b85e77a02c9029d6/django-stubs/contrib/gis/gdal/geometries.pyi#L62-L63

## How is that should be

Probably:

```py
 @property 
 def wkb(self) -> memoryview: ... 
```
cc @ciscorn 

Background information:
- Commit updating Django docs: https://github.com/django/django/commit/7c884afe5acc00d1df83390848227f42918ec0d4
- Commit giving details about `bytes` vs `memoryview`: https://github.com/python/typing/commit/f6c17dd8ccca955374e465172de44e04b0a6c037

## System information

- OS: Docker image `python:3.9.16-bullseye`
- `python` version: 3.9.16
- `django` version: 4.1.4
- `mypy` version: 0-991
- `django-stubs` version: 1.13.2

**Comment by intgr** [comment]
If you're up for it, for simple changes like this, you could also try submitting a PR.

**Comment by intgr** [comment]
ciscorn already added this to the existing PR. 👍

**Comment by StefanBrand** [comment]
> If you're up for it, for simple changes like this, you could also try submitting a PR.

Cool, I'll keep it in mind in case I find something else. I've seen that this one is already covered in #1335
