### ISSUE TITLE
Correctly type `vary_on_headers` decorator

### ISSUE THREAD

**Issue by intgr** [typeddjango/django-stubs#1340]
## What's wrong

Noticed this while reviewing #1339. The `vary_on_headers` decorator doesn't preserve the type (arguments and return) when used on a function.

**Comment by RyanWalker277** [comment]
Hey @intgr @adamchainz! Wanted to ask a few things about this one. In https://github.com/typeddjango/django-stubs/blob/master/django-stubs/views/decorators/vary.pyi , what does the definition of `vary_on_headers` here imply? Are we overriding the decorator funciton here? One approach I could think of is wrapping the whole definition into `functools.wraps` decorator. Not sure how good that would be or whether it would even work or not? Would appreciate your feedback!

**Comment by intgr** [comment]
`functools.wraps` doesn't help AFAIK. I could be wrong.

There are lots of examples of decorators already, I think you can look at `require_http_methods` which behaves similarly.

Here's mypy documentation on type hinting decorators: https://mypy.readthedocs.io/en/stable/generics.html#declaring-decorators

**Comment by adamchainz** [comment]
Please don't @ particular people on issues, those who have notifications will notice.

**Comment by RyanWalker277** [comment]
I have raised a PR ( #1370 ) for this. For a more accurate type annotation, I utilised a parameter specification (ParamSpec). Kindly review.
