### ISSUE TITLE
Next release planning (1.16.0; django-stubs-ext 0.8.0)

### ISSUE THREAD

**Issue by intgr** [typeddjango/django-stubs#1372]
Will be making a release soon-ish (TM). If someone is waiting to get their PR reviewed, or a merged PR released, please mention here.

**Comment by intgr** [comment]
We'll probably want to update recommended & CI mypy to 1.1.1.

<details><summary>Collapsed error output from mypy 1.1.1</summary>
This needs fixing: https://github.com/typeddjango/django-stubs/actions/runs/4350182908/jobs/7600636354

```
django-stubs/utils/datastructures.pyi:68: error: Signature of "setdefault" incompatible with supertype "MutableMapping"
django-stubs/utils/datastructures.pyi:68: note:      Superclass:
django-stubs/utils/datastructures.pyi:68: note:          @overload
django-stubs/utils/datastructures.pyi:68: note:          def setdefault(self, _K, None = ..., /) -> Optional[_V]
django-stubs/utils/datastructures.pyi:68: note:          @overload
django-stubs/utils/datastructures.pyi:68: note:          def setdefault(self, _K, _V, /) -> _V
django-stubs/utils/datastructures.pyi:68: note:      Subclass:
django-stubs/utils/datastructures.pyi:68: note:          def setdefault(self, key: _K, default: _V = ...) -> _V
Found 1 error in 1 file (checked 675 source files)
```

</details>

**Comment by intgr** [comment]
Created PR to update mypy & fix new errors. django-stubs and djangorestframework-stubs:

* #1391
* https://github.com/typeddjango/djangorestframework-stubs/pull/374

**Comment by PIG208** [comment]
It would also be great if we get a new release for `django-stubs-ext`

**Comment by intgr** [comment]
Oops, I didn't realize there were unreleased items in django-stubs-ext. Thanks @PIG208 for pointing out, I will make a release of that as well.

**Comment by intgr** [comment]
django-stubs-ext 0.8.0 released:

* https://pypi.org/project/django-stubs-ext/0.8.0/#history
* https://github.com/typeddjango/django-stubs/releases/tag/django-stubs-ext%400.8.0

**Comment by intgr** [comment]
django-stubs 1.16.0 released:

* https://pypi.org/project/django-stubs/1.16.0/#history
* https://github.com/typeddjango/django-stubs/releases/tag/1.16.0

**Comment by intgr** [comment]
Aaaand djangorestframework-stubs 1.10.0 released too:

* https://pypi.org/project/djangorestframework-stubs/1.10.0/#history
* https://github.com/typeddjango/djangorestframework-stubs/releases/tag/1.10.0
