### ISSUE TITLE
How to use types from django-stubs

### ISSUE THREAD

**Issue by rvanlaar** [typeddjango/django-stubs#1374]
As the title mentions, how can I use types from django-stubs  in my own code?

Example, I have a custom login_required that mimicks django's behavior, but with an extra check.
Preferable I would use the '_VIEW' type directly in my own code.

Is this possible?

<https://github.com/typeddjango/django-stubs/blob/cf8c0a65a61bfa452ae9c4883a56336fb732f3b0/django-stubs/contrib/auth/decorators.pyi>

**Comment by intgr** [comment]
Yes, it's possible to use private types (starting with `_`) defined in django-stubs, but it's not a good idea. They aren't stable between releases and using them requires jumping through some hoops.

For `TypeVar`s in particular it's common to duplicate them in each file you need them.

But here's an example how to do it. You need to guard the import behind `TYPE_CHECKING`, and use quotes in the type hints that use it.

```python
from typing import Callable, TYPE_CHECKING

if TYPE_CHECKING:
    from django.contrib.auth.decorators import _VIEW


def my_decorator(arg: str) -> "Callable[[_VIEW], _VIEW]":
    ...
```

**Comment by rvanlaar** [comment]
Ah, just a normal import as if it's in the package itself. 

Also good to know it's not a stable interface.

Thank you very much.
