### ISSUE TITLE
Non-deterministic crash "KeyError: 'model_bases'" with auth models

### ISSUE THREAD

**Issue by intgr** [typeddjango/django-stubs#1383]
# Bug report

I'm able to reproduce this crash mostly with a *clean* cache (`--no-incremental` or `rm -rf .mypy_cache`). If I have a warm cache from scanning some other files, this does not occur.

Just a small annoyance, I don't have time to debug right now, but figured I should report it.

```
.../site-packages/django-stubs/contrib/auth/models.pyi:21: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.0.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6210, in accept
  File "mypy/nodes.py", line 1133, in accept
  File "mypy/semanal.py", line 1545, in visit_class_def
  File "mypy/semanal.py", line 1625, in analyze_class
  File "mypy/semanal.py", line 1652, in analyze_class_body_common
  File "mypy/semanal.py", line 1735, in apply_class_plugin_hooks
  File ".../site-packages/mypy_django_plugin/main.py", line 44, in transform_model_class
    helpers.get_django_metadata(sym.node)["model_bases"][ctx.cls.fullname] = 1
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'model_bases'
.../site-packages/django-stubs/contrib/auth/models.pyi:21: : note: use --pdb to drop into pdb
```

## System information

- OS: macOS
- `python` version: 3.11.2
- `django` version: 4.1.7
- `mypy` version: 1.0.1
- `django-stubs` version: 1.15.0
- `django-stubs-ext` version: 0.7.0

**Comment by jonodrew** [comment]
I've just started experiencing this

**Comment by intgr** [comment]
@jonodrew Any idea what changed about your project that may have provoked this?

I haven't experienced this crash in my usage any more.

**Comment by intgr** [comment]
Suddenly now this happened to me as well. 🤷

The code is:

```python
def transform_model_class(ctx: ClassDefContext, django_context: DjangoContext) -> None:
    ...
    helpers.get_django_metadata(sym.node)["model_bases"][ctx.cls.fullname] = 1
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

def get_django_metadata(model_info: TypeInfo) -> Dict[str, Any]:
    return model_info.metadata.setdefault("django", {})
```

So it should be entirely expected that `get_django_metadata()` can return empty dict.

Patching it like this at least avoids the exception though probably not correct:
```python
    return model_info.metadata.setdefault("django", {"model_bases": {}})
```

There's also another similar assumption made in another function `transform_form_class()`

**Comment by flaeppe** [comment]
The `"model_bases"` mapping is set by `_get_current_model_bases`.

https://github.com/typeddjango/django-stubs/blob/91dc6d31b8cb8ce49a985727331194ed26bb11c1/mypy_django_plugin/main.py#L94-L101

While the base class hooks e.g. `transform_model_class` is called depending on an `or` conditioned if-statement:

https://github.com/typeddjango/django-stubs/blob/91dc6d31b8cb8ce49a985727331194ed26bb11c1/mypy_django_plugin/main.py#L255-L263

I would suspect that `fullname in self.django_context.all_registered_model_class_fullnames` returns true at a point where `self._get_current_model_bases()` hasn't yet been called and the `or`-statement won't trigger it either.

As such `"model_bases"` hasn't yet been defaultly inserted. But this is just some quick and early guess work, and I have no way of reproducing. I just discovered the code paths.

We have multiple of these state mappings:

https://github.com/typeddjango/django-stubs/blob/91dc6d31b8cb8ce49a985727331194ed26bb11c1/mypy_django_plugin/main.py#L76-L115

Best way, IMO, would be to organise those data structures behind a proper interface. While the quick and dirty way could be to trigger the population inside `django_metadata` once at some early boot(?) point of the plugin
