### ISSUE TITLE
Model has no attribute "objects"

### ISSUE THREAD

**Issue by K0Te** [TypedDjango/django-stubs#14]
Hi,

I've tried installing `django-stubs` and running mypy check on one of my projects.
mypy has zero complaints before, but after installing `django-stubs` it returned ~300 warnings.
Most of them are about various models not having `.objects` attribute.

What approach it recommended in this case ? Is it something that should be fixed in `django-stubs`, or should I use "# type ignore" for such cases ?

**Comment by mkurnikov** [comment]
Try install package from original repo 
https://github.com/mkurnikov/django-stubs
and add 
```
[mypy]
plugins =
    mypy_django_plugin.main
```
to mypy config to enable plugin.

**Comment by mkurnikov** [comment]
It's by no means production-ready, I pushed very first version to pypi couple of days ago. 

For the first issue, try to set `DJANGO_SETTINGS_MODULE` environment variable for your mypy execution, it could help. If it won't, then it's a problem with plugin, please report it with some description. 
It's in the README
https://github.com/mkurnikov/django-stubs#installation
sorry, I've forgotten to mention it. 

Others are valid bugs too, you can create issue or just send PR. Package is very much WIP now, lot to be done - most of the stubs are autogenerated and contain lots of errors.

**Comment by K0Te** [comment]
Thanks a lot ! I'll create separate issues for further findings.
