### ISSUE TITLE
Form.clean returns Optional[dict] instead of dict

### ISSUE THREAD

**Issue by mschoettle** [typeddjango/django-stubs#1403]
# Bug report

## What's wrong

Overriding `clean` on a `Form` subclass brings up the following definition in vscode:

```py
def clean(self) -> Dict[str, Any]:
        return super().clean()
```

However, it raises the following type error:

> Incompatible return value type (got "Optional[Dict[str, Any]]", expected "Dict[str, Any]")  [return-value]

## How is that should be

`Form.cleaned_data` is defined as `dict[str, Any]` (see: https://github.com/typeddjango/django-stubs/blob/master/django-stubs/forms/forms.pyi#L32) whereas `clean` is defined to return `dict[str, Any] | None` (see: https://github.com/typeddjango/django-stubs/blob/master/django-stubs/forms/forms.pyi#L62).

Based on the Django source code it returns `self.cleaned_data` (https://github.com/django/django/blob/main/django/forms/forms.py#L370).

Based on this it should be `dict[str, Any]`.

If there is agreement I will be able to provide a PR for this.

## System information

- OS:
- `python` version: 3.10.10
- `django` version: 4.1.7
- `mypy` version: 1.1.1
- `django-stubs` version: 1.15.0
- `django-stubs-ext` version: 0.7.0

**Comment by adamchainz** [comment]
Form subclasses are allowed to skip returning the dictionary, so the type in form needs to allow none. See previous issue #954. Please search the issue tracker before opening issues.

**Comment by mschoettle** [comment]
Sorry about that! Thanks for the reference.
