### ISSUE TITLE
Don't require `tomli` on Python 3.11

### ISSUE THREAD

**Issue by pawelad** [typeddjango/django-stubs#1408]
# Bug report

## What's wrong

Hi!

I'm in the process of upgrading my app to use Python 3.11 and noticed that the only library that requires `tomli` is `django-stubs`, as all other have it marked as an optional dependency required only if Python version is lower than 3.11.

<img width="878" alt="Screenshot 2023-03-20 at 16 57 32" src="https://user-images.githubusercontent.com/7062874/226398474-12acd3f7-446c-4c4f-9b3a-70675dd0093f.png">

## How is that should be

`django-stubs` should only install `tomli` on Python <3.11  and use `tomllib` on Python 3.11. As far as I understand their interfaces are compatible, which is why all the libraries listed above just use `tomllib` on Python 3.11 and `tomli` on older versions

Example from `black`:

https://github.com/psf/black/blob/ef6e079901d53a42dfae4ab10b081ce7a73a47b5/pyproject.toml#L71

https://github.com/psf/black/blob/ef6e079901d53a42dfae4ab10b081ce7a73a47b5/src/black/files.py#L26-L34

As far as I see, the replacement should be pretty straightforward and I'd be happy to provide a PR.

## System information

- OS: macOS 12.6.3
- `python` version: 3.11.2
- `django` version: 4.1.7
- `mypy` version: 1.0.1
- `django-stubs` version: 1.14.0
- `django-stubs-ext` version: 0.7.0

**Comment by sobolevn** [comment]
PR is welcome!
