### ISSUE TITLE
django-stubs-ext version schema

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#1409]
# Bug report

## What's wrong

I want to automatically update to newer versions of libraries, and so I use a version specifier like `~=1.0` to upgrade to versions  `1.x.x`, hoping that dependencies follow semver. When the version starts with `0`, I need to use `~=0.1.0` to upgrade to all `0.1.x` versions because semver defines bumping the minor version (i.e. `0.2.0`) as a breaking change.

I think django-stubs follows this, at least in spirit, but django-stubs-ext only bumps the minor version: https://pypi.org/project/django-stubs-ext/#history

## How is that should be

I would love for django-stubs-ext to either:

- Bump the patch release for mostly-backward-compatible changes (similar to how django-stubs bumps the minor version), or
- My preference: bump the major version to `1` to match django-stubs and continue bumping the minor version the way we have been

## System information

N/A

**Comment by intgr** [comment]
I think there's no particular reason why we're still using `0.x` versions for django-stubs-ext? @sobolevn?

We should release django-stubs-ext `1.0.0` next time around.

**Comment by sobolevn** [comment]
I think we can release the same version as django has.

Basically like `django-major.django-minor.our-own-patch`

**Comment by sobolevn** [comment]
And we can only claim to support this version. Other versions can be "partially supported".

**Comment by intgr** [comment]
Oh, right, we already had this discussion at https://github.com/typeddjango/django-stubs/issues/1095#issuecomment-1307066177.
