### ISSUE TITLE
Don't expose delete() on Manager

### ISSUE THREAD

**Issue by mschoettle** [typeddjango/django-stubs#1426]
# Bug report

## What's wrong

Given a model `Foo`, calling `Foo.objects.delete()` on it passes type checking but fails at runtime:

> AttributeError: 'Manager' object has no attribute 'delete'

## How is that should be

Can we remove `delete()` from `Manager`?

Django docs: https://docs.djangoproject.com/en/dev/topics/db/queries/#deleting-objects

> Note that [delete()](https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.delete) is the only [QuerySet](https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet) method that is not exposed on a [Manager](https://docs.djangoproject.com/en/dev/topics/db/managers/#django.db.models.Manager) itself. This is a safety mechanism to prevent you from accidentally requesting Entry.objects.delete(), and deleting all the entries.

## System information

- OS:
- `python` version: 3.10.10
- `django` version: 4.1.7
- `mypy` version: 1.1.1
- `django-stubs` version: 1.16.0
- `django-stubs-ext` version:

**Comment by sobolevn** [comment]
Oh, very interesting! Thanks for the report. PR is welcome.
