### ISSUE TITLE
Internal Error on Model Query

### ISSUE THREAD

**Issue by slayb3ar** [typeddjango/django-stubs#1433]
# Bug report

## System information

- OS:
- `python` 3.10.5:
- `django` 4.1.8:
- `mypy` 1.1.1:
- `django-stubs` 1.16.0:
- `django-stubs-ext` version:

**Comment by intgr** [comment]
This issue is missing a description. I can re-open when you have added a description, or report a new issue.

**Comment by slayb3ar** [comment]
ah sorry @intgr , not sure what happened but issue body was totally wiped 😢 
I've downgraded for now and issue is gone. When I find some time I will try and upgrade / replicate / re-open
