### ISSUE TITLE
ManyToManyRawIdWidget expects to be initialized with a ManyToOneRel

### ISSUE THREAD

**Issue by pheki** [typeddjango/django-stubs#1435]
# Bug report

## What's wrong

ManyToManyRawIdWidget expects `__init__` to be called with a ManyToOneRel:

```console
error: Argument 1 to "ManyToManyRawIdWidget" has incompatible type "ManyToManyRel"; expected "ManyToOneRel"  [arg-type]
```

This happens because ManyToManyRawIdWidget subclasses ForeignKeyRawIdWidget, which (correcly) takes a ManyToOneRel. 

## How is that should be

ManyToManyRawIdWidget uses a ManyToManyRel, so that should be accepted.

Maybe we could force `__init__` to take ManyToManyRel and `# type: ignore[override]` it, just like it's done for the rel attribute: https://github.com/typeddjango/django-stubs/blob/be609f1962351b99ff228309e8039ea2768bf1e0/django-stubs/contrib/admin/widgets.pyi#L52

That would violate [Liskov substitution principle](https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides), but it seems that this class already does it anyway.

## System information

- OS: linux
- `python` version: 3.8.8
- `django` version: 3.2.18
- `mypy` version: 1.1.1
- `django-stubs` version: 1.16.0
- `django-stubs-ext` version: 0.8.0

**Comment by intgr** [comment]
> That would violate [Liskov substitution principle](https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides), but it seems that this class already does it anyway.

Yep. It's no problem though, Python constructors frequently violate LSP. In fact, **every** constructor that has required arguments violates LSP because it's incompatible with `object.__init__`. 😆

I believe the Python type-checking community has taken the view that LSP should apply to class instances, but is relaxed for _class types_.

**Comment by pheki** [comment]
I see, I'll create a PR for that then

Edit: nevermind, I just realized there is already a PR!
