### ISSUE TITLE
Incorrect type revealed for `.select_related(...)`

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#145]
Here's my code:

```python
# -*- coding: utf-8 -*-

from server.apps.main.models import BlogPost


def post_dates_by_author(author_id: int):
    """Returns published blog posts."""
    x = BlogPost.objects.filter(
        author__id=author_id,
    ).select_related('author')
    reveal_type(x)
    return x
```

Output:

```
» PYTHONPATH="$PYTHONPATH:$PWD" mypy server
server/apps/main/logic/repo.py:20: note: Revealed type is 'django.db.models.manager.Manager[server.apps.main.models.BlogPost]'
```

Note, that it is `django.db.models.manager.Manager` and not `django.db.models.query.QuerySet`.

That's what it should return:

```python
In [1]: from server.apps.main.models import BlogPost                                  

In [2]: x = BlogPost.objects.filter(author_id=1).select_related('author')             

In [3]: type(x)                                                                       
Out[3]: django.db.models.query.QuerySet
```

Reproduction: https://github.com/sobolevn/django_stubs_example/blob/master/server/apps/main/logic/repo.py

**Comment by mkurnikov** [comment]
Related to new queryset type `ValuesQuerySet` mentioned here https://github.com/typeddjango/django-stubs/issues/145

**Comment by sobolevn** [comment]
@mkurnikov you might be interested: https://sobolevn.me/2019/08/typechecking-django-and-drf

I wrote a tutorial for complete beginners about TypedDjango. I will write about `pytest-mypy-plugin` next week. Thanks a lot for your work!

**Comment by ygwain** [comment]
Thanks to your work guys.
So the only way to get a correct type for the regular `QuerySet` methods like `all`, `filter`, `select_related` etc is to explicitly annotate their results?
