### ISSUE TITLE
Missing stub for django.shortcuts.reverse

### ISSUE THREAD

**Issue by Salaah01** [typeddjango/django-stubs#1466]
# Bug report

## What's wrong
Getting an error with the following bit of code:

```python
from django.shortcuts import reverse
```

It gives the following error:

```
Module "django.shortcuts" has no attribute "reverse"  [attr-defined]
```

## How is that should be

Should be able to run the line of code I mentioned.

## System information

- OS: Ubuntu 20.04
- `python` version: 3.11.3
- `django` version: 4.1.7
- `mypy` version: 1.2.0
- `django-stubs` version: 1.16.0
- `django-stubs-ext` version: 0.8.0

**Comment by intgr** [comment]
Hi

You should use `from django.urls import reverse` instead, see https://docs.djangoproject.com/en/4.2/ref/urlresolvers/#django.urls.reverse

Django does happen to import `reverse` in `django.shortcuts`, but these incidential imports aren't stable and should not be used.
