### ISSUE TITLE
contrib.gis PointField typing

### ISSUE THREAD

**Issue by martinlehoux** [typeddjango/django-stubs#1479]
Hi, I would like to help and add a stronger typing to geo fields (the one I use is PointField).
My issue today is that I have a `coordinates = models.PointField()` field, but when I use the value, it is typed as any.

I believe we could have the same approach in [PointField](https://github.com/typeddjango/django-stubs/blob/5f57a42110e04ac1bd451ac42923da89e5c3b7f0/django-stubs/contrib/gis/db/models/fields.pyi#LL115C18-L115C31) as in [CharField](https://github.com/typeddjango/django-stubs/blob/5f57a42110e04ac1bd451ac42923da89e5c3b7f0/django-stubs/db/models/fields/__init__.pyi#L273)

What do you think? Let me known if I should work on this.

**Comment by sobolevn** [comment]
You totally should! It would be an amazing addition.
Thanks a lot! 👍

**Comment by martinlehoux** [comment]
Looks good!
