### ISSUE TITLE
RegexValidator is treated as invalid validator

### ISSUE THREAD

**Issue by WhyNotHugo** [typeddjango/django-stubs#1480]
# Bug report

I have a validator which subclasses `RegexValidator` (which itself is `Callable`) ,but using it as a `validator` in a `forms.CharField` results in an error.

## What's wrong

```py
class NameValidator(RegexValidator):
    regex = r"^[a-z áéíóúüñ]+$"
    flags = re.IGNORECASE
    message = _("Only letters (with or without tildes) and spaces are allowed.")
```

And:

```py
class ProfileCompletionForm(forms.ModelForm):
    first_name = forms.CharField(
        label=_("Name"),
        min_length=2,
        max_length=64,
        validators=[NameValidator],
    )
```

Results in this error:

```
List item 0 has incompatible type "Type[NameValidator]"; expected "Callable[[Any], None]"  [list-item]
```

However, type `NameValidator` _is_ callable.

## How is that should be

This should not error, but I'm not entirely sure why this is not considered a callable.

## System information

OS: Linux 6.3.0-0-edge x86_64 Linux
python version: Python 3.11.3
django version: Django==4.1.9
mypy version: mypy==1.2.0
django-stubs version: django-stubs==4.2.0
django-stubs-ext version: django-stubs-ext==4.2.0

**Comment by intgr** [comment]
Does this actually work in Django?

I think you need to instanciate the validator first for this to work:

```patch
-        validators=[NameValidator],
+        validators=[NameValidator()],
```

**Comment by WhyNotHugo** [comment]
> Does this actually work in Django?

It does. To validate something you call the type, e.g.:

    NameValidator("some name")

**Comment by WhyNotHugo** [comment]
I think my usage worked mostly by coincidence.

**Comment by intgr** [comment]
Saved by the type checker ✅

**Comment by WhyNotHugo** [comment]
It's funny that this worked (since 2020 and had extensive coverage).

There was a fun hidden bug here though: I was returning the result from the `NameValidator` call in a function that returned `bool`. This worked because the validator raises if the value is invalid or returns None (which is falsy) otherwise. The call site always tried to raise of the result was False, so everything worked, by sheer coincidence.
