### ISSUE TITLE
Model field arg `db_comment` not supported

### ISSUE THREAD

**Issue by andrlik** [typeddjango/django-stubs#1490]
# Bug report

When using the field option `db_comment` introduced in Django 4.2, it triggers mypy errors such as the below.

## What's wrong

Given a model with the following structure:

```python
from django.db import models
from django.utils.translation import gettext_lazy as _

class Task(models.Model):
    title = models.CharField(max_length="250", help_text=_("The title of the task"))
    notes = models.TextField(
        blank=True,
        null=True,
        help_text=_("Additional notes about the task; markdown formatting supported."),
        db_comment="Additional notes about the task. May contain markdown."
    )

    def __str__(self):
        return self.title
```

You get the following call-arg error for it when running `mypy`.

```shell
taskhub/models.py:75:13: error: Unexpected keyword argument "db_comment" for "TextField"  [call-arg]
        notes = models.TextField(
                ^
```
## How is that should be

It should not throw an error on that field definition. 

As a workaround for now, I'm adding `# type: ignore[call-arg]` on the fields where I'm using `db_comment`, but obviously that's less than ideal.

## System information

- OS:
- `python` version: 3.11.2
- `django` version: 4.2.1
- `mypy` version: 1.2.0
- `django-stubs` version: 4.2.0
- `django-stubs-ext` version: 4.2.0

**Comment by sobolevn** [comment]
PR is welcome!

**Comment by andrlik** [comment]
Ask and ye shall receive! :smile:
