### ISSUE TITLE
Generic Views, self.request.user.id

### ISSUE THREAD

**Issue by JoaoHenrique12** [typeddjango/django-stubs#1506]
# Bug report

## What's wrong

I'm using pyright with Neovim LSP to code a simple django app.
When I acess self.request.user.id in a UpdateView, is displayed an error.

![Screenshot from 2023-05-20 01-10-38](https://github.com/typeddjango/django-stubs/assets/42558165/e2b6a58f-b417-4285-a8c6-5634ca1f57d4)

## How is that should be

That error should not be displayed, when i run my django server everything goes ok.

## System information

- OS:
- `python` version: 3.10.6
- `django` version: 4.1.7
- `mypy` version: 1.1.1
- `django-stubs` version: 1.16.0
- `django-stubs-ext` version: 0.8.0

**Comment by adamchainz** [comment]
This seems like a specific instance of the problem described in the FAQ: https://github.com/typeddjango/django-stubs#how-can-i-create-a-httprequest-thats-guaranteed-to-have-an-authenticated-user

In the stubs we can only guarantee that `self.request.user` is an `AbstractBaseUser`, which has limited attributes. It doesn’t constrain the field name for the primary key. However you are using a subclass, maybe the `User` concrete class provided by Django, that has an `id` field.

You can swap to `self.request.user.pk`, the always-available primary key attribute, for this particular case. But you will see errors for other fields. Constraining the request to an authenticated subclass as per the FAQ I linked previously will stop this kind of error for you.
