### ISSUE TITLE
Cannot resolve shared manager/queryset method for union

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#1532]
# Bug report

## What's wrong

I have two models with matching managers and querysets, and sometimes use them as a union.

```python3
model: type[Foo] | type[Bar]

result = model.objects.shared_method()
```

```
Unable to resolve return type of queryset/manager method "shared_method" 
```

## How is that should be

`result` is inferred as the union of return types of `Foo.objects.shared_method()` and `Bar.objects.shared_method()`.

## System information

- OS: Docker `Linux b5ca85c5b236 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux`
- `python` version: 3.11
- `django` version: 4.2
- `mypy` version: 1.3
- `django-stubs` version: 4.2.1
- `django-stubs-ext` version: 4.2.1

**Comment by sobolevn** [comment]
PR to the plugin code is welcome!

**Comment by delfick** [comment]
@sobolevn good suggestion, https://github.com/typeddjango/django-stubs/pull/2027 :)
