### ISSUE TITLE
File.size: Unsupported operand types for "Callable" and "int".

### ISSUE THREAD

**Issue by wlisesrivas** [typeddjango/django-stubs#154]
Django File.size is a property type:
`
@cached_property 
def size(self):
...
`
https://github.com/django/django/blob/master/django/core/files/base.py#L32

But in stubs it's treated like callable function (which is wrong):
`
def size(self) -> int: 
...
`
https://github.com/typeddjango/django-stubs/blob/master/django-stubs/core/files/base.pyi#L17

**Comment by sobolevn** [comment]
@wlisesrivas can you please change `def size(self) -> int: ...` to be `@property`?

**Comment by wlisesrivas** [comment]
@sobolevn you mean create a pull-request fixing that? If so, sure.

**Comment by sobolevn** [comment]
Yes 🙂

**Comment by sobolevn** [comment]
Closed by #156
