### ISSUE TITLE
Signature of "get" incompatible with supertype "TemplateView"  [override]

### ISSUE THREAD

**Issue by rvanlaar** [typeddjango/django-stubs#1564]
# Bug report

## What's wrong

When using urls with a pattern, those elements are given to the view as arguments.
For example: `path("module/<int:module_id>", ModuleView.as_view())` will call the get of a TemplateView as
`get(self, request, module_id)`.
This will result in the error:  Signature of "get" incompatible with supertype "TemplateView"  [override]

## How is that should be

What's the recommended way to type those functions?

## System information

- OS: debian 11 (bullseye)
- `python` version: 3.9.17
- `django` version: 3.2.19
- `mypy` version: 1.1.1
- `django-stubs` version: 1.16.0
- `django-stubs-ext` version: 4.2.1

**Comment by UnknownPlatypus** [comment]
The signature of `TemplateView.get` is the following:
```python
def get(self, request, *args, **kwargs):
    context = self.get_context_data(**kwargs)
    return self.render_to_response(context)
```
You are defining another signature for the get method here, hence the error.
One way to fix you issue would be to do that:

```python
def get(self, request, *args, **kwargs):
    module_id = kwargs["module_id"]
    ...
```

To allow you syntax and more accurate type inference, I guess this would need plugin support checking the urlpatterns definition (I'm not even sure it really possible)

**Comment by adamchainz** [comment]
I don't think it's generally possible since views can be mapped to many URLs, plus `View` classes could have different signatures between different HTTP method method like `get()` and `post()`

**Comment by rvanlaar** [comment]
Plugin support for checking the url pattern would be great.

This is one of the places where I feel like python and typing is making me jump through hoops.

Feel free to close this issue.
