### ISSUE TITLE
Support `report_config_data` mypy plugin hook

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#1568]
When the configuration of our plugin changes, mypy cache is not reset. So, settings are not changed.
There might be other side-effects of this.

I will send a PR shortly.

Docs: https://mypy.readthedocs.io/en/stable/extending_mypy.html?highlight=report_config_data#current-list-of-plugin-hooks

**Comment by christianbundy** [comment]
Interesting, good call. I wonder whether this will help with dmypy runs where changing models [currently] requires restarting dmypy.
