### ISSUE TITLE
django.core.mail.outbox: EmailMultiAlternatives?

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#1584]
# Bug report

I'm observing under test that the mail outbox contains `EmailMultiAlternatives` instead of `EmailMessage` -- this is leading to lots of false-positives by the type checker -- I'm not sure which is correct however 🤔 

## What's wrong

an example error:

```python
        assert "group-header" in msg.alternatives[0][0]
```

```
tests/sentry/mail/test_adapter.py:1541: error: "EmailMessage" has no attribute alternatives"  [attr-defined]
```

## How is that should be

I'm not sure!

## System information

- OS:
- `python` version: 3.8.16
- `django` version: eheh, old
- `mypy` version: 1.3.0
- `django-stubs` version: 4.2.0
- `django-stubs-ext` version: 4.2.0

**Comment by adamchainz** [comment]
`EmailMultiAlternatives` is an `EmailMessage` subclass, and it will appear if the appropriate email-sending functions/classes are used: https://docs.djangoproject.com/en/4.2/topics/email/#sending-alternative-content-types .

Tests need to type narrow before accessing the `EmailMultiAlternatives`-specific attributes:

```python
assert isinstance(msg, EmailMultiAlternatives)
assert "group-header" in msg.alternatives[0][0]
```

I don't think there's anything we can do in the stubs to avoid this requirement.

> `django` version: eheh, old

lol
