### ISSUE TITLE
`AppConfig.default_auto_field` -- Incompatible types in assignment

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#1593]
# Bug report

```python3
class FooConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "foo"
```

## What's wrong

> Incompatible types in assignment (expression has type "str", base class "AppConfig" defined the type as "Callable[[AppConfig], str]")  [assignment]

```python3
default_auto_field = "django.db.models.BigAutoField"
```

## How is that should be

No error.

## System information

- OS: N/A
- `python` version: 3.11
- `django` version: 4.1
- `mypy` version: 1.4
- `django-stubs` version: 4.2.2
- `django-stubs-ext` version: 4.2.2

**Comment by intgr** [comment]
I presume this is a regression from django-stubs 4.2.2?

`AppConfig.default_auto_field` was changed in #1583. I think we should just change it back and add this to `stubtest/allowlist.txt`

**Comment by christianbundy** [comment]
Yep, you got it -- this is a new error from upgrading to django-stubs 4.2.2.

**Comment by XF-FW** [comment]
Yep, can confirm, just hit it too.
