### ISSUE TITLE
Compatibility with mypy 0.730

### ISSUE THREAD

**Issue by blueyed** [typeddjango/django-stubs#160]
Using `mypy 0.730+dev.28423cd78062b81365ec9aaa591b4e823af1606d` I am seeing an error:

> setup.cfg:55: error: Error importing plugin 'mypy_django_plugin.main'

The exception there is:

> No module named 'mypy.newsemanal.semanal'

I've not investigated, but are there plans to make it compatible with the upcoming mypy version?
Pinning it to "<0.730" was done in b11a9a8.

**Comment by zacchiro** [comment]
yup, same here: due to this I can't use this plugin with recent versions of mypy (0.720 here)

**Comment by sobolevn** [comment]
@zacchiro `0.720` works fine for me. Please, check that you use `django-stubs@1.1`.

**Comment by zacchiro** [comment]
> @zacchiro `0.720` works fine for me. Please, check that you use `django-stubs@1.1`.
```
$ pip show django-stubs
Name: django-stubs
Version: 1.1.0
Summary: Mypy stubs for Django
```

**Comment by sobolevn** [comment]
@zacchiro ok 😞 

Then, please create a new issue for your case. This one is specifically for `0.730`. And `0.720` should be supported, that's a bug.

**Comment by zacchiro** [comment]
> Then, please create a new issue for your case. This one is specifically for `0.730`. And `0.720` should be supported, that's a bug.

*nod*, here it is: #166

**Comment by mkurnikov** [comment]
@blueyed Regarding this error specifically
> No module named 'mypy.newsemanal.semanal'

I've merged a fix in https://github.com/typeddjango/django-stubs/pull/165/files#diff-4220d6302939b8f0164e64a68181a0d4R25

As for 0.730 in general, we'll going to make it compatible as long as 0.730 mypyc build is out. Version installed directly from repo is too slow to run tests on / debug. New release for django-stubs will follow.

**Comment by zacchiro** [comment]
I'm sure the maintainers are aware, but for other lurkers following this issue: mypy 0.730 has been released yesterday and is indeed incompatible with the most recent release of django-stubs available on PyPI.

**Comment by zacchiro** [comment]
hey, thanks a lot for this !

do you have any ETA for releasing 1.2.0? Given mypy is often used in CI toolchains that pull directly from PyPI, it would be very useful to have a django-stubs version there that is compatible with the mypy version there

**Comment by sobolevn** [comment]
@zacchiro here's the release plan: https://github.com/typeddjango/django-stubs/milestone/1

**Comment by zacchiro** [comment]
On Tue, Oct 01, 2019 at 05:00:21AM -0700, Nikita Sobolev wrote:
> @zacchiro here's the release plan: https://github.com/typeddjango/django-stubs/milestone/1

Thanks !
