### ISSUE TITLE
Hotfix release (4.2.3)

### ISSUE THREAD

**Issue by intgr** [typeddjango/django-stubs#1605]
Fixes two regressions:

* https://github.com/typeddjango/django-stubs/pull/1596
* https://github.com/typeddjango/django-stubs/pull/1595

**Comment by intgr** [comment]
And it's out!

* Release notes: https://github.com/typeddjango/django-stubs/releases/tag/4.2.3
* PyPI: https://pypi.org/project/django-stubs/4.2.3/#history

**Comment by adamchainz** [comment]
Thanks @intgr
