### ISSUE TITLE
DefaultStorage has no attribute "url"

### ISSUE THREAD

**Issue by mlazar-endear** [typeddjango/django-stubs#1610]
# Bug report

## What's wrong

I am seeing a regression after updating from ``django-stubs==4.2.0`` to ``django-stubs==4.2.3``. This PR appears to be the source of the issue: https://github.com/typeddjango/django-stubs/pull/1488

All of the attributes for the `default_storage` django object now raise type errors.

```python
from django.core.files.storage import default_storage

default_storage.url("filename")
...
```

```
error: "DefaultStorage" has no attribute "url"  [attr-defined]
error: "DefaultStorage" has no attribute "listdir"  [attr-defined]
error: "DefaultStorage" has no attribute "get_modified_time"  [attr-defined]
error: "DefaultStorage" has no attribute "delete"  [attr-defined]
...
```

I understand that this object is difficult to annotate because it's lazy loaded from the user's settings, but I would at least expect the attributes and methods on the base `Storage` class to be allowed.

https://docs.djangoproject.com/en/4.2/ref/files/storage/#the-storage-class

## How is that should be

Using the `default_storage` object, as described by the django docs, should not raise type errors.

## System information

- `python` version: 3.10
- `django` version: 3.1.10
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.2

**Comment by jewelvadim** [comment]
Hello, have the same problem :(
Please, patch it, if it is not a problem)

https://stackoverflow.com/questions/76595587/how-to-solve-mypy-error-for-django-abstract-class

**Comment by jewelvadim** [comment]
Still have this error even in v4.2.4

**Comment by sobolevn** [comment]
PR is welcome, it is an easy one to do :)

**Comment by jewelvadim** [comment]
@sobolevn I thought this one will fix the problem)

https://github.com/typeddjango/django-stubs/pull/1665
