### ISSUE TITLE
View.http_method_names should be Iterable

### ISSUE THREAD

**Issue by 93578237** [typeddjango/django-stubs#1615]
# Bug report

## What's wrong
This is valid code:
```python
from django.views.generic.base import View
class MyView(View):
    http_method_names = ('get',)
```

## How is that should be
`http_method_names` should be `Iterable[str]` instead of `list[str]`.

## System information

- OS: Linux
- `python` version: 3.11.4
- `django` version: 4.2.3
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.2

**Comment by adamchainz** [comment]
I think Sequence or Container should be appropriate, but not Iterable because that allows generators.
