### ISSUE TITLE
get_group_by_cols does not seem to have the correct type

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#1623]
# Bug report

it seems to always have had `-> list[Self]` (but in various forms through the history)

## What's wrong

however looking at the implementation it is finding sub-expressions and attempting to extract columns from it? 

https://github.com/django/django/blob/7f2bc365b3652eaa8a8c19e58ddd35f062c68dbc/django/db/models/expressions.py#L434-L435

## How is that should be

I suspect it should be `-> list[BaseExpression]` or really `list[Any]` since the return is a union of everything with `contains_aggregate` being `False`

## System information

- OS:
- `python` version: irrelevant
- `django` version: HEAD
- `mypy` version: irrelevant
- `django-stubs` version: HEAD
- `django-stubs-ext` version: HEAD

**Comment by asottile-sentry** [comment]
apologies, I am very not used to a mac keyboard and pressed something+enter which caused it to earlypost -- edited the information in after the fact

**Comment by adamchainz** [comment]
Without looking too hard, I think it should probably be `list[BaseExpression]`, would you like to make the PR?
