### ISSUE TITLE
Instantiating an abstract model yields no error

### ISSUE THREAD

**Issue by flaeppe** [typeddjango/django-stubs#1624]
# Bug report

Simple example where Django raises, while `django-stubs` doesn't

```python
from django.contrib.auth.models import AbstractUser
AbstractUser()
# Traceback (most recent call last):
#  File "/usr/local/lib/python3.10/code.py", line 90, in runcode
#    exec(code, self.locals)
#  File "<console>", line 1, in <module>
#  File "/app/venv/lib/python3.10/site-packages/django/db/models/base.py", line 467, in __init__
#    raise TypeError("Abstract models cannot be instantiated.")
# TypeError: Abstract models cannot be instantiated.
AbstractUser.objects.create()
# Traceback (most recent call last):
#  File "/usr/local/lib/python3.10/code.py", line 90, in runcode
#    exec(code, self.locals)
#  File "<console>", line 1, in <module>
#  File "/app/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 191, in __get__
#    raise AttributeError(
# AttributeError: Manager isn't available; AbstractUser is abstract
```

This isn't really any serious issue though, since one will get smacked with a runtime error quite quickly. Just thought it was worth reporting.

If anything, this could clean up our test suite in regards to abstract models..

Ref: #1393 

## What's wrong

There's no complaints from `django-stubs`

## How is that should be

There should be errors on both initialisation and usage of manager of an abstract model.

## System information

- OS:
- `python` version: 3.10
- `django` version: 4.2.2
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.2
- `django-stubs-ext` version: 4.2.2

**Comment by sobolevn** [comment]
Plugin can set `TypeInfo.is_abstract` to fix this. I will send a PR.

**Comment by flaeppe** [comment]
That sounds like a great approach!

**Comment by flaeppe** [comment]
I get a feeling the plugin could then read and use that value in other places too.

Could be preferable to resolve/fetch a model to guard against abstract, if that happens
