### ISSUE TITLE
ManyToManyField is typed as `RelatedManager[<model>] | None` rather than just `RelatedManager[<model>]`

### ISSUE THREAD

**Issue by PureTryOut** [typeddjango/django-stubs#1638]
## What's wrong

I have the following model:

```
class Customer(User):
    addresses = models.ManyToManyField(
        Address,
        related_name="customers",
        null=True,
        blank=True,
    )
```

`addresses` here is typed as `RelatedManager[<model>] | None`. meaning any queryset call on it will make mypy complain about the attribute not existing. For example:

```
project/views/address.py:68: error: Item "None" of "RelatedManager[Address] | None" has no attribute "add"  [union-attr]
project/views/address.py:93: error: Item "None" of "RelatedManager[Address] | None" has no attribute "get"  [union-attr]
project/views/address.py:97: error: Item "None" of "RelatedManager[Address] | None" has no attribute "remove"  [union-attr]
```

However, it never is `None`, and I'm not sure how it could be either. If there are no addresses for a customer than `customer.addresses.exists()` would just return false rather than `customer.addresses` being `None`.

## How is that should be

It should be typed as just `RelatedManager[<model>]`.

## System information

- OS: Linux
- `python` version: 3.11
- `django` version: 4.2
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: not installed

**Comment by sobolevn** [comment]
Does `null=True` or `blank=True` affect `| None` part?

**Comment by andersk** [comment]
The `ManyToManyField` documentation [says](https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.ManyToManyField.swappable)

> [`null`](https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.Field.null) has no effect since there is no way to require a relationship at the database level.

and in fact the system check framework raises the [`fields.W340` warning](https://docs.djangoproject.com/en/4.2/ref/checks/#related-fields) for this. django-stubs should ignore `null` here too, but meanwhile you can just remove it.
