### ISSUE TITLE
related name not found when the model definitions are not in app_name/models.py

### ISSUE THREAD

**Issue by MoranAbadieGatewatcher** [typeddjango/django-stubs#1643]
# Bug report

I'm encountering a problem related to attribute referencing in Django models and I have managed to simplify the issue as follows:

```
from django.db import models

class Test(models.Model):
    example1 = models.IntegerField()

class NotTest(models.Model):
    example2 = models.OneToOneField(Test, on_delete=models.CASCADE, related_name="test_related_name")

def test():
    a = Test()
    a.example1 = "1"
    a.test_related_name.save()
```
When executing the above, I receive the error: "Test has no attribute 'test_related_name'". This problem seems to occur when the model definitions aren't located in the standard app_name/models.py directory.

Here's my current application structure (for the simplified example):
```
src/test/
├── apps.py
├── __init__.py
├── models
│   ├── __init__.py
│   └── test.py
```

## What's wrong

What's particularly perplexing is that the error appears inconsistently across various environments. For example, the code runs without any issues in some environments (like tox, despite having identical configurations), but in others, it does not.

I have noticed that sometimes (not always), when I use mypy to scan files individually (i.e., mypy src/app_name/folder/file.py), it works as expected. However, when scanning the entire directory (mypy src/app_name/folder/, with an empty `__init__.py` file and only the same file in the folder), the error reappears.

My suspicion is that the issue may be related to how mypy and django-stubs are loading and interpreting the files.

## System information

- OS:
- `python` version: 3.9.10
- `django` version: 3.2.19
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.2

**Comment by intgr** [comment]
> My suspicion is that the issue may be related to how mypy and django-stubs are loading and interpreting the files.

The django-stubs mypy plugin imports Django and uses Django to introspect models. If there are issues with models discovery, then I suspect you're using Django models incorrectly.

Did you follow the Django docmentation about '[Organizing models in a package](https://docs.djangoproject.com/en/4.2/topics/db/models/#organizing-models-in-a-package)'?

It says that, if you want to move your models out of `models.py`, then `models.py` or `models/__init__.py` file needs to import those classes. Otherwise Django isn't guaranteed to discover them. But they _may_ get discovered by other incidential imports.

> that the error appears inconsistently across various environments.

That's the symptom I would expect if your models aren't correctly imported. Some environments have imports that cause the model files to be imported, others don't.

**Comment by MoranAbadieGatewatcher** [comment]
Hello, and thank you for the response.

I'd like to provide some additional context. The code that I'm scanning has been operating perfectly in production for years, and all tests are passing without issue. Indeed, my views are importing my models (indirectly). So the models are well readed by django.

The main problem appears only when scanning specific files with mypy, outside of the tox environment. Given that the code is running fine in other contexts, I believe that the issue may not be directly related to Django itself. Instead, it seems to be associated with the interaction between the mypy Django plugins and Django.

I have made some debugging and It seems that  the method self.django_context.get_model_class_by_fullname(self.model_classdef.fullname) within ModelClassInitializer.run is returning None. 

A specific question I have in this context is: Is it possible to customize DjangoContext.model_modules? If so, I'd appreciate any guidance on how to proceed with this customization. This might be the key to resolving the bug I'm encountering.

Thank you for your continued assistance.

**Comment by MoranAbadieGatewatcher** [comment]
Ok, you were right. If I include the imports in the __init__.py, everything works fine.

Sorry for the inconvenience,
