### ISSUE TITLE
False positive `"BaseManager[User]" has no attribute "create_user"` on default `User` `Model`

### ISSUE THREAD

**Issue by johnthagen** [typeddjango/django-stubs#1654]
# Bug report

## What's wrong

The following code:

```py
from django.contrib.auth.models import User

user = User.objects.create_user(username="user")
```

Generates an type checking error:

```
main.py:3: error: "BaseManager[User]" has no attribute "create_user"  [attr-defined]
```

This works at runtime, however.

The Django `User` derives from `AbstractUser`, which sets:

```py
objects = UserManager()
```

And `UserManager` defines:

```py
def create_user(self, username, email=None, password=None, **extra_fields):
    ...
```

## How is that should be

Expect no type error.

## System information

- OS: macOS
- `python` version: 3.10.11
- `django` version: 4.2.4
- `mypy` version: 1.5.0
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.2

This error did not appear in Mypy 1.4.1, but started appearing in 1.5.0.

**Comment by intgr** [comment]
This is a symptom of issue #1648, closing as duplicate. Unfortunately fixing it is not straightforward.

As a work-around you can downgrade mypy.
