### ISSUE TITLE
SQLCompiler.setup_query - incorrect signature

### ISSUE THREAD

**Issue by senseysensor** [typeddjango/django-stubs#1688]
# Incorrect method signature in stubs

## What's wrong
Incorrect signature of `SQLCompiler.setup_query()` for Django 4.2.5. Signature is specified as following: `def setup_query(self) -> None: ...`

## How is that should be
Actual signature is following:
`def setup_query(self, with_col_aliases=False):`

## System information

- OS: os x 13.5.1
- `python` version: 3.11.4
- `django` version: 4.2.5
- `mypy` version: 1.5.1
- `django-stubs` version: 4.2.4
- `django-stubs-ext` version: 4.2.2

**Comment by sobolevn** [comment]
PR is welcome

**Comment by ashm-tech** [comment]
#1689

**Comment by nebiyuelias1** [comment]
I guess this issue should be closed because I see pr has been merged.

**Comment by flaeppe** [comment]
Closed via #1689
