### ISSUE TITLE
models.Model.DoesNotExist and models.Model.MultipleObjectsReturned incorrectly considered undefined

### ISSUE THREAD

**Issue by sjdemartini** [typeddjango/django-stubs#1697]
# Bug report

## What's wrong

In writing generic code that needs to handle potentially different models, it's useful to be able to catch general exceptions with:

```python
try:
    result = queryset.get()
except models.Model.DoesNotExist:
    ...
except models.Model.MultipleObjectsReturned:
    ...
```

However, as of django-stubs 4.2.4 (apparently via https://github.com/typeddjango/django-stubs/pull/1663), django-stubs now claims that these generic base exception classes are not defined:

- `error: "type[Model]" has no attribute "DoesNotExist"  [attr-defined]`
 - `error: "type[Model]" has no attribute "MultipleObjectsReturned"  [attr-defined]`

## How is that should be

`models.Model.DoesNotExist` and `models.Model.MultipleObjectsReturned` are both real/defined exception classes that can be used and are needed/useful in generic code where the specific model class is not known.

Those attributes were apparently marked as "abstract" per comment here https://github.com/typeddjango/django-stubs/issues/1653#issuecomment-1697156925 and are only available via django-stubs for non-abstract models, which is not technically correct and limits real-world usage of these base exception classes.

## System information

- OS: MacOS 13.5
- `python` version: 3.10
- `django` version: 3.2.21
- `mypy` version: 1.5.0
- `django-stubs` version: 4.2.4
- `django-stubs-ext` version: 4.2.2

**Comment by flaeppe** [comment]
Attributes `models.Model.DoesNotExist` and `models.Model.MultipleObjectsReturned` do not exist.

The metaclass `ModelBase` has a guard that exits early, found [here](https://github.com/django/django/blob/e41f9f94505f690525f16af8bd10e62e22bc0207/django/db/models/base.py#L98-L102) for the type `models.Model`. Whereas you can see these attributes being added by the metaclass later on for concrete models [here](https://github.com/django/django/blob/e41f9f94505f690525f16af8bd10e62e22bc0207/django/db/models/base.py#L145-L172).

If you try to inspect those two attributes at runtime, you'll notice they don't exist

```python
from django.db import models
models.Model.DoesNotExist  # AttributeError: type object 'Model' has no attribute 'DoesNotExist'
models.Model.MultipleObjectsReturned  # AttributeError: type object 'Model' has no attribute 'MultipleObjectsReturned'
```

However, what you should instead use as generic exceptions to catch are the base exception classes `django.core.exceptions.ObjectDoesNotExist` and `django.core.exceptions.MultipleObjectsReturned`.

**Comment by sjdemartini** [comment]
Ah indeed, my bad. Thanks for the quick response and clarification. I guess the code in our project that referenced those exception classes was never executed in practice so I assumed incorrectly that they did indeed exist (with VSCode showing them as existing thanks to the stubs, despite them being "abstract"). 👍
