### ISSUE TITLE
related_name not found when models are from different apps

### ISSUE THREAD

**Issue by bshelkhonov** [typeddjango/django-stubs#1729]
# Bug report

I have the following project
```
src/apps/
|---- users
│      |---- __init__.py
|      |---- models.py
|---- another_app
│      |---- __init__.py
│      |---- models.py
```
In app 'users' i have User model
```python
class User(AbstractBaseUser, PermissionsMixin):
    objects = MyUserManager()
   # and so on
```

In app 'another_app' i have model:
```python
from users.models import User

class MyModel(Model):
    user = ForeignKey(User, related_name="my_model")
```

## What's wrong

When I want to get `user.my_model.id`, I receive an error:
`Item "AnonymousUser" of "User | AnonymousUser" has no attribute "my_model"`

## System information

- OS: MacOs 13.5.2
- `python` version: 3.11.5
- `django` version: 4.2.4
- `mypy` version: 1.5.1
- `django-stubs` version: 4.2.4
- `django-stubs-ext` version: 4.2.2

**Comment by flaeppe** [comment]
This looks a bit off for 2 reasons;

1. `user.my_model` the `related_name=` _many_ side attribute of a foreign key relationship. Which means that `user.my_model` is a manager. I'm not sure if your manager has an attribute `.id` but then it's definitely custom.
2. It very much looks like your `user` variable comes from `request.user`, and that is indeed typed as `<AUTH_USER> | AnonymousUser`. There's type narrowing bound to `is_authenticated` that could help you out for that case by doing e.g. `assert user.is_authenticated`

I'm going to close this off for now, let me know if I got something wrong and should reopen.
