### ISSUE TITLE
Next release planning (4.2.5)

### ISSUE THREAD

**Issue by flaeppe** [typeddjango/django-stubs#1740]
__TODO:__
- [x] #1719 
- [x] Add plugin support for `users = ManyToManyField(settings.AUTH_USER_MODEL)` #1746 

#1719 introduces plugin support for `ManyToManyField` but is lacking support for passing `AUTH_USER_MODEL` as `to=` arg e.g.:

```python
users = ManyToManyField(settings.AUTH_USER_MODEL)
```

Which we suspect is a normal use case and should support in any next release.

---

Please comment on this issue if there's anything else you know should, or want to be included.

**Comment by flaeppe** [comment]
And for anyone feeling adventurous, please try out `HEAD` on your project(s) and report back here if you run in to anything you think is a new issue. Perhaps we can then resolve it before pushing out a release.

**Comment by intgr** [comment]
Now that mypy 1.6.0 is out, we should consider making a release with the `compatible-mypy` bump. I can do the release.

I'd consider this a blocker, since it's a regression and we already have a fix PR:

* https://github.com/typeddjango/django-stubs/pull/1745

**Comment by intgr** [comment]
I'm releasing djangorestframework-stubs too, any takers to review this for the release:
* https://github.com/typeddjango/djangorestframework-stubs/pull/482

**Comment by flaeppe** [comment]
It'd be nice if we could also include #1767 in the next release

**Comment by intgr** [comment]
I want to move forward with:

* https://github.com/typeddjango/django-stubs/issues/1628

Making no changes quite yet, but I propose mentioning in 4.2.5 release notes that the next next version (4.2.6) will remove hard mypy dependency. Something like:

<details>

<summary>(outdated text)</summary>

> django-stubs is taking steps to improve experience with other type checkers besides mypy. Next version (4.2.6) will remove explicit mypy dependency. If you are currently using mypy, please add an explicit dev dependency on `mypy` to your project, or depend on django-stubs with the `compatble-mypy` extra, e.g. `django-stubs[compatible-mypy]`.
> **Note:** this is not a guarantee that other type checkers will be fully supported, pull requests for improvements are welcome. See [#1628](https://github.com/typeddjango/django-stubs/issues/1628) for details.

</details>

If you have comments on this, please discuss in #1628.

**Comment by intgr** [comment]
Should I cut the release or wait for the `cached_property` work to be completed?

* #1771
* #1761
* #1768
* #1769

**Comment by flaeppe** [comment]
We could always push another release if we want to. If you feel that one is due

**Comment by sobolevn** [comment]
I think `property` stuff can wait, really.

**Comment by intgr** [comment]
It's out!

* Release notes: https://github.com/typeddjango/django-stubs/releases/tag/4.2.5
* PyPI: https://pypi.org/project/django-stubs-ext/#history
* PyPI: https://pypi.org/project/django-stubs/#history

**Comment by intgr** [comment]
And also `djangorestframework-stubs` 3.14.4

* Release notes: https://github.com/typeddjango/djangorestframework-stubs/releases/tag/3.14.4
* PyPI: https://pypi.org/project/djangorestframework-stubs/3.14.4/#history

**Comment by intgr** [comment]
I introduced some issues in #1724 that will be fixed by #1778.

I will wait a few days to see if other bug reports come in and make a follow-up release soon. Opened release planning issue: #1780
