### ISSUE TITLE
django Settings.py values are not working when use `django_stubs_ext.monkeypatch`

### ISSUE THREAD

**Issue by TGoddessana** [typeddjango/django-stubs#1750]
# Bug report

## What's wrong

When using django_stubs_ext.monkeypatch(), settings from some third-party packages do not seem to be applied correctly.

I have three separate configuration files. They are `default.py, production.py, and development.py`.

In `default.py`, I store common settings, and in the other two, I import and use them, like `from .default import *` on the very first line.

```
settings/
    __init__.py
    default.py
    production.py 
    development.py
    
```

lets see. this is my `REST_FRAMEWORK` setting. 

```python
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dj_rest_auth.jwt_auth.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),

    # see this line!
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",


    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
}
```

In the files set as they are, when `DEFAULT_SCHEMA_CLASS` is imported, it should clearly be `drf_spectacular.openapi.AutoSchema`.

BUT the real result is:

```
In [1]: from rest_framework.settings import api_settings

In [2]: api_settings.DEFAULT_SCHEMA_CLASS
Out[2]: rest_framework.schemas.openapi.AutoSchema
```

this is confusing.

However, if we remove the monkeypatch function, it works as expected.

```python
# lets remove all.

# import django_stubs_ext
# from rest_framework.fields import Field
# from rest_framework.generics import GenericAPIView
# 
# django_stubs_ext.monkeypatch(
#     extra_classes=(
#         Field,
#         GenericAPIView,
#     )
# )
```

```
In [1]: from rest_framework.settings import api_settings

In [2]: api_settings.DEFAULT_SCHEMA_CLASS
Out[2]: drf_spectacular.openapi.AutoSchema
```

..works fine as expected.

## How is that should be

settings should work fine, after using `monkeypatch` method.

## System information

- OS:rocky linux
- `python` version: 3.11.5
- `django` version: 4.2.3
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.2

**Comment by to-sta** [comment]
I am having the same issue.

**Comment by to-sta** [comment]
Found a workaround for this problem. Since the api_settings are overriden by monkeypatch, if you reload the settings after you declared the REST_FRAMEWORK issue is resolved.

```python
rest_framework.settings import api_settings

...

api_settings.reload()
```

**Comment by TGoddessana** [comment]
> Found a workaround for this problem. Since the api_settings are overriden by monkeypatch, if you reload the settings after you declared the REST_FRAMEWORK issue is resolved.
> 
> ```python
> rest_framework.settings import api_settings
> 
> ...
> 
> api_settings.reload()
> ```

hello. Thank you for sharing your experience in resolving the error. I think my code will finally be " comfortable" to look at. XD
