### ISSUE TITLE
"cannot import name 'parse_bool'" after updating somes packages

### ISSUE THREAD

**Issue by batiste** [typeddjango/django-stubs#1784]
# Bug report

I use this version of mypy

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1

## What's wrong

mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

setup.cfg:34: error: Error importing plugin "mypy_django_plugin.main": cannot import name 'parse_bool' from 'mypy.semanal_shared' (/home/runner/.cache/pre-commit/repo712jqpu7/py_env-python3/lib/python3.11/site-packages/mypy/semanal_shared.cpython-311-x86_64-linux-gnu.so)  [misc]
Found 1 error in 1 file (errors prevented further checking)

## System information

- OS:
- `python` version: 3.11
- `django` version: 4.2.5
- `mypy` version: 1.6.1
- `django-stubs` version: 4.2.4
- `django-stubs-ext` version: 3.2.3

**Comment by intgr** [comment]
Probably related to https://github.com/typeddjango/django-stubs/pull/1703. @flaeppe any ideas?

**Comment by flaeppe** [comment]
Not having any ideas really, I'm still seeing a `mypy.semanal_shared.parse_bool` for `v1.6.1`.

Ref: https://github.com/python/mypy/blob/v1.6.1/mypy/semanal_shared.py#L469-L475

**Comment by intgr** [comment]
Might be some quirk related to the way mypy is compiled with Mypyc

> name 'parse_bool' from 'mypy.semanal_shared' (/home/runner/.cache/pre-commit/repo712jqpu7/py_env-python3/lib/python3.11/site-packages/mypy/**semanal_shared.cpython-311-x86_64-linux-gnu.so**)

If we don't understand this, may make sense to report a mypyc issue: https://github.com/mypyc/mypyc/issues

**Comment by flaeppe** [comment]
Yeah, that could probably be a reason. Would probably be worth to take it for a spin upstream, see what they say.

**Comment by intgr** [comment]
Created upstream issue:

* https://github.com/mypyc/mypyc/issues/1026

**Comment by batiste** [comment]
I am trying to resolve it on my side playing with versions.

But thanks for the quick reaction!

**Comment by intgr** [comment]
If there's no resolution in a few days, I'd propose reverting #1703 for the upcoming 4.2.6 release #1780

**Comment by intgr** [comment]
I've opened PR #1792 to revert the suspected change.

@batiste does this issue still occur or have you found a work-around?

**Comment by batiste** [comment]
My sincerest apologies, I have 2 different pre-commit configurations (one local and one for the CI). And I got confused about this setup. The one that was problematic was this one

`
   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v1.0.1
     hooks:
       - id: mypy
         exclude: tests|migrations|commands|settings
         additional_dependencies:
          - django-stubs
`

Once I updated mypy to 1.6.1 the error went away.

**Comment by intgr** [comment]
> repo: https://github.com/pre-commit/mirrors-mypy
> rev: v1.0.1

Doh! Yep, the old mypy version explains it.

Unfortunately the reversion #1792 already got merged. 😅

But we should consider special logic in the plugin to detect old mypy versions and issue a warning, to make detecting such issues easier.
