### ISSUE TITLE
As_manager: Self not taken into account

### ISSUE THREAD

**Issue by moranabadie** [typeddjango/django-stubs#1788]
# Bug report
```
from django.db import models
from typing_extensions import Self
class MyQuerySet(BaseQuerySet):
       def example_simple(self) -> Self: ...

class MyModel(models.Model):
     objects = MyQuerySet.as_manager()
reveal_type(MyModel.objects.example_simple())  # -> Revealed type is "<nothing>" 
````

## What's wrong

The issue lies in the type revelation within the custom QuerySet method that is supposed to return Self. Currently, it reveals the type as `<nothing>`, which indicates that the Self type isn't properly recognized or handled.

## How is that should be

The correct and expected behavior should reveal the type accurately, as per the following expectation:
```
reveal_type(MyModel.objects.example_simple())  # -> Revealed type is "myapp.models.ManagerFromMyQuerySet[myapp.models.MyModel]"
```

## System information

- OS:
- `python` 3.12
- `django` 3.2.12
- `mypy` 1.6.1
- `django-stubs` 4.2.5
- `django-stubs-ext` 4.2.5

**Comment by sobolevn** [comment]
PR is welcome.
