### ISSUE TITLE
Proposal: Add `django-stubs-ext` as an optional dependency of `django-stubs`

### ISSUE THREAD

**Issue by richardebeling** [typeddjango/django-stubs#1790]
My `requirements.txt` file currently specifies `django-stubs` and `django-stubs-ext` separately, requiring duplication of the required version:
```
django-stubs==4.2.5
django-stubs-ext==4.2.5
```

I would llike to express this as one dependency without duplicating the version by using an [optional dependency](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies):
```
django-stubs[ext]==4.2.5
```
I don't care about the actual identifier (`ext`), I could also see it being `django-stubs-ext` or any other name.

Note: django-stubs already specifies the [`compatible-mypy` optional dependency](https://github.com/typeddjango/django-stubs/blob/master/setup.py#L35).

**Comment by sobolevn** [comment]
Sure, why not?
PR is welcome :)

**Comment by intgr** [comment]
I'm not quite sure what you're proposing.

`django-stubs` already depends on `django-stubs-ext`

https://github.com/typeddjango/django-stubs/blob/0ce571e19e378cd4ca830f29ec28985cfca59b7e/setup.py#L23-L25

**Comment by richardebeling** [comment]
Ah, I see. I was under the assumption that `django-stubs-ext` is an optional additional package. Sorry for the confusion.
