### ISSUE TITLE
`Model.<related_name>` has no attribute "through"

### ISSUE THREAD

**Issue by michjnich** [typeddjango/django-stubs#1800]
# Bug report

## What's wrong
I confess, I am quite new to typing, so if this is a mypy issue and not a django-stubs issue, I apologise. I think I am reporting this in the right place though. 

I have a ManyToManyField on a model:
```
class Post(models.Model):
   ...
    identifiers = models.ManyToManyField(Identifier, verbose_name=_("Identifiers"), related_name="posts")
```
And a `TabularInline` in admin for the `Identifier` model: 
```
class PostInline(admin.TabularInline):
    model = Identifier.posts.through
    ...
```
But mypy does not like this :
```
error: "RelatedManager[Post]" has no attribute "through"  [attr-defined]
```
## How is that should be

No error should be raised because `Identifier.posts.through` is valid

## System information

- OS: WSL2 under windows 11
`Linux LMAVSURFACE4 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- `python` version: 3.11
- `django` version: 4.2.6
- `mypy` version: 1.6.1
- `mypy-extensions` version:  1.0.0
- `django-stubs` version: 4.2.5
- `django-stubs-ext` version: 4.2.5

**Comment by intgr** [comment]
Hi! Did you configure mypy to use the `mypy_django_plugin.main` plugin? And did you configure a functional `django_settings_module`?

**Comment by michjnich** [comment]
I have this in `pyproject.toml`

```
[tool.mypy]
python_version = "3.11"
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings"
```

**Comment by intgr** [comment]
And does the `INSTALLED_APPS` in `config.settings` enable the app where your `Post` model exists?

**Comment by michjnich** [comment]
It does, yes. (otherwise pretty much nothing would work :) )

**Comment by flaeppe** [comment]
I can reproduce this in `test_many_to_many`

https://github.com/typeddjango/django-stubs/blob/25e23fa24c7691f8ae53fe5a81f0b3c6f2d33693/tests/typecheck/fields/test_related.yml#L1070-L1095

```diff
 -   case: test_many_to_many
    main: |
        from myapp.models import MyModel, Other
        ...

        reveal_type(MyModel.other_again.through)
+       reveal_type(Other.autos.through)
```

**Comment by flaeppe** [comment]
I think we need to improve with descriptor types here. e.g.

```python
reveal_type(Other.autos)  # Revealed type is "django.db.models.manager.RelatedManager[myapp.models.MyModel]"
print(type(Other.autos))  # <class 'django.db.models.fields.related_descriptors.ManyToManyDescriptor'>
```

**Comment by superlevure** [comment]
I am still getting this error with `4.2.7`

**Comment by flaeppe** [comment]
@superlevure feel free to provide a breaking case and/or open a new issue
