### ISSUE TITLE
`_StrPromise` on a `TypedDict`

### ISSUE THREAD

**Issue by michjnich** [typeddjango/django-stubs#1804]
# Bug report

## What's wrong
If I define a `TypedDict`

```
class CustomItem(TypedDict):
    name: str
    value: str
```
And a dict that uses this: 
```
from django.utils.translation import gettext_lazy as _

MYDICT: dict[str, CustomItem] = {
    "test": {"name": _("testing"), "value": "this"}
}
```

I get the resulting message:
```
Incompatible types (expression has type "_StrPromise", TypedDict item "name" has type "str")
```
I am currently using the `django_stubs_ext.StrOrPromise` instead here, but the README asks us to report if we come across a `_StrPromise` issue while using Django. 

## How is that should be
I should be able to type a `gettext_lazy` value as `str`

## System information
- OS: WSL2 on Win11
- `python` version: 3.11.6
- `django` version: 4.2.6
- `mypy` version: 1.6.1
- `django-stubs` version: 4.2.6
- `django-stubs-ext` version: 4.2.5

**Comment by flaeppe** [comment]
> I should be able to type a `gettext_lazy` value as `str`

This has been brought up previously, or a slightly different version of it. Which you'll probably find if you start off somewhere around here: https://github.com/typeddjango/django-stubs/pull/689#issuecomment-1327929656. Which is some discussion(s) and reasoning from when `_StrPromise` was introduced.

The short version is something like: while the promise returned by `gettext_lazy` in many cases behaves like a `str`, it doesn't always. And we want to be very careful spoofing the type checker.

**Comment by michjnich** [comment]
Ah, OK. Sorry if I've re-raised a previous discussion - I did do a search first but obviously missed those specific comments. 

So for this specific case the correct solution (and will remain the correct solution) is to use `StrOrPromise` from `django-stubs-ext`? Is that right? No problem if that's the case - I'd just got the impression from the README comment that it was kind of a workaround until these things could be standardises in core. 

And if you close this one, at least there's an "obvious" issue that will pop up in a search for it in the event somebody else is looking for the same thing :)

**Comment by intgr** [comment]
Yep, `str` and `StrPromise` are distinct types. If you need to typehint it in your own code, use the `StrOrPromise` type exported by `django-stubs-ext`:

```python
from django_stubs_ext import StrOrPromise

class CustomItem(TypedDict):
    name: StrOrPromise
    value: str
```

**Comment by flaeppe** [comment]
No worries. As you said, now we hopefully have something that is more searchable. I'm gonna close this off for now.
