### ISSUE TITLE
False-positive trigger when converting a queryset to a dictionary

### ISSUE THREAD

**Issue by Oleksii-Kutsenko** [typeddjango/django-stubs#1817]
# Bug report

## What's wrong
I tried to convert a queryset into a dictionary, and I encountered a type error:
```
dict(Model.objects.values_list("name", "value"))
```
This triggers mypy with the following error:
```
error: Argument 1 to "dict" has incompatible type "_QuerySet[Model, tuple[int, float | None]]"; expected "Iterable[tuple[int, float]]"  [arg-type]
```
## How is that should be
It should not trigger mypy.

## System information

- OS: Linux Mint 21.2
- `python` version: 3.11.0
- `django` version: 4.2.4
- `mypy` version: 1.6.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.5

**Comment by flaeppe** [comment]
I can't reproduce this with querysets and inferred types of a dict, which is what exampled here:

```python
dict(Model.objects.values_list("name", "value"))
```

But looking a bit closer, it seems like the inferred type for your dictionary is `dict[int, float]`. While your column `value` is nullable, thus producing `float | None`.

Could that be what's wrong here?

**Comment by Oleksii-Kutsenko** [comment]
@flaeppe Thank you, sorry it was not so clear what happens here
