### ISSUE TITLE
TemplateCommand subclasses `handle` method typing is incorrect

### ISSUE THREAD

**Issue by PedroPerpetua** [typeddjango/django-stubs#1820]
# Bug report

## What's wrong
The `TemplateCommand` class stub (`django-stubs/core/management/templates.pyi`) defines the `handle` command as follows:
```py
def handle(self, app_or_project: str, name: str, target: str | None = ..., **options: Any) -> None: ...
```

We can see that in subclasses (startapp and startproject), Django actually does not follow the super's definition, instead manually parsing kwargs to pass into the super's method:
```py
# django.core.management.commands.startapp
class Command(TemplateCommand):
    help = (
        "Creates a Django app directory structure for the given app name in "
        "the current directory or optionally in the given directory."
    )
    missing_args_message = "You must provide an application name."

    def handle(self, **options):
        app_name = options.pop("name")
        target = options.pop("directory")
        super().handle("app", app_name, target, **options)
```

## How is that should be
This is an issue where Django itself is kinda violating the principles of inheritance by havind a different definition in the child class; however, I believe the stubs should still reflect this behaviour, and should define the class methods for the respective commands in the way they are actually used:
```py
def handle(self, **options: Any) -> Optional[str]: ...
```

## System information

- OS:
- `python` version: 3.11
- `django` version: 4.2.7
- `mypy` version: 1.6.1
- `django-stubs` version: 4.2.6
- `django-stubs-ext` version: 4.2.5

**Comment by intgr** [comment]
What problems does this cause, or what will improve if the args are removed?

~~I think this should be fixed by just making `app_or_project` and `target` keyword-only arguments (by adding a `*,` to signature), not removing the arguments. I don't think there are any downsides?~~

**Comment by PedroPerpetua** [comment]
> What problems does this cause, or what will improve if the args are removed?

My current use case where I'm faced with this problem is that I'm overriding the `startapp` command to use, by default, a `TEMPLATE_PATH` that I provide:
```py
# My custom startapp command
from pathlib import Path
from typing import Any, Optional
from django.conf import settings
from django.core.management.commands.startapp import Command as StartAppCommand


class Command(StartAppCommand):
    """Customize the StartAppCommand to use our custom app template by default."""

    TEMPLATE_PATH: Path = settings.BASE_DIR / "core" / "app_template"

    # https://github.com/typeddjango/django-stubs/issues/1820
    def handle(self, *args: Any, **options: Any) -> Optional[str]:  # type: ignore
        """Override the `handle` method to add the option "template" with our template if None were passed."""
        if options.get("template", None) is None:
            options["template"] = str(self.TEMPLATE_PATH)
        return super().handle(*args, **options)
```

**Comment by UnknownPlatypus** [comment]
> I think this should be fixed by just making app_or_project and target keyword-only arguments (by adding a *, to signature), not removing the arguments. I don't think there are any downsides?

Django passe these arguments as [non keyword args](https://github.com/django/django/blob/stable/4.2.x/django/core/management/commands/startapp.py#L11-L14) so that would be a bit weird to do that maybe ? 

I feel like having the signature proposed above by @PedroPerpetua  is more accurate and reflect more the actual django code ?

**Comment by intgr** [comment]
> Django passe these arguments as [non keyword args](https://github.com/django/django/blob/stable/4.2.x/django/core/management/commands/startapp.py#L11-L14) so that would be a bit weird to do that maybe ?

Yes my bad, I wasn't concentrating and I got multiple things mixed up there. 😅

**Comment by UnknownPlatypus** [comment]
Will submit a PR for this tonight, I was working on updating these a few days ago
