### ISSUE TITLE
No error detected for non-existent attribute in ForeignKey relation

### ISSUE THREAD

**Issue by jereze** [typeddjango/django-stubs#1844]
Hello django-stubs community,

I've encountered a situation with django-stubs and mypy where an attribute error is not being detected, and I'm seeking clarification on whether this behavior is expected or a wrong configuration on my side.

In my Django models, I have two classes, Article and Comment. The Comment class has a ForeignKey relationship with Article. When accessing a non-existent attribute on an Article instance through a Comment instance (e.g., c.article.xyz), mypy does not raise an attribute error.

Code Snippet:

```python
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

c = Comment._default_manager.get(id="1")
a = c.article.xyz  # No error detected by mypy here
```

If I explicitly annotate the article field in the Comment model with the Article type, mypy correctly identifies the attribute error.

```python
class Comment(models.Model):
    article: Article = models.ForeignKey("Article", on_delete=models.CASCADE)
    # other fields...

c = Comment._default_manager.get(id="1")
a = c.article.xyz  # Mypy error: "Article" has no attribute "xyz"
```

Any insights or clarifications on this matter would be greatly appreciated.

Thank you for your time and assistance.

Cheers,
Jeremy

- OS:
- `python` version: 3.11.6
- `django` version: 4.2.7
- `mypy` version: 1.7.0
- `django-stubs` version: 4.2.6
- `django-stubs-ext` version: 4.2.5

**Comment by MrkGrgsn** [comment]
I could replicate your problem when the app the models were defined in was not in `INSTALLED_APPS`. I guess the mypy plugin does not update the model types unless the app is installed.

**Comment by jereze** [comment]
Thank you, Mark, for your efforts in attempting to replicate the issue.

Indeed the application wasn't included in INSTALLED_APPS. This was an oversight while trying to create a minimal reproducible example.

Additionally, I needed to encapsulate my test within a function. Without this, the mypy command-line interface produced an error (Error constructing plugin instance of NewSemanalDjangoPlugin):

```
def test() -> str:
    c = Comment._default_manager.get(id=1)
    a = c.article.xyz  # does not exist, and now raise an error 
    return a
```

I'm going to close this issue. Thanks again.

**Comment by UnknownPlatypus** [comment]
@jereze I think django-stubs only support the "<app_name>.<model_name>" syntax for FK definition. Might be the reason of your problem. 

```diff
-    article = models.ForeignKey("Article", on_delete=models.CASCADE)
+    article = models.ForeignKey("<app_name>.Article", on_delete=models.CASCADE)
```

**Comment by jereze** [comment]
Thank you, @UnknownPlatypus, for the suggestion. I tried it both with and without including it in INSTALLED_APPS, but it didn't change the outcome of my test case.
