### ISSUE TITLE
TypedModelMeta only allows `list[str]` for `ordering`

### ISSUE THREAD

**Issue by HansAarneLiblik** [typeddjango/django-stubs#1846]
Hi!

[TypedModelMeta.ordering](https://github.com/typeddjango/django-stubs/blob/master/ext/django_stubs_ext/db/models/__init__.py) currently only allows a Sequence of `str`, but accoding to the [docs,](https://docs.djangoproject.com/en/4.2/ref/models/options/#ordering) expressions like `OrderBy` should also be allowed

![image](https://github.com/typeddjango/django-stubs/assets/5418540/59795261-de47-40fd-8fa3-057c59481064)

Example of valid input:
```py
class Entry(models.Model):
  type = models.CharField(max_length=100)
  item = models.CharField(max_length=100, null=True)

  class Meta(TypedModelMeta):
    ordering = ["type", F("item").asc(nulls_first=True)]
```

**Comment by intgr** [comment]
Yes. Are you interested in submitting a PR? 😆
