### ISSUE TITLE
Open to cutting a 4.2.8 release?

### ISSUE THREAD

**Issue by jamesbraza** [typeddjango/django-stubs#1931]
Are you open to cutting a new release (for `mypy==1.8`)?

`django-stubs[compatible-mypy]==4.2.7` is pinned to `mypy==1.7`: https://github.com/typeddjango/django-stubs/blob/4.2.7/setup.py#L35, but the current `master` is not

**Comment by sobolevn** [comment]
It will be `5.0.0`, I guess 🤔

**Comment by jamesbraza** [comment]
Oh if it was a bugfix version bump, I am okay with requesting it 🤓 , but I don't want to rush a major version bump. If it's a major version bump, that would be up to your own choice in timing

**Comment by meshy** [comment]
Is there an appetite for back-fixing other bug fixes? It'd be great to have https://github.com/typeddjango/django-stubs/pull/1913 in an earlier version too!

**Comment by aleksanb** [comment]
looking forward to a release here as well.

**Comment by intgr** [comment]
> but I don't want to rush a major version bump. If it's a major version bump, that would be up to your own choice in timing

Yep it would be 5.0.0. But the major version bump is just to stay in sync with Django version numbers. It shouldn't be significantly more complex than a typical release for us.

It's more that I've been absent from this project lately and nobody else has stepped up to handle the release. I wrote more at https://github.com/typeddjango/django-stubs/issues/1493#issuecomment-1943787982

**Comment by sobolevn** [comment]
I think that `5.0.0` should also drop 3.7 support, since it is EOL.

**Comment by intgr** [comment]
We already dropped Python 3.7 in version 4.2.1 😄 https://github.com/typeddjango/django-stubs?tab=readme-ov-file#version-compatibility

**Comment by sobolevn** [comment]
Sorry, I got confused.

3.8 is not supported by `pre-commit` anymore: https://github.com/typeddjango/django-stubs/actions/runs/7953898472/job/21710530911

But, we cannot drop it yet, since it is still a supported Python version.

**Comment by delfick** [comment]
that could be fixed by making it install pre-commit with a different version if the python version is less than a certain number https://pip.pypa.io/en/stable/reference/requirement-specifiers/

**Comment by sobolevn** [comment]
@delfick PR is welcome :)

**Comment by delfick** [comment]
@sobolevn https://github.com/typeddjango/django-stubs/pull/1961 I believe it needs approval before we can see if CI works against that change

**Comment by jamesbraza** [comment]
Since versions in `django-stubs` match Django, it seems the next release here is a major version bump to version 5. I am now realizing that the small version bump I requested in the OP will go against the Django version matching.

I can attain what I wanted by pinning requirements to the last commit https://github.com/typeddjango/django-stubs/tree/7564f79d8d1574dc642e80c215c9262d7fe15baf like so:

```txt
django-stubs-ext @ git+https://github.com/typeddjango/django-stubs.git@7564f79d8d1574dc642e80c215c9262d7fe15baf#subdirectory=ext  # Matching django-stubs
django-stubs[compatible-mypy] @ git+https://github.com/typeddjango/django-stubs.git@7564f79d8d1574dc642e80c215c9262d7fe15baf  # For mypy 1.8
```

As shared above, there is a `django-stubs` compatibility with Django 5 issue tracker at https://github.com/typeddjango/django-stubs/issues/1493, so closing this out in favor of that.

**Comment by intgr** [comment]
* Please see this for updates: #2020
