### ISSUE TITLE
Overrides of BaseCommand.handle() are problematic

### ISSUE THREAD

**Issue by antonagestam** [typeddjango/django-stubs#197]
[`django.core.management.base.BaseCommand.handle()`](https://github.com/django/django/blob/master/django/core/management/base.py) has the signature:

    def handle(self, *args, **options) -> NoReturn: ...

And has the stub:

    def handle(self, *args: Any, **options: Any) -> None: ...

But some if its subclasses has incompatible signatures for this method, like [`django.core.management.base.AppCommand.handle()`](https://github.com/django/django/blob/master/django/core/management/base.py#L499)

    def handle(self, *args: Any, **options: Any) -> Optional[str]: ...

And [`staticfiles.management.commands.collectstatic.Command.handle`](https://github.com/django/django/blob/master/django/contrib/staticfiles/management/commands/collectstatic.py#L147):

    def handle(self, **options) -> Optional[str]:

Subclassing collectstatic with an identical signature gives:

    error: Signature of "handle" incompatible with supertype "BaseCommand"  [override]

Changing to also accept `*args: Any` instead gives:

    error: Return type "str" of "handle" incompatible with return type "None" in supertype "BaseCommand"  [override]

... so that's all the information I have on the table. I think this situation is pretty weird as it seems to mostly lie in Django breaking Liskov Substitution Principle. However, I believe at least some of my problems would go away if `BaseCommand.handle()` was annotated with `-> Optional[str]`.

What do you think? Is it worth a bug report towards Django?

## System information

- OS: macos
- `python` version: 3.7.4
- `django` version: 2.2.6
- `mypy` version: mypy 0.730
- `django-stubs` version: -e git+git@github.com:typeddjango/django-stubs.git@b939bc96b7ff0645da19c2ff960ac9bd0a50bee7#egg=django_stubs

**Comment by sobolevn** [comment]
Seems like Django has to fix it indeed. Would you create a bug there, please?

**Comment by antonagestam** [comment]
Sure! I'll try and get to it as soon as I can. Would you be open to changing the annotation of `BaseCommand.handle()` to `(Any, Any) -> Optional[str]`?
