### ISSUE TITLE
Class attributes annotated as mutable types when mutability is not required

### ISSUE THREAD

**Issue by samueljsb** [typeddjango/django-stubs#1992]
# Bug report

## What's wrong

There are many attributes that are annotated here as mutable types (lists, dicts) that don't actually need to be mutable. It would be perfectly valid to use immutable types (tuples, `MappingProxyType` or frozendicts), but the type checker then complains because the annotation here appear to require mutability.

There are a lot of these, and I don't want to do a half-baked job of listing them exhaustively, so as an example, we can consider `TemplateView`'s `extra_context`:

```python
from types import MappingProxyType

from django.views import generic


class MyView(generic.TemplateView):
    extra_context = MappingProxyType({
        'foo': 1,
        'bar': 42,
    })
```

```console
t.py:7: error: Incompatible types in assignment (expression has type "MappingProxyType[str, int]", base class "ContextMixin" defined the type as "dict[str, Any] | None")  [assignment]
Found 1 error in 1 file (checked 1 source file)
```

## How is that should be

I think this case should be annotated as `Mapping[str, Any] | None`, because a mapping is required but not necessarily a mutable one.

## System information

This example was with the following, but I've experienced this problem with various combinations and versions.

- OS: macOS 14.3.1
- `python` version: v3.11.5
- `django` version: 5.0.3
- `mypy` version: 1.8.0 
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

**Comment by sobolevn** [comment]
PR is welcome.

Generally we annotate attributes with their concrete types. Because Django does not provide any promises about how they would be used.

So, if you have any speicific examples, we can decide on a per-case basis.

**Comment by sobolevn** [comment]
Please, open new issues for any other places you find this problem 👍
