### ISSUE TITLE
Inheriting from model_utils SoftDeletableModel causes issues

### ISSUE THREAD

**Issue by JannKleen** [typeddjango/django-stubs#2011]
# Bug report

## What's wrong

I'm using https://github.com/jazzband/django-model-utils/blob/master/model_utils/models.py#L133-L158 (I know this isn't a great implementation for soft deletion, but I needed something quick and simple) and have the following models set up:

```python
from model_utils.models import SoftDeletableModel


class BaseModel(SoftDeletableModel):
    class Meta:
        abstract = True

class MyModelA(BaseModel):
    sub_items = models.ManyToManyField(
        "self", related_name="parents", symmetrical=False, blank=True
    )

class MyModelB(BaseModel):
    model_a = models.ManyToManyField(MyModelA, related_name="model_b")
    deleted_model_a = models.ManyToManyField(MyModelA, related_name="model_b_deleted")
```

This works fine if I don't inherit from `SoftDeletableModel` but if I do I get:

```
error: Need type annotation for "sub_items"  [var-annotated]
error: Need type annotation for "model_a"  [var-annotated]
error: Need type annotation for "deleted_model_a"  [var-annotated]
```

## System information

- OS: Linux (`python:3.11.7-slim-bullseye`)
- `python` version: 3.11.7
- `django` version: `django==4.2.7`
- `mypy` version: `mypy==1.7.0`
- `django-stubs` version: `django-stubs[compatible-mypy]==4.2.7`
- `django-stubs-ext` version: `django-stubs-ext==4.2.7`

**Comment by JannKleen** [comment]
What works is manually annotating those fields with `field : models.ManyToManyField = ...`.

**Comment by flaeppe** [comment]
I'm not completely sure; but since `SoftDeletableModel` seem to lack type hints it might be that mypy can't resolve that class/type properly.

With the above said it looks like this is rather an issue (at least initially) for `django-model-utils` than for `django-stubs`.

I'm happy to reopen if it there's anything else that I might have missed and would need to be fixed.

**Comment by JannKleen** [comment]
@flaeppe Thanks for the reply! I get that this is more related to `django-model-utils`, but since you're probably more familiar with python (and Django) typing, could you maybe point me at what could cause the issue? It doesn't look like they're doing anything crazy, is it the Mixin that could be causing this?

**Comment by intgr** [comment]
I don't understand either, why this would happen. While `django-model-utils` is missing many specific type hints, it actually includes a `py.typed` marker. So mypy should be fully aware that `SoftDeletableModel` inherits from `models.Model`.

If you're looking for a quick work-around hack, this might help:

```python
from typing import TYPE_CHECKING

class BaseModel(models.Model if TYPE_CHECKING else SoftDeletableModel):
```
