### ISSUE TITLE
Allow setting `django_settings_module` from the `DJANGO_SETTINGS_MODULE` env variable

### ISSUE THREAD

**Issue by armanckeser** [typeddjango/django-stubs#2018]
Hi there!

Hope everyone is doing alright! I have a use-case where I deploy my Django application with different `INSTALLED_APPS` in two different deployments. The least invasive way I found to do this was having two separate settings files and switching between them based on whichever one I am deploying. Things like `pytest` allow the setting of `django_settings_module` from both the environment and the `pyproject.toml`. It seems like `django_stubs` wants the settings to be static which doesn't really make sense to me considering Django has deemed it as an env variable for that flexibility. 

Let me know if I am missing something, or if there is a workaround/fix that would be easier.

Thanks!

**Comment by sobolevn** [comment]
We can try this, PR is welcome.

**Comment by armanckeser** [comment]
@sobolevn Opened a PR
