### ISSUE TITLE
Signature of "has_add_permission" incompatible with supertype "BaseModelAdmin"

### ISSUE THREAD

**Issue by Sukochev** [typeddjango/django-stubs#203]
## What's wrong
Getting mypy error:
`project/contact/admin.py:25: error: Signature of "has_add_permission" incompatible with supertype "BaseModelAdmin"`

For example in registering a custom Django Admin such as
```
class ContactAdmin(admin.ModelAdmin):
    list_display = ("__str__",)

    def has_add_permission(self, request: HttpRequest) -> bool:
        return False

admin.site.register(Contact, ContactAdmin)
```
results in the error above for the method `has_add_permission`.

This is possibly due to the fact that https://github.com/typeddjango/django-stubs/blob/8402e7c53ee4d2fa2ea31a506b6a986b67e10c1a/django-stubs/contrib/admin/options.pyi#L89

has     `def has_add_permission(self, request: HttpRequest, obj: Optional[Model] = ...) -> bool: ...`

while https://github.com/django/django/blob/42b9a23267f14be39b9b00958e18d5746783208e/django/contrib/admin/options.py#L467

has   `def has_add_permission(self, request):`

i.e `obj` parameter shouldn't be in stub?

## How is that should be

I don't think this error should appear here. The case of `has_change_permission` for example, works as expected.

## System information

- OS:
- `python` version: 3.7.3
- `django` version: 2.2.5
- `mypy` version: 0.720
- `django-stubs` version: 1.1.0

**Comment by sobolevn** [comment]
Yes, looks like a bug in stubs. @Sukochev can you please send a PR with the fix?

**Comment by Sukochev** [comment]
@sobolevn Sure, will do.
