### ISSUE TITLE
uninstallable

### ISSUE THREAD

**Issue by developer992** [typeddjango/django-stubs#2032]
```
Because no versions of django-stubs match >4.2.7,<5.0.0
 and django-stubs (4.2.7) depends on mypy (>=1.7.0,<1.8.0), django-stubs (>=4.2.7,<5.0.0) requires mypy (>=1.7.0,<1.8.0).
```

**Comment by sobolevn** [comment]
Try these versions from here: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/poetry.lock

Look for `django-stub`, `mypy` and `django` versions.

It works for me quite well.
Please, reopen if that didn't work.
