### ISSUE TITLE
`TextChoices` api with human-readable name is not supported

### ISSUE THREAD

**Issue by voidus** [typeddjango/django-stubs#2033]
According to the [django docs](https://docs.djangoproject.com/en/5.0/ref/models/fields/), this should be allowed:

```
    class YearInSchool(models.TextChoices):
        FRESHMAN = "FR", _("Freshman")
        SOPHOMORE = "SO", _("Sophomore")
        JUNIOR = "JR", _("Junior")
        SENIOR = "SR", _("Senior")
        GRADUATE = "GR", _("Graduate")
```

but since the [constructor for Textchoices](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/enums.pyi#L63) is defined like this:

```
    def __new__(cls, value: str) -> Self: ...
```

This is rejected by pyright in some situations. (I can talk about my setup some more, but in my personal situation it's not easy to work around)

Or maybe the constructor is not involved in this at all? Pyright gives me this not-really-helpful error:

```
/path/to/models.py
  /path/to/models.py:40:19 - error: Expected 1 positional argument (reportCallIssue)
  /path/to/models.py:41:50 - error: Expected 1 positional argument (reportCallIssue)
2 errors, 0 warnings, 0 informations 
``

**Comment by hubert-springbok** [comment]
Hi, we're also experiencing this since 4.2.6. Here is a minimal example to reproduce the error:
```python
from django.db.models import TextChoices


class MyChoices(TextChoices):
    CHOICE = "CHOICE", "A choice"
```
django: 4.2.11
python: 3.10

Result: `/test_file.py:5:14 - error: Expected 1 positional argument (reportCallIssue)`

I've initially wrongly reported this to [pyright](https://github.com/microsoft/pyright/issues/7756).
