### ISSUE TITLE
Model files being skipped

### ISSUE THREAD

**Issue by agronick** [typeddjango/django-stubs#2036]
# Bug report

## What's wrong

I have two model files in my project that are not being annotated correctly. There appears to be some kind of bug that is causing them to be skipped. Every line in the model is being reported in mypy like

```
optimax/models.py:252: error: Need type annotation for "update_date"  [var-annotated]
optimax/models.py:253: error: Need type annotation for "created_at"  [var-annotated]
```

How can I debug where the models get patched and why they aren't being included?

## How is that should be

These models should be patched and there should be an error if they can't be patched for some reason.

## System information

- OS:
- `python` version: 3.11.8
- `django` version: 5.0.2
- `mypy` version: 1.9.0
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

**Comment by sobolevn** [comment]
Can you please provide a reproducer?
