### ISSUE TITLE
isinstance(obj, QuerySet) check in third-party libraries

### ISSUE THREAD

**Issue by beaverkiria** [typeddjango/django-stubs#2088]
Hey there!

The [readme](https://github.com/typeddjango/django-stubs?tab=readme-ov-file#how-do-i-check-if-something-is-an-instance-of-queryset-in-runtime) says that we should use `isinstance(obj, QuerySetAny)` to check whether object is a queryset in runtime.

However there are lots of places in django itself and third party libraries that do the same check and they obviously do that with vanilla `QuerySet` class.
I wonder if I might have any problems if I deploy `django_stubs_ext` to my production server.

I'm using django 4.2 if that matters

**Comment by sobolevn** [comment]
No, you won't have any problems: https://github.com/typeddjango/django-stubs/blob/6f7a19cf26257fb2da1c65c12a72807f9154dfe7/ext/django_stubs_ext/aliases.py#L14

It is safe to use :)
