### ISSUE TITLE
HttpResponsePermanentRedirect missing in django.shortcuts

### ISSUE THREAD

**Issue by SRChiP** [typeddjango/django-stubs#210]
# Bug report

## What's wrong

I get an issue:
`error: Module 'django.shortcuts' has no attribute 'HttpResponsePermanentRedirect'; maybe "HttpResponseRedirect"?`.

It seems that `HttpResponseRedirect` is defined in django.shortcuts, but not `HttpResponsePermanentRedirect`.

## How is that should be

No errors when running mypy

## System information

- OS: ArchLinux
- `python` version: 3.7.4
- `django` version: 2.2.5
- `mypy` version: 0.730
- `django-stubs` version: 1.2.0

**Comment by sobolevn** [comment]
@SRChiP would you like to submit a PR with the fix, please?
