### ISSUE TITLE
Configure PyPI for release automation

### ISSUE THREAD

**Issue by intgr** [typeddjango/django-stubs#2114]
PR #1950 introduced automation for making releases. But when I tried this out on Tuesday, it did not work: https://github.com/typeddjango/django-stubs/actions/runs/8892716988/job/24417384679

> Token request failed: the server refused the request for the following reasons:
>
> * `invalid-publisher`: valid token, but no corresponding publisher (All lookup strategies exhausted)

It requires some setup to be done on PyPI side. I believe only @sobolevn can do it. See below:

----

https://github.com/typeddjango/django-stubs/pull/2087#issuecomment-2084867311

> @intgr Was the trusted publisher set up on the PyPI side? Do you have access to see if it's configured?
> 
> It should just be to follow this if it's not: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
> 
> Should just be to fill in and post a form

https://github.com/typeddjango/django-stubs/pull/2087#issuecomment-2084870025

> Owner: typeddjango
> Repository name: django-stubs
> Workflow name: release.yml
> Environment name: release

**Comment by sobolevn** [comment]
Done!
<img width="438" alt="Снимок экрана 2024-05-02 в 18 09 01" src="https://github.com/typeddjango/django-stubs/assets/4660275/169e0ab6-3a74-44a1-b831-de6cce874948">

**Comment by sobolevn** [comment]
We can try `5.0.1` release, since we have lots of PRs with stub fixes.

**Comment by intgr** [comment]
@sobolevn Looks like you only configured the `django-stubs` package? We also need `django-stubs-ext`.

**Comment by flaeppe** [comment]
We don't have any release workflow for `django-stubs-ext` yet. I don't know what we should have as a trigger?

- Should we always release it, regardless if files under `ext/` were changed or not? Then it's simple to add it.
- Should we only release if files were changed? Then we need to diff files.

Main thing to think about is that if we want the ability to keep different release numbers between the packages we can't use the same GitHub releases.

**Comment by intgr** [comment]
Doh, sorry. I had a brief look at the diff before and saw it doing something with `ext`. But I was misled by the `build-and-check` workflow

https://github.com/typeddjango/django-stubs/blob/ea8e425a794e8b1693de2dbab1ca9ec0fc338048/.github/workflows/test.yml#L174-L179

----

> if we want the ability to keep different release numbers between the packages we can't use the same GitHub releases.

Diverging version numbers are a PITA that we don't want in any case. Otherwise we would also need a separate set of git tags for django-stubs/django-stubs-ext, separate release notes, etc. And possibly other maintenance complexity.

The closest thing to a policy is currently documented in `ext/setup.py`

> NB! For clarity, keep version major.minor.patch in sync with django-stubs.
> It's fine to skip django-stubs-ext releases, but when doing a release, update this to newest django-stubs version.

So, you *could* make the ext release conditional on whether stubs and ext version numbers match in `setup.py`.

But I think releasing both packages regardless of whether there were any changes in ext is clearer and also more foolproof.

**Comment by sobolevn** [comment]
> But I think releasing both packages regardless of whether there were any changes in ext is clearer and also more foolproof.

Yeah, I agree. It should not be a problem to release just the same package. But it can be a problem not to release something.

**Comment by flaeppe** [comment]
Yeah I'm in on this as well. I don't think there's any harm in releasing `django-stubs-ext` regardless of changes.

We just have to think a little bit about the design of the workflow(s) so that the releases can fail and be retried independently

**Comment by intgr** [comment]
@flaeppe Are you interested in adding release automation for `django-stubs-ext` too?

> the design of the workflow(s) so that the releases can fail and be retried independently

That would be nice to have. But even a non-retriable release workflow would be more useful than what we have now.

**Comment by flaeppe** [comment]
Sure I can try when I'm able to (see #2150)
