### ISSUE TITLE
Incompatible types with ManyRelatedManager and through Model

### ISSUE THREAD

**Issue by martinlehoux** [typeddjango/django-stubs#2171]
Hi, when upgrading to version 5.0.0, I get a new error

```py
class Establishment:
	equipments: models.ManyToManyField[Equipment, EquipmentEstablishmentMembership] = models.ManyToManyField(
	        Equipment,
	        through="EquipmentEstablishmentMembership",
	        blank=True,
	        related_name="establishments",
	    )

equipments_manager: manager.ManyRelatedManager[Equipment]
equipments_manager = instance.establishment.equipments # assignment error
```

The fulle error is `Incompatible types in assignment (expression has type "Equipment_ManyRelatedManager[EquipmentEstablishmentMembership]", variable has type "ManyRelatedManager[Equipment, Model]")`

When I looked at the source code, it seems that `Equipment_ManyRelatedManager` is generated by django stubs in certain cases. Is that expected that I receive this type in the calling code?

Thanks!

**Comment by flaeppe** [comment]
`Equipment_ManyRelatedManager` is a subclass of `ManyRelatedManager` and the default manager of your `Equipment` model.

The runtime names it `ManyRelatedManager`. But you can see that it's dynamically subclassed (normally by another manager) here:

https://github.com/django/django/blob/8f205acea94e93a463109e08814f78c09307f2b9/django/db/models/fields/related_descriptors.py#L1040

As long as your `Establishment` class is a subclass of `models.Model`, could perhaps a solution here be to change the `through=` to have a full lazy reference? e.g. `"<app_label>. EquipmentEstablishmentMembership"` Ref: https://github.com/typeddjango/django-stubs/issues/1802#issuecomment-1781423719

And then remove the explicit type annotation for the field as mypy should be able to infer the type itself.

```diff
class Establishment:
-	equipments: models.ManyToManyField[Equipment, EquipmentEstablishmentMembership] = models.ManyToManyField(
+	equipments = models.ManyToManyField(
	        Equipment,
-	        through="EquipmentEstablishmentMembership",
+	        through="<app_label>.EquipmentEstablishmentMembership",
	        blank=True,
	        related_name="establishments",
	    )
```

Additionally, `5.0.0` included an update to `ManyRelatedManager` to have 2 type parameters in #2026. If the type hinting is necessary/wanted for `equipments_manager` you probably want to change:

```diff
-equipments_manager: manager.ManyRelatedManager[Equipment]
+equipments_manager: manager.ManyRelatedManager[Equipment, EquipmentEstablishmentMembership]
```

**Comment by martinlehoux** [comment]
Thanks @flaeppe for your input! I used the lazy reference and removed the type annotation and it works like a charm!
