### ISSUE TITLE
attribute 'bases' of 'TypeInfo' undefined when running mypy after adding a model

### ISSUE THREAD

**Issue by delfick** [typeddjango/django-stubs#2184]
# Bug report

Hi, I'm creating a [mypy plugin that wraps django-stubs](https://extended-mypy-django-plugin.readthedocs.io/en/latest/) so I can work with Abstract models in a way that lets us upgrade past mypy 1.4. I'm writing tests in there that run mypy after modifications and I came across an interesting corner case.

## What's wrong

It seems under some special circumstance, django-stubs can end up with this error

```
  File "mypy/semanal.py", line 1825, in apply_class_plugin_hooks
  File "/Users/stephen.moore/Projects/testing/django-stubs-bug/example-django-stubs-bug-20240526/.venv/lib/python3.10/site-packages/mypy_django_plugin/transformers/models.py", line 954, in process_model_class
    initializer_cls(ctx, django_context).run()
  File "/Users/stephen.moore/Projects/testing/django-stubs-bug/example-django-stubs-bug-20240526/.venv/lib/python3.10/site-packages/mypy_django_plugin/transformers/models.py", line 667, in run
    for statement in self.statements():
  File "/Users/stephen.moore/Projects/testing/django-stubs-bug/example-django-stubs-bug-20240526/.venv/lib/python3.10/site-packages/mypy_django_plugin/transformers/models.py", line 643, in statements
    for base in model.info.bases:
AttributeError: attribute 'bases' of 'TypeInfo' undefined
```

## System information

- OS: OSX/Linux
- `python` version: 3.10
- `django` version: 5.0.0 
- `mypy` version: 1.10.0
- `django-stubs` version: 5.0.0
- `django-stubs-ext` version: 5.0.0

My project also tests against mypy-1.4/django-stubs-4.2.3 and it appears to only be in the newer version of django-stubs

## Reproducing

I've created a script here to reproduce the bug https://gist.github.com/delfick/46bac4f1609e866f01385f77f639d39d. Gist also includes the output it creates. Essentially bootstraps a virtualenv and creates a very basic django project (where one app creates concrete models using an abstract model defined in a seperate app), runs mypy, adds a model and runs mypy again. The second run produces the above exception. if mypy is not run before the additional model is added (or if run with `--no-incremental`) then it works fine.

I found it when I wrote [this test](https://github.com/delfick/extended-mypy-django-plugin/blob/4c0e780efc465852898854d3321e8dac96be8e51/tests/test_concrete_annotations.py#L224-L352). My plugin wraps django-stubs and so I'm able to [put in this "fix"](https://github.com/delfick/extended-mypy-django-plugin/blob/bdc8cbde2963e40a845705726ae73e52f9ce5687/extended_mypy_django_plugin/plugin/_plugin.py#L146-L203) that appears to work in the meantime where I trigger the exception and catch it so I can find and populate the missing information before passing control back to django-stubs itself.

I'm wondering if you were able to find it easier than me to understand why this happens and if there was a better fix?

Thanks!

**Comment by flaeppe** [comment]
I've seen this recently too. The closest I could get is that it _seems_ to be a mypy issue when loading from cache.

In my case it looked like loading from some form of a corrupt cache as a `TypeInfo` should always have a `bases` attribute.

I don't know if it could be related to mypy versions. I would suggest to start out there. If you have a case that can reproduce consistently and don't get the error on a different mypy version, try bisecting mypy.

No need to go way back in versions though as then it's more likely a `django-stubs` issue and you could instead try going back on `django-stubs` versions and bisect.

**Comment by delfick** [comment]
> I don't know if it could be related to mypy versions

If I change my gist to be latest django-stubs and mypy 1.4.0 then it fails on django-stubs 5.0.0 and passes on django-stubs 4.2.7

> As a TypeInfo should always has a bases attribute

It appears it starts with being empty https://github.com/python/mypy/blob/25087fdbb72d1495e6903d171dee999c47ba09fd/mypy/nodes.py#L1161

**Comment by flaeppe** [comment]
I was wrong. I figured out the problem, see #2185 (seems that you found the `FakeInfo` instance too)

**Comment by delfick** [comment]
@flaeppe awesome, thanks!

**Comment by delfick** [comment]
@flaeppe in my solution I end up finding the real TypeInfo, should the fix in django-stubs do the same? I haven't looked too closely into what that class actually does with these tbh.

**Comment by flaeppe** [comment]
I don't think we should patch it. The cache contains no statements and we should be able to run the plugin when loaded from cache without depending on analyzing any definitions.

If our plugin lacks information on a cached run we should instead try to write that information to cache and read it from there.

**Comment by delfick** [comment]
> If our plugin lacks information on a cached run we should instead try to write that information to cache and read it from there.

the main problem is it appears without changes to mypy the only way to write to the metadata for a file is if that file itself changes

Which is especially annoying for Abstract django orm model classes where what they represent is influenced by what concrete children end up getting defined for them.

**Comment by flaeppe** [comment]
Feel free to open any new issues or discussions with the problems you have or encounter
