### ISSUE TITLE
Configure PyPI trusted publisher for `django-stubs-ext` 

### ISSUE THREAD

**Issue by flaeppe** [typeddjango/django-stubs#2187]
PR #2150 introduced automated releases of `django-stubs-ext` https://github.com/typeddjango/django-stubs/actions/runs/9254742886 but PyPI complained that the trusted publisher is invalid. Perhaps it was misconfigured?

Before any next release we should check and adjust the trusted publishing for `django-stubs-ext` at PyPI to correspond with our release workflow.

Below is a print of the output from the action run:

<img width="671" alt="Screenshot 2024-05-27 at 14 30 25" src="https://github.com/typeddjango/django-stubs/assets/3703560/857a9fc8-02d8-43b3-8505-b646c653305d">

---

Ref: #2183

**Comment by sobolevn** [comment]
Done! 
<img width="444" alt="Снимок экрана 2024-05-28 в 09 15 49" src="https://github.com/typeddjango/django-stubs/assets/4660275/377efa25-0927-4eb3-9943-67f8629bb667">

**Comment by flaeppe** [comment]
Superb :ok_hand:, thank you!
