### ISSUE TITLE
How to type UserAdmin?

### ISSUE THREAD

**Issue by tbrlpld** [typeddjango/django-stubs#2193]
# Bug report

I can't seem to satisfy `mypy` when using a custom `UserAdmin`.

## What's wrong

I have:
```python
class UserAdmin(auth_admin.UserAdmin):
    model = users_models.User

    ...
```

When I run `mypy` I get: 
```console
src/users/admin.py:8: error: Missing type parameters for generic type "UserAdmin"  [type-arg]
```

When I try:
```python
class UserAdmin(auth_admin.UserAdmin[users_models.User]):
    model = users_models.User

```

When I run `mypy` I get: 
```console
    class UserAdmin(auth_admin.UserAdmin[users_models.User]):
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: type 'UserAdmin' is not subscriptable

```

## How is that should be

One of those versions should pass the type check I guess? Or I must be doing something wrong. 

## System information

- OS: Docker `python:3.11`
- `python` version: `Python 3.11.8`
- `django` version: `5.0.6`
- `mypy` version: `1.10.0`
- `django-stubs` version: `5.0.2`
- `django-stubs-ext` version: `5.0.2`

**Comment by flaeppe** [comment]
`UserAdmin` or any of its parents doesn't seem to implement the `__class_getitem__` classmethod. If it's a subclass of e.g. `ModelAdmin` you could for instance keep `django-stubs-ext` in your runtime and use it to monkeypatch classes from django that `django-stubs` establishes as generic.

See more here: https://github.com/typeddjango/django-stubs/tree/master/ext

classmethod `__class_getitem__` is also briefly mentioned in the README, here: https://github.com/typeddjango/django-stubs#i-cannot-use-queryset-or-manager-with-type-annotations

Feel free to report back if doing the above results in any other errors. But until then I'll close this off.
