### ISSUE TITLE
Please, don't tag all contributors in release notes

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#2220]
Our current release notes tag all contributors on GitHub: https://github.com/typeddjango/django-stubs/releases/tag/5.0.2

I've recieved several complaints about that. I think that we should not do that. Let's respect people's notification space :)

I propose to change it to:

```
- [by some-person](link-to-github-profile) in #gh-pr-number
```

if this is possible. If not, we can just drop the name part, only keeping the PR number. It will show the author.

**Comment by intgr** [comment]
I thought release notes `@tags` don't create a notification. Or is it because I'm subscribed to releases anyway?

I thought the only reason for pings was when I  checked the box to also create a discussion for the release. https://github.com/typeddjango/django-stubs/discussions/2096

**Comment by sobolevn** [comment]
Can you please try to create a release (maybe on some test project) and ping me in the description there? I will show what will happen :)

**Comment by intgr** [comment]
Sure, will try when I'm back behind a computer

**Comment by intgr** [comment]
I did it yesteday, did you receive a notification? https://github.com/intgr/test-idea-plugin/releases/tag/test-release

**Comment by sobolevn** [comment]
Nope 🎉

**Comment by intgr** [comment]
Our release process is undocumented and not totally straightforward.

I think the "final" solution to this is to create a step-by-step list of instructions about what to do for each release. I already alluded to that in https://github.com/typeddjango/django-stubs/pull/2183#issuecomment-2133319819 too.

There we can document to *keep unchecked* "Create a discussion for this release" when making a release.

What do you think?

**Comment by sobolevn** [comment]
Yes, sounds good to me. https://github.com/typeddjango/django-stubs/blob/master/CONTRIBUTING.md can store this info.
