### ISSUE TITLE
`RawQuerySet`  has conflicting errors: "is not subscriptable" vs "Missing type parameter"

### ISSUE THREAD

**Issue by hterik** [typeddjango/django-stubs#2236]
# Bug report

## What's wrong

Using `RawQuerySet` as type annotation is not possible. 
_Without_ the generic parameter, mypy fails with `is not subscriptable` error. 
_With_ the generic parameter, python throws `TypeError`.

```
from django.db.models.query import RawQuerySet
from models import MyModel

# TypeError: type 'RawQuerySet' is not subscriptable
def foo() -> RawQuerySet[MyModel]:                  
    return MyModel.objects.raw("SELECT id FROM my_model")

# mypy error: Missing type parameters for generic type "RawQuerySet"  [type-arg]
def bar() -> RawQuerySet:                           
    return MyModel.objects.raw("SELECT id FROM my_model")
```

## System information

- OS: Ubuntu 24.04
- `python` version: 3.12.3
- `django` version: 5.0.6
- `mypy` version: 1.10
- `django-stubs` version: 5.0.2
- `django-stubs-ext` version: 5.0.2

**Comment by flaeppe** [comment]
Looks like `RawQuerySet` is missing from the monkeypatch list of classes to add `__class_getitem__` to:

https://github.com/typeddjango/django-stubs/blob/590f033abb9f0b3d10360a975c17b851a8222b88/ext/django_stubs_ext/patch.py#L55-L81

A PR is welcome for fixing that

**Comment by intgr** [comment]
As a work-around, you can also use quoted type hints, e.g.

```python
def foo() -> "RawQuerySet[MyModel]":                  
    return MyModel.objects.raw("SELECT id FROM my_model")
```

or alternatively, add `from __future__ import annotations` to the beginning of the file, which causes evaluation of all type hints to be deferred.
