### ISSUE TITLE
ModuleNotFoundError using a custom apps directory & path

### ISSUE THREAD

**Issue by richkirsch** [typeddjango/django-stubs#224]
To make my apps more reusable, I prefer to use an `apps` directory in my project root to house them, with the following structure:
```
--Project/
    -- manage.py
    -- apps/
        -- app1/
            -- app.py
            -- models.py
            -- etc...
    -- etc ...
```

To make life easier, in `manage.py`, I have the following:
```
current_path = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.join(current_path, "apps"))
```

This enables me to use e.g. `from app1 import SomeClass` anywhere in the project, instead of `from apps.app1 import SomeClass`.

However, this is causing `mypy` with `django-stubs` (though not without it) to crash a with `ModuleNotFoundError`:
```
  File "/Users/me/Projects/AwesomeProject/apps/app2/models.py", line 4, in <module>
    from app1.models import SomeModel
ModuleNotFoundError: No module named 'app1'
```

I had a similar issue with PyLint, but was able to solve it with the help of [this StackOverflow page](https://stackoverflow.com/questions/1899436/pylint-unable-to-import-error-how-to-set-pythonpath), taking advatange of an initialisation hook to set the system path in a similar way to above but in `.pylintrc`, like so:
```
[MASTER]
init-hook='
  import os, sys;
  from pylint.config import find_pylintrc;
  sys.path.append(os.path.join(os.path.dirname(find_pylintrc()), 'apps'))'
load-plugins=pylint_django, pylint_celery
...
```

My questions are:
    1) Is there a similar approach I can take?
    2) Otherwise, what are alternative suggestions?

**Comment by Atala** [comment]
I think a workaround is to add the `apps`  folder to your PYTHONPATH :
```
PYTHONPATH=:<path_to_apps_folder> mypy
```

**Comment by LucidDan** [comment]
I do this too, using a dedicated apps directory, and as @Atala says, I adjust my PYTHONPATH, which works fine.

**Comment by flyte** [comment]
This isn't possible when you don't control the calling environment creation such as when mypy is called from the Python extension in VSCode.

Could this module respect the `mypy_path` `mypy.ini` setting and add those paths before trying to import the Django settings file?

https://mypy.readthedocs.io/en/stable/config_file.html#import-discovery
