### ISSUE TITLE
is_relation and related_model attributes are not declared on the Field stub

### ISSUE THREAD

**Issue by youssefm** [typeddjango/django-stubs#228]
# Bug report

## What's wrong

When type checking a function that looks like this with mypy

```python
def my_function(model_cls: Type[models.Model]) -> None:
    try:
        django_field = model_cls._meta.get_field('my_field')
    except FieldDoesNotExist:
        return
    if django_field and django_field.is_relation:
        related_model = django_field.related_model
```

you get the following errors:

```
error: "Field[Any, Any]" has no attribute "is_relation"
error: "Field[Any, Any]" has no attribute "related_model"
```

These are attributes that are always available on Fields and should be declared in the stub. See:

https://github.com/django/django/blob/89368ab6e358ebe29a0417d65209182238daa245/django/db/models/fields/__init__.py#L120

and

https://github.com/django/django/blob/89368ab6e358ebe29a0417d65209182238daa245/django/db/models/fields/__init__.py#L145

I believe the right annotations are `bool` and `Optional[Type[Model]]` respectively.

## How is that should be

There shouldn't be any mypy errors.

## System information

- OS: Mac OS 10.14
- `python` version: 3.6.5
- `django` version: 2.2.4
- `mypy` version: 0.740
- `django-stubs` version: 1.2.0

**Comment by sobolevn** [comment]
@youssefm thanks! Can you please send a PR with the fix?
