### ISSUE TITLE
django.contrib.auth should return the configured User type

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#2293]
# Bug report

https://github.com/typeddjango/django-stubs/blob/9b50861f0db34b48a52a29655e40abe48fcd7574/django-stubs/contrib/auth/__init__.pyi#L21

probably would require a mypy plugin to adjust the type similar to the one for `django.contrib.auth.get_user_model`

I suspect #1353 is related at least and may be solved by fixing this as well

(sorry for cutting off the rest of the bug report template -- I haven't been able to pin down a minimal example!)

**Comment by flaeppe** [comment]
After reading through #1353 it seems that will also be closed by adjusting `authenticate` with the plugin.

I think one form of minimal example is

```python
# myapp/models.py
from django.db import models

class User(models.Model): ...
```

```python
# settings.py
INSTALLED_APPS = ["django.contrib.contenttypes", "django.contrib.auth", "myapp"]
AUTH_USER_MODEL = "myapp.User"
```

```python
# main
from django.contrib.auth import authenticate
reveal_type(authenticate())  # N: Revealed type is "Union[myapp.models.User, None]"
```
