### ISSUE TITLE
In setup steps : "pip install django-stubs[compatible-mypy]" returns "no matches found: django-stubs[compatible-mypy]"

### ISSUE THREAD

**Issue by MarArMar** [typeddjango/django-stubs#2315]
# Bug report

## What's wrong

```
pip install django-stubs[compatible-mypy]
> no matches found: django-stubs[compatible-mypy]
pip --version
pip 24.2 (python 3.11)
```

## How is that should be

Should work ?

## System information

- OS:
- `python` version: 3.11
- `django` version: 5.0.7
- `mypy` version: 
- `django-stubs` version:
- `django-stubs-ext` version:

**Comment by sobolevn** [comment]
Please, try `pip install 'django-stubs[compatible-mypy]'`, I've update the README file.
Thanks for the report! 👍
