### ISSUE TITLE
No error when creating `django.db.models.Model` instance with incompatible property type

### ISSUE THREAD

**Issue by pchabros** [typeddjango/django-stubs#2339]
# Bug report

## What's wrong
Mypy does not report any error nor warning for below code:

```py
from django.db.models import Model, CharField


class Foo(Model):
    name = CharField[str, str]()


foo = Foo(name=123)
``` 

## How is that should be

Since there are two generic types to be passed (set and get) I expect to get error when I want to create instance of `Foo` with incompatible type for `name` property.

## System information

- OS:
- `python` version: 3.11.7
- `django` version: 4.2.10
- `mypy` version: 1.10.0
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

**Comment by flaeppe** [comment]
Thanks for the report, I can reproduce this with `4.2.7` but not with our latest release `5.0.4`, my conclusion here would be to upgrade `django-stubs` to a newer version as we currently don't have the capacity to backport a fix for this.

I will close this as resolved.
