### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lundberg** [typeddjango/django-stubs#241]
A new release of master to pypi would be nice, thanks.

**Comment by brianhelba** [comment]
@mkurnikov Is it possible to release a `1.2.1` version now? The latest release of `django-stubs` is broken under typical install scenarios, and requires ugly package pinning (which must later be reverted) by downstreams to be usable. This even breaks CI for related upstream projects such as [djangorestframework-stubs](https://github.com/typeddjango/djangorestframework-stubs).

#238 fixes the breakage, and it looks like the [roadmap for `1.3.0`](https://github.com/typeddjango/django-stubs/milestone/3) will take significantly more time to complete.

**Comment by mkurnikov** [comment]
I'll finish testing for Django 3.0, and then release.
