### ISSUE TITLE
Admin: log_addition/log_change/log_deletion have incorrect parameter names

### ISSUE THREAD

**Issue by sergei-maertens** [typeddjango/django-stubs#2413]
# Bug report

## What's wrong

In the `admin/options.pyi` stubs, the `log_addition`, `log_change` and `log_deletion` use the `object` parameter name for the object affected, however the Django methods (4.2 and main, see https://github.com/django/django/blob/3fad712a91a8a8f6f6f904aff3d895e3b06b24c7/django/contrib/admin/options.py#L944) use `obj` for the paremeter name.

This results in Pyright disagreeing with overrides:

```
src/woo_publications/logging/admin_tools.py
  src/woo_publications/logging/admin_tools.py:23:9 - error: Method "log_addition" overrides class "ModelAdmin" in an incompatible manner
    Parameter 3 name mismatch: base parameter is named "object", override parameter is named "obj" (reportIncompatibleMethodOverride)
  src/woo_publications/logging/admin_tools.py:28:9 - error: Method "log_change" overrides class "ModelAdmin" in an incompatible manner
    Parameter 3 name mismatch: base parameter is named "object", override parameter is named "obj" (reportIncompatibleMethodOverride)
  src/woo_publications/logging/admin_tools.py:33:9 - error: Method "log_deletion" overrides class "ModelAdmin" in an incompatible manner
    Parameter 3 name mismatch: base parameter is named "object", override parameter is named "obj" (r
```

MyPy doesn't appear to report any problems related to the parameter names.

## How is that should be

Change the `object` variable name to `obj`.

## System information

- OS:
- `python` version: 3.12.6
- `django` version: 4.2.16
- `mypy` version: 1.11.2
- `django-stubs` version: 5.1.0
- `django-stubs-ext` version: 5.1.0

**Comment by sobolevn** [comment]
PR is welcome :)

**Comment by sergei-maertens** [comment]
I shall create one later today!
