### ISSUE TITLE
[Documentation request] Version compatibility: What does "partial" mean, and why does this package not pin its dependencies?

### ISSUE THREAD

**Issue by khink** [typeddjango/django-stubs#2429]
# Documentation request

The [Version compatibility](https://github.com/typeddjango/django-stubs#version-compatibility) table has me wondering: What is the difference between "Django version" column and "Django partial support"? Maybe it could be explained next to the table?

Also, i'm wondering why these versions can not be pinned in setup.py. I'm sure there's a reason, maybe it could be documented. 

The reason i ask is: 
- I upgraded to the latest django-stubs and mypy, on Django 4.2, and all works fine. Having seen the compatibility table after that fact, I'm wondering if using latest versions is a sane approach.
- I'd prefer to pin as few packages as possible, and use [pip-tools](https://github.com/jazzband/pip-tools) to find the latest compatible versions. This uses the packages' setup.py.

**Comment by flaeppe** [comment]
I think you might get some answers in the following discussion: https://github.com/typeddjango/django-stubs/discussions/2101

Might be that we should move some of that info into the README. Or we might just link to the discussion from the README, like some "further reading"

**Comment by khink** [comment]
That discussion kind of answers my question about using setup.py to require specific Django/mypy versions: It would remove the freedom of people to use "partially" supported versions if they wish to do so. Thanks!
