### ISSUE TITLE
Error in NewSemanalDjangoPlugin.get_additional_deps: 'str' object is not callable

### ISSUE THREAD

**Issue by mattbonnell** [typeddjango/django-stubs#243]
# Bug report

## What's wrong
I get this error when I try to run mypy from the command line:
``` 
File "C:\cygwin64\home\bonm020\.virtualenvs\relationship-index-izKo2f_E\lib\site-packages\mypy_django_plugin\main.py", line 124, in get_additional_deps
    if file.fullname() == 'django.conf' and self.django_context.django_settings_module:
TypeError: 'str' object is not callable
```

## How is that should be
This is the output when I disable the plugin:
```
$ python -m mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers d:\\dev\\relationship-index\\relationshipindex\\urls.py
d:\dev\relationship-index\relationshipindex\urls.py:3:1: error: Module 'relationshipindex' has no attribute 'api'
Found 1 error in 1 file (checked 1 source file)
```

## System information

- OS:
- `python` version: 3.7.4
- `django` version: 2.2.7
- `mypy` version: 0.750
- `django-stubs` version: 1.2.0

**Comment by mattbonnell** [comment]
@mkurnikov do you know if there's a previous version I could drop down to to avoid this problem?

**Comment by mkurnikov** [comment]
mypy 740 should be fine. Or you could just move from `fullname()` to `fullname` (to property) in the forked version, it should work too.
