### ISSUE TITLE
Incorrect type for `get_object()` in view mixins

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#263]
# Bug report

## What's wrong

This code:

```python
class SubmissionRetryView(SubmissionCreateView, UpdateView):
    """This view is used to send the application submission once again."""

    pk_url_kwarg = ''  # do not allow to query by pk
    slug_url_kwarg = 'uid'
    slug_field = 'uid'
    context_object_name = 'instance'

    def get_queryset(self):
        """Returns custom queryset for each user."""
        return filter_submissions_to_retry(self.request.user.link.profile)

    def get_object(
        self, queryset: Optional[QuerySet[ApplicationSubmission]] = None,
     ) -> ApplicationSubmission:
        """Returns the post-processed copy of an application submission."""
        instance = super().get_object(queryset=queryset)
        reveal_type(instance)
        return prepare_submission_for_retry(instance)
```

Where `prepare_submission_for_retry` is `def prepare_submission_for_retry(instance: ApplicationSubmission) -> ApplicationSubmission:`

Raises this error:

```python
server/web_app/views/submission.py:124: note: Revealed type is 'django.db.models.base.Model'
server/web_app/views/submission.py:125: error: Argument 1 to "prepare_submission_for_retry" has incompatible type "Model"; expected "ApplicationSubmission"
```

## How is that should be

`get_object` should return instance type from `QuerySet`.

## System information

- `python` version: 3.7
- `django` version: 2.2
- `mypy` version: 0.750
- `django-stubs` version: 1.3

**Comment by jhabarsingh** [comment]
@sobolevn, I would like to work on this issue.

**Comment by jhabarsingh** [comment]
'get_object should return instance type from QuerySet'. Can you explain this  to me in detail ?

**Comment by jhabarsingh** [comment]
"get_object should return instance type from QuerySet". can you explain this to me.

**Comment by sondrelg** [comment]
Hi! 

I was about to ask a similar question to this, so I'll ask here instead:

### Background

Given some example code, like:

```python
class ExampleView(SingleObjectMixin, View):
    model = Contract

    def post(self):
        obj = self.get_object()
        ...
```

The [current](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/views/generic/detail.pyi#L16) code stubs indicates that we will receive a `models.Model` back from `get_object`. 

![image](https://user-images.githubusercontent.com/25310870/116253221-91400600-a770-11eb-9bfa-160613a24410.png)

### Question

This isn't wrong, but to make Pycharm happy I sometimes find myself sometimes doing this:

```python
class ExampleView(SingleObjectMixin, View):
    model = Contract

    if TYPE_CHECKING:
        def get_object(self, queryset=None) -> Contract:
            ...

    def post(self):
        obj = self.get_object()
        ...
```

![image](https://user-images.githubusercontent.com/25310870/116253413-c2203b00-a770-11eb-853d-a0f536fd8967.png)

This works for each individual class, but do you think it would be possible to generalize this soliution by changing the stub to just return the class' `model` attribute? It seems to work for me in a local scope:

![image](https://user-images.githubusercontent.com/25310870/116253546-dd8b4600-a770-11eb-9f14-89e5ff704edb.png)

**Comment by sobolevn** [comment]
Yes, this seems doable. PRs are, as always, welcome.

**Comment by sondrelg** [comment]
After looking at it a little, I don't think `-> model` is a completely legal way of doing it, unfortunately. 

I could be wrong, but it seems like we need a mechanism for saying "mirror the type assigned to model later", without just using `model` directly. 

Do you know of anything in the typing library that does this @sobolevn?

**Comment by sobolevn** [comment]
@sondrelg `SingleObjectMixin` can be generic on `ObjectType`: https://github.com/typeddjango/django-stubs/blob/master/django-stubs/views/generic/detail.pyi#L8

So, it would be:

```python
T = TypeVar('T', bound=models.Model)

class SingleObjectMixin(Generic[T]):
    model: Type[T]
   
    def get_object(self) -> T: ...
    def get_queryset(self) -> models.query.QuerySet[T]: ...
```
