### ISSUE TITLE
Reverse manager should be a subclass of `_default_manager` of related model

### ISSUE THREAD

**Issue by youssefm** [typeddjango/django-stubs#269]
# Bug report

## What's wrong

``` python
class User(Model):
    pass

class OrderManager(Manager):
    @property
    def active(self):
        return self.exclude(state='canceled')

class Order(Model):
    objects = OrderManager()
    user = models.ForeignKey(User, related_name='orders')
```

When type checking:

`count: int = user.orders.active.count()`

it should succeed, but instead we get:

`error: "RelatedManager[Order]" has no attribute "active"`

It seems like the wrong manager gets associated with `user.orders`. The real manager is a subclass of the default manager for the model - see https://github.com/django/django/blob/26cab4e8c113b873b99b747128a064ba72d40c74/django/db/models/fields/related_descriptors.py#L551.

## System information

- OS:
- `python` version: 3.6.5
- `django` version: 2.2.1
- `mypy` version: 0.750
- `django-stubs` version: tested with latest master as of 6b3b6be3c139d1165925ee02e39b8ea3135e368f

**Comment by mkurnikov** [comment]
> The real manager is a subclass of the default manager for the model

Shouldn't it be a `_base_manager`? https://docs.djangoproject.com/en/3.0/topics/db/managers/#base-managers 
Which is still a `Manager` in your example. 

On other hand, from this code https://github.com/django/django/blob/26cab4e8c113b873b99b747128a064ba72d40c74/django/db/models/fields/related_descriptors.py#L519
it seems that `_default_manager` is used (which will be consistent with your example)

**Comment by youssefm** [comment]
The documentation doesn't seem entirely clear, but Django's behavior is that a subclass of the default manager seems to be used. Here's some testing I did:

``` python
In [5]: isinstance(user.orders, type(Order._default_manager))
Out[5]: True

In [6]: isinstance(user.orders, type(Order._base_manager))
Out[6]: True

In [7]: type(user.orders)
Out[7]: django.db.models.fields.related_descriptors.create_reverse_many_to_one_manager.<locals>.RelatedManager

In [8]: type(user.orders).__bases__
Out[8]: (OrderManager,)

In [10]: type(Order._default_manager) in type(user.orders).__bases__
Out[10]: True

In [11]: type(Order._base_manager) in type(user.orders).__bases__
Out[11]: False
```

**Comment by AdrienLemaire** [comment]
Looks like I have the same issue.

```py
class PlanManager(models.Manager):
    def active(self) -> models.query.QuerySet:
        return self.get_queryset().filter(completed_on__isnull=True).distinct()

class Plan(index.Indexed, ClusterableModel):
    completed_on = models.DateTimeField(blank=True, null=True)
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_("Student"),
        related_name="student_plans",
    )

class ProfilePage(RoutablePageMixin, Page):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        verbose_name=_("User"),
    )

    def get_context(self, request: HttpRequest, *args: list, **kwargs: dict) -> dict:
        plan = self.user.student_plans.active().first()  # [mypy error] [E] "RelatedManager[Plan]" has no attribute "active"
```

I'll do this temporarily
```diff
+ from typing import cast

-         plan = self.user.student_plans.active().first()
+         plan = cast("PlanManager", self.user.student_plans).active().first()
```
Hopefully this isn't wrong, please let me know otherwise

**Comment by flaeppe** [comment]
I think this can be closed. I'm not able to recreate it on `master`. And #825 changed so that reverse managers are a subclass of the related model's `_default_manager`.
