### ISSUE TITLE
Assigning an incompatible type to a model field instance does not raise an error

### ISSUE THREAD

**Issue by frnhr** [typeddjango/django-stubs#283]
I think this should raise a typing error:

``` python
class User(AbstractUser):
    name = models.CharField(...)
    ....

user = User()
user.name = 123  # <-- this is fine under current stubs.
```

Expected behaviour can be achieved like so (with a bunch of other downsides, I expect):

``` python
class User(AbstractUser):
    name: str = models.CharField(...)  # type: ignore
    ....

user = User()
user.name = 123  # <-- error: Incompatible types in assignment (expression has type "int", variable has type "str")
```

Am I wrong in expecting to see the error (like in the second example) instead of a no-error situation (which is what actually happens)?

**Comment by flaeppe** [comment]
[This should be covered nowadays](https://github.com/typeddjango/django-stubs/blob/348ae5f4896f023fa89d6bbc6e2b20de0f56f311/tests/typecheck/models/test_init.yml#L298), yielding an error where mentioned as expected. Also with an appropriate descriptor class (not requiring any ignores)
