### ISSUE TITLE
Incorrect type for django.core.files.File.file

### ISSUE THREAD

**Issue by danifus** [typeddjango/django-stubs#293]
# Bug report

## What's wrong

Trying to assign the result of `open()` to a `File.file` attribute results in the following warning:

```
Incompatible types in assignment (expression has type "IO[Any]", variable has type "StringIO")
``` 

```
# Failing example:

import django.core.files

class MyFile(django.core.files.File):

    def open(self, mode=None):
        # (This is the File.open() method from django)
        if not self.closed:
            self.seek(0)
        elif self.name and os.path.exists(self.name):
            self.file = open(self.name, mode or self.mode)
        else:
            raise ValueError("The file cannot be reopened.")
        return self
```

## How is that should be

No error should be raised.

https://github.com/typeddjango/django-stubs/blob/master/django-stubs/core/files/base.pyi#L11

is `file: StringIO = ...` but should probably be `file: IO[Any] = ...`

## System information

- OS: mac
- `python` version: 3.7.5
- `django` version: 2.2
- `mypy` version: 0.750
- `django-stubs` version: 1.3.0

**Comment by sobolevn** [comment]
Thanks, @danifus would you like to send a PR?
