### ISSUE TITLE
Consider adding wsgitypes

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#302]
https://github.com/shabbyrobe/wsgitypes

I am not sure if this is helpful or not, just wanted to share the possibility.

**Comment by adamchainz** [comment]
Python 3.11 now includes [`wsgiref.types`](https://docs.python.org/3.11/library/wsgiref.html#module-wsgiref.types) - if we need WSGI types, they should come from there or the [typeshed version](https://github.com/python/typeshed/blob/master/stdlib/wsgiref/types.pyi).
