### ISSUE TITLE
Can't assign AnonymousUser to request.user

### ISSUE THREAD

**Issue by lfrodrigues** [typeddjango/django-stubs#309]
# Bug report

I'm implementing my own logout routine and need to assign AnonymousUser to request.user like:

```
        if hasattr(request, 'user'):
            from django.contrib.auth.models import AnonymousUser

            request.user = AnonymousUser()
```

## What's wrong
The code above has the error:

error: Incompatible types in assignment (expression has type "AnonymousUser", variable has type "AbstractBaseUser")

## How is that should be

request.user should allow both AnonymousUser and AbstractBaseUser

## System information

- OS: Ubuntu 18.04
- `python` version: 3.6
- `django` version: 2.2
- `mypy` version: 0.761
- `django-stubs` version: 1.4.0

**Comment by kalekseev** [comment]
@lfrodrigues you can always define your own Request type and use it across your database.

@mkurnikov One way to solve this would be to use `Union[AbstractBaseUser, AnonymousUser]` type on request, with [tagged unions](https://mypy.readthedocs.io/en/latest/literal_types.html#tagged-unions) support mypy should discriminate union type based on `is_authenticated` check:
```
if request.user.is_authenticated:
   reveal_type(request.user)  # AbstractBaseUser
else:
   reveal_type(request.user). # AnonymousUser
```

Although that change may be inconvenient for user who have mostly protected views, it will cover general case for Django apps.

**Comment by lfrodrigues** [comment]
Thanks for the suggestion but it adds complexity to my code. 

Django itself can have AbstractBaseUser or AnonymousUser in request.user. I'll wait for a fix :)
