### ISSUE TITLE
__get__ of foreign key field returns "ForwardManyToOneDescriptor" instead of model

### ISSUE THREAD

**Issue by lassesteffen** [typeddjango/django-stubs#311]
# Bug report

## What's wrong

Model:

```python

class User(models.Model, AbstractBaseUser, PermissionsMixin):
    email = EmailField(unique=True)
    ...

    USERNAME_FIELD = 'email'


class MembershipInvitation(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    ...
```

Test:
```python
self.assertTrue(invitation.host.email in message)
```

mypy result:

`"ForwardManyToOneDescriptor" has no attribute "email"`

## How is that should be

`invitation.host` should have been correctly recognized as `User`

## System information

- OS: macOS Catalina 10.15.2
- `python` version: 3.8
- `django` version: 3.0.2
- `mypy` version: 0.761
- `django-stubs` version: 1.4.0

Thanks a lot for the great work. I just started using this library, so let me know if I can assist you!

**Comment by flaeppe** [comment]
This shouldn't be an issue in more recent versions
