### ISSUE TITLE
django.utils.learn_cache_key incorrect type

### ISSUE THREAD

**Issue by vsalvino** [typeddjango/django-stubs#314]
# Bug report

## What's wrong
`django.utils.learn_cache_key()` has the incorrect type specified for the `cache` parameter.

https://github.com/typeddjango/django-stubs/blob/f89a0fbbaa53a23b80fd0b9bfe8fdbf71da35de8/django-stubs/utils/cache.pyi#L31

It is currently set as `Optional[LocMemCache]` but in reality this can be any valid type of `BaseCache`. Looking into the function you can see if `cache=None` then it is pulled from `django.core.cache.caches` which returns a `BaseCache` type.

## System information

- OS: Windows 10, 64-bit
- `python` version: 3.8.1, 64-bit
- `django` version: 3.0.2
- `mypy` version: 0.761
- `django-stubs` version: 1.4.0

**Comment by sobolevn** [comment]
@vsalvino would you please send a PR?
