### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by AndreyMZ** [typeddjango/django-stubs#330]
Django 3.0 was released quite long ago. The support of Django 3.0 is needed.

**Comment by sobolevn** [comment]
Yes, we are working on it #246

**Comment by intgr** [comment]
#246 was merged ages ago, can this issue be closed or is there something significant still missing?

**Comment by askoretskiy** [comment]
So, is Django 3.0 is supported out of the box? `README.md` does not state it is supported.

**Comment by sobolevn** [comment]
It is partially supported right now. We do plan to work on this during GSoC.

**Comment by aleksanb** [comment]
FWIW i'm runnning django-stubs on a large django 3.0 / DRF setup, and everything's working smooth.

**Comment by askoretskiy** [comment]
I personally have only issue with `asgi.py` that is not in stubs.

What I could suggest is to update `README.md` to indicate that Django 3.0 is "partially supported"

**Comment by AndreyMZ** [comment]
`README.md` was updated in scope of #390 to indicate that Django 3.x are supported.

**Comment by AndreyMZ** [comment]
Reopened until the next version of `django-stubs` (with the changes includes) is released.

**Comment by AndreyMZ** [comment]
Closed as django-stubs 1.6.0 has been released.
