### ISSUE TITLE
patch_response_headers expecting float for number of seconds

### ISSUE THREAD

**Issue by MarcinWieczorek** [typeddjango/django-stubs#337]
## What's wrong
`patch_response_headers` from `django-stubs.utils.cache.pyi` expects `float` as the second parameter.

Original code:
https://github.com/django/django/blob/master/django/utils/cache.py#L249
Stubs source:
https://github.com/typeddjango/django-stubs/blob/master/django-stubs/utils/cache.pyi#L18

## How is that should be
The source code of django says:
> cache_timeout is in seconds.

Why would it be a float? I checked the history (of the stubs), it used to be an int but was later changed without apparent reason. Also it's nullable, so it could even be `Optional[int]`. Correct me if I'm wrong. I'm willing to do the patching if this is confirmed.

## System information

- OS: ArchLinux
- `python` version: 3.7
- `django` version: 3.0.2
- `mypy` version: 0.761
- `django-stubs` version: 1.4.0

**Comment by sobolevn** [comment]
@MarcinWieczorek are you willing to fix this? 🙂

**Comment by MarcinWieczorek** [comment]
Yes, as I said. May I consider this bug confirmed?

Edit: I don't know what kind of a test would be appropriate for this issue. Could you link me a similar one?
