### ISSUE TITLE
Please do a new release

### ISSUE THREAD

**Issue by intgr** [typeddjango/django-stubs#342]
Now that mypy 0.770 is released and #341 added support for it, can you please do another official release?

**Comment by sobolevn** [comment]
Yes, we can. But, I need @mkurnikov's help here.

**Comment by mkurnikov** [comment]
Done. 

I don't use Python much nowadays, so please don't expect any maintenance efforts from me any time soon. I'll update the library to support `__class_getitem__` when https://github.com/django/django/pull/12405 is merged.

**Comment by intgr** [comment]
Thank you :)

PS: If you're scaling down your involvement in TypedDjango, have you considered granting PyPI access to someone else as well, perhaps sobolevn?
