### ISSUE TITLE
"Model" has no attribute "_state"

### ISSUE THREAD

**Issue by stevanmilic** [typeddjango/django-stubs#347]
# Bug report

The `mypy` reports that model is missing the `_state` attribute. I've checked the source code and it looks like the `ModelState` is defined, but it isn't included into `Model`.

## What's wrong
Run mypy on:
```python
def is_updated(instance: Model):
    return not instance._state.adding
```

And you will get an error:
```
error: "Model" has no attribute "_state"
```
## How is that should be

No error should be reported since `Model` has the `_state` attribute.

## System information

- OS:
- `python` version: 3.8
- `django` version: 2.2
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

I would be happy to provide PR, since the fix is straightforward.

**Comment by sobolevn** [comment]
@stevanmilic thanks a lot! Would you please submit a fix for it?
