### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by kszmigiel** [typeddjango/django-stubs#349]
Hello!

I know it's an unwanted way to contact you gentlemen @sobolevn @mkurnikov but I have not much time left. Yesterday I wrote emails to both of you regarding GSoC 2020, and I look forward to hearing from you. I would like to kindly ask if you could respond to me ASAP, as the deadline to send the proposal passes on Tuesday.

Please don't feel offended by my message here, I'm just a little desperate at this point.

Kindest regards,
Kacper

**Comment by sobolevn** [comment]
@kszmigiel thanks a lot! 👍 

I have got your email, but didn't have time during weekends to write you a reply. 
Let's continue in the email thread!

Best,
Nikita Sobolev
