### ISSUE TITLE
Error for django.conf.settings

### ISSUE THREAD

**Issue by V-ampire** [typeddjango/django-stubs#352]
I have got error when i try to use django settings object.
Something like this:
```
from django.conf import settings

billing_config = settings.BILLING

token = billing_config['Yandex']['token']
```
Got errors:
```
error: Value of type "_VT" is not indexable
error: Invalid index type "str" for "dict"; expected type "_KT"
```
Is this real issue or I just should use some option in conf. file?

**Comment by sobolevn** [comment]
Thanks for the report! Lets join it together with #312
