### ISSUE TITLE
When using from_queryset, attributes are missing

### ISSUE THREAD

**Issue by dragonpaw** [typeddjango/django-stubs#353]
# Bug report
## What's wrong

I have a custom FooManager, and FooQueryset, and as per Django docs, I'm using from_queryset to initialize the Manager for the class, and it's not discovering the attributes of the QuerySet.

```python
class FooQuerySet(models.QuerySet):
    def closed(self):
        return self.filter(is_closed=True)

class FooManager(models.Manager):
    def whatever(self):
        pass

class Foo(models.Model):
    objects = FooManager.from_queryset(FooQuerySet)()
    # As documented: https://docs.djangoproject.com/en/2.2/topics/db/managers/#from-queryset
```

```console
$ mypy fooapp
foo/app/models.py:107: error: "RelatedManager[Foo]" has no attribute "closed"
```

FYI, when building a manager this way, it ends up being something like `django.db.models.manager.FooManagerFromFooQuerySet`

## How is that should be
Ideally, it would see the `closed` method on my custom QuerySet

## System information

- OS: OSX
- `python` version: 3.7.6
- `django` version: 2.2.8
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by sobolevn** [comment]
Yes, this is a well-known bug of `django-stubs`. We have to refactor mypy plugin to fix it.
Sorry for the inconvenience 😞

**Comment by kszmigiel** [comment]
The good news is that piece of code given by @dragonpaw does not cause problems at refactored version. To be released soon!

**Comment by haplo** [comment]
> The good news is that piece of code given by @dragonpaw does not cause problems at refactored version. To be released soon!

Was that fixed version ever released? Because I'm currently experiencing this bug and just found this issue.

**Comment by Syntaf** [comment]
I know this thread is old - but bumping what @haplo asked. Did this ever actually get resolved?

As a workaround, if you'd prefer to make MyPy aware of queryset methods, you can "incorrectly" type the manager on the model, since django-stubs adds manager methods on all querysets:

```
class FooQuerySet(models.QuerySet):
    def closed(self):
        return self.filter(is_closed=True)

class FooManager(models.Manager):
    def whatever(self):
        pass

class Foo(models.Model):
    objects: FooQuerySet = FooManager.from_queryset(FooQuerySet)()

# manager methods won't return the correct type
foo: Foo = Foo.objects.get(id=15) # type: ignore

# queryset attributes will be correctly typed however
qs = Foo.objects.closed()
```

For me, personally, I find MyPy more useful for checking queryset attributes rather than the return type of manager methods like `create` `get` and so on.
