### ISSUE TITLE
Using TypedDict for templates rendering

### ISSUE THREAD

**Issue by dmerejkowsky** [typeddjango/django-stubs#355]
# Bug report

## What's wrong

So, not sure if it's a bug or not - maybe what I'm trying to achieve is
outside the scope of the typeddjango project. Anyway, here goes.

I have a `view_index()` view that delegates building the context used
for template rendering to a `IndexPresenter` class with a `get_context()`
method:

Here are the relevant snippets (tell me if you need more):

```python
from tying import TypedDict
from models import User, Category

IndexContext = TypedDict("IndexContext", {"user": User, "categories": List[Category]})

class IndexPresenter:
    def __init__(self, user: User):
        self.user = user

    def get_context(self) -> IndexContext:
        categories = Category.objects.all().order_by("name")
        return {"user": self.user, "categories": list(categories)}

@login_required()
def index(request: HttpRequest) -> HttpResponse:
    user = request.user
    presenter = IndexPresenter(user)
    context = presenter.get_context()
    return render(request, "audiotheque/index.pug", context)
```

You can see I'm using the new ``TypedDict`` from Python 3.8

The problem is that `mypy` complains about the last line:

```
Argument 3 to "render" has incompatible type  "IndexContext";
expected "Optional[Dict[str, Any]]"
```

## How is that should be

I guess that mypy should see that a TypedDict is compatible with a `Dict[str, Any]` somehow?

## System information

- OS:
- `python` version: 3.8.2
- `django` version: 3.0.3
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by dmerejkowsky** [comment]
Oh, and one more thing - I don't really mind if the type check does not work "all the way through" - I think that the annotation of the returned dict already serves quite nicely as "executable documentation" for the templates authors :)

**Comment by kszmigiel** [comment]
@dmerejkowsky Hello! I've investigated your code, and I think that's not really a problem with Mypy. The reason is this part:
```
TypedDict("IndexContext", {"user": User, "categories": List[Category]})
```
Here you define "user" as User instance, while `render()` function expects `context` to be `Dict[str, Any]` or none.

Also, it's weird that Mypy hasn't warned you about doing `"user": self.user`. According to `AbstractBaseUser` class in Django `self.user` returns a string:
```
def __str__(self):
        return self.get_username()
```

So, changing `"user": User` to `"user": str` should do the job. Unfortunately I had no time to check it, so please let me know if it works :)

**Comment by dmerejkowsky** [comment]
I don't think it's an issue in django-stubs actually

This also fails:

```python
from typing import Any, Dict, TypedDict


IndexContext = TypedDict("IndexContext", {"user": str})


def get_context() -> IndexContext:
    return {"user": "john"}


def render(context: Dict[str, Any]) -> None:
    print(context)


def main() -> None:
    context = get_context()
    render(context)
```
I've aked on mypy bug tracker: https://github.com/python/mypy/issues/8923

**Comment by kszmigiel** [comment]
@dmerejkowsky Now I see that my first comment was actually pretty dummy, so sorry for that. I haven't checked Mypy docs on TypedDict, and it was pretty late at night when I was writing it iirc.

So, according to [this Mypy issue](https://github.com/python/mypy/issues/4976) it's done on purpose, and probably there's no convenient way to make `TypedDict` work when `Dict` is expected (probably there exists some workaround, who knows). The solution to this would be to change type annotation for `context` in stubs from `Dict` to `Mapping`. I'd like to ask @sobolevn for opinion on this.

**Comment by dmerejkowsky** [comment]
> Now I see that my first comment was actually pretty dummy

No worries - it happens. Also, it forced me to write a simpler example, so this was actually a win :)

> The solution to this would be to change type annotation for context in stubs from Dict to Mapping. I'd like to ask @sobolevn for an opinion on this.

I agree. It looks like a good idea from where I'm standing but I'm not aware of all the implications.

Thanks for your help anyway.

**Comment by sobolevn** [comment]
Yes, we can try `Mapping`!

**Comment by dmerejkowsky** [comment]
Thank you - keep up the good work!
