### ISSUE TITLE
django.contrib.admin.helpers.AdminForm expects change password form

### ISSUE THREAD

**Issue by tumb1er** [typeddjango/django-stubs#358]
# Bug report

## What's wrong
```
admin_wizard/admin.py:30: 
error: Argument 1 to "AdminForm" has incompatible type "BaseForm"; expected "AdminPasswordChangeForm"
admin_form = helpers.AdminForm(
            # django-stubs bug
            form,  # BaseForm
            fieldsets,
            prepopulated_fields={},
            model_admin=self.model_admin)
```

## How is that should be

`AdminForm.__init__`  should have `form: BaseForm`  parameter.

## System information

- OS: ubuntu 18.04
- `python` version: python3.8
- `django` version: 3.0.5
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by sobolevn** [comment]
Thanks a lot for the bug report! @tumb1er are you willing to submit a fix? Please 🙂
