### ISSUE TITLE
Invalid typings for django.core.cache.backends.base.BaseCache

### ISSUE THREAD

**Issue by Ashish-Bansal** [typeddjango/django-stubs#362]
# Bug report

`django.core.cache.backends.base.Base` typings are invalid. 

According to https://github.com/django/django/blob/447980e72ac01da1594dd3373a03ba40b7ee6f80/django/core/cache/backends/base.py#L108, add operation should be returning `True` if the value was stored, otherwise `False`, but in the typings, it's set to None. 

https://github.com/typeddjango/django-stubs/blob/96914e466bcd7a65fdd92422586f9ebc72fdf8a8/django-stubs/core/cache/backends/base.pyi#L22

Similarly other typings for BaseCache have wrong typings.

## What's wrong

```
foobar.py:688: error: "add" of "BaseCache" does not return a value
```

## How is that should be

Shouldn't raise any error. 

## System information

- `django` version: master branch
- `django-stubs` version: master branch

**Comment by sobolevn** [comment]
@Ashish-Bansal can you please send a fix? 🙂

**Comment by Ashish-Bansal** [comment]
@sobolevn Thanks for the quick response! I'll ship PR in few hours.
