### ISSUE TITLE
Missing decorator stubs

### ISSUE THREAD

**Issue by mattbasta** [typeddjango/django-stubs#37]
I'm seeing a lot of missing stubs errors for Django view decorators:

```
podcasts/views.py:12: error: No library stub file for module 'django.views.decorators.cache'
podcasts/views.py:13: error: No library stub file for module 'django.views.decorators.csrf'
podcasts/views.py:14: error: No library stub file for module 'django.views.decorators.gzip'
podcasts/views.py:15: error: No library stub file for module 'django.views.decorators.http'
```

I see the decorators in the `django-stubs` repo, and I'm running 0.8.0. Any idea why this might be happening?

**Comment by mkurnikov** [comment]
Thanks for the report! Fixed it in https://github.com/mkurnikov/django-stubs/commit/627daa55f5a95c4479e2aa5f2d08407a1031c8d2, seems that `__init__` file had leftover `.py` extension.
