### ISSUE TITLE
CharField with blank=True should not be considered nullable

### ISSUE THREAD

**Issue by Naddiseo** [typeddjango/django-stubs#38]
AFAIK, `CharField(blank=True,...)` just means that the string can be 0-length, and doesn't mean that it's `Optional`/nullable. The documentation on [`blank`](https://docs.djangoproject.com/en/2.1/ref/models/fields/#blank) also seems to suggest this, saying that it "will allow the entry of an empty value", which for a string is just a 0-length string.

I think the offending code is [fields.py:105](
https://github.com/mkurnikov/django-stubs/blob/c962b8ac68856e5ff39748444c20d8fb99ab9f0b/mypy_django_plugin/transformers/fields.py#L105)

I can make a pull request to remove (or comment out) that block of code if needed

**Comment by mkurnikov** [comment]
It's fine to remove it. Thanks!
