### ISSUE TITLE
mypy@0.780 is out

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#388]
We need to test if everything works on this new version and update the dependency.

**Comment by sobolevn** [comment]
This is also outdated: https://github.com/typeddjango/django-stubs#version-compatibility

**Comment by jnoortheen** [comment]
when can we expect the PyPI release? 
![image](https://user-images.githubusercontent.com/6702219/85925567-cf516c80-b8b6-11ea-8133-4831042e2e29.png)

**Comment by autoferrit** [comment]
I am still getting this error. currently we are at `mypy=0.782`. Are there any chances of getting this updated?
