### ISSUE TITLE
Wrong supported python versions in PyPi metadata

### ISSUE THREAD

**Issue by AndreyMZ** [typeddjango/django-stubs#392]
According to [README](https://github.com/typeddjango/django-stubs/blob/54f5f63e719bb16bb51f19b20c5241227db7bc54/README.md#version-compatibility) and [the test configuration](https://github.com/typeddjango/django-stubs/blob/54f5f63e719bb16bb51f19b20c5241227db7bc54/.travis.yml#L8) it looks like django-stubs supports Python 3.8.

But [the metadata](https://github.com/typeddjango/django-stubs/blob/master/setup.py#L47-L48) of the [`django-stubs`](https://pypi.org/project/django-stubs/) project on PyPi differs.

## What's wrong

https://pypi.org/project/django-stubs/

> Programming Language
> * Python :: 3.6
> * Python :: 3.7

## How is that should be

> Programming Language
> * Python :: 3
> * Python :: 3.6
> * Python :: 3.7
> * Python :: 3.8

**Comment by sobolevn** [comment]
Thanks a lot for the report! Fixed in `master`.

python3.8 support was added several days ago: #379 
There was no release made since then.
