### ISSUE TITLE
Type of model is not model's class

### ISSUE THREAD

**Issue by phwh** [typeddjango/django-stubs#40]
First of all, django-stubs is an amazing project. I built some workarounds for typing Django myself but this project is so much more comprehensive and better. So thank you very much for your work!

However, I have run into my first issue:

For the following code

```python
class Comment(models.Model):
    # fields
    pass

class OtherModel(models.Model):
    comments = GenericRelation(Comment)
```

mypy complains with the following error message:

```
error: Argument 1 to "GenericRelation" has incompatible type "Type[Comment]"; expected "Union[Type[Model], str]"
```

Expecting `Union[Type[Model], str]` is completely correct imho. But since `Comment` is a subclass of `Model` everything should be fine.

In order to find the underlying problem I inserted an `reveal_type(Comment)` call which gave me the following output:

```
Revealed type is 'def (**kwargs: Any) -> comments.models.Comment'
```

Maybe this is totally fine and due to the internals of the plugin. But I expected it to be `Type[Comment]` which could also be the reason why mypy doesn't recognize it as compatible to `Type[Model]`.

(What I don't understand is why mypy says `Type[Comment]` in the first error message which contradicts the 'revealed type' output)

**Comment by mkurnikov** [comment]
Technically, `Type[Comment]` is a callable, you can run `Comment(*args)` and it will return objects of type `Comment`, which is what mypy shows in the `reveal_type`. 

I tried to reproduce, but had no luck. Could you provide failing test case in the form of 
```
[CASE my_test_case]
class MyClass:
    def method(self) -> str:
        pass
reveal_type(MyClass().method())  # E: Revealed type is 'builtins.str'
[/CASE]
```

You can look at the plugin test suite for the format and examples
https://github.com/mkurnikov/django-stubs/tree/master/test-data/typecheck

**Comment by phwh** [comment]
Thanks, I will try to reproduce.

**Comment by phwh** [comment]
Couldn't reproduce. The test case I wrote didn't throw the error.

I probably have a Django model stub in a `pyi` file somewhere in my code that interfered with `mypy-stubs`.

Sorry for the false alarm and keep up the good work!
