### ISSUE TITLE
update_session_auth_hash() type doesn't match documentation and functionality

### ISSUE THREAD

**Issue by coiax** [typeddjango/django-stubs#400]
# Bug report

## What's wrong

The stub for update_session_auth_hash() is inaccurate, it asks for a WSGIRequest, when
the function itself expects a HttpRequest (with a .session attribute).

In the [documentation](https://docs.djangoproject.com/en/2.2/_modules/django/contrib/auth/#update_session_auth_hash), it is also passed a request.

## How is that should be

The stub should be:

```def update_session_auth_hash(request: HttpRequest, user: AbstractUser) -> None: ...```

## System information

- OS: Ubuntu 18.04
- `python` version: 3.8.3
- `django` version: 2.2.13
- `mypy` version: 0.750
- `django-stubs` version: 1.3.0

**Comment by Datamance** [comment]
The second type should actually be `AbstractBaseUser`...
