### ISSUE TITLE
"AbstractBaseUser" has no attribute "is_staff"

### ISSUE THREAD

**Issue by AdrienLemaire** [typeddjango/django-stubs#402]
# Bug report

## What's wrong
django-stubs incorrectly associates `HttpRequest.user` to AbstractBaseUser when my user extends AbstractUser.

## How is that should be
Given the `settings.py`:
```py
AUTH_USER_MODEL = "app.User"
```
and the `app/models.py`:
```py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    ...
```

When calling an AbstractUser property:
```py
    def get_context(self, request: HttpRequest) -> dict:
        context: dict = super().get_context(request)
        if not request.user.is_staff and request.user.has_perm("app.student"):
```
No type error should be raised, but I get:
```
[mypy error] [E] "AbstractBaseUser" has no attribute "is_staff"
```

I suppose the simplest of fixes would be to change https://github.com/typeddjango/django-stubs/blob/master/django-stubs/http/request.pyi#L55
```diff
- from django.contrib.auth.base_user import AbstractBaseUser
+ from django.contrib.auth.models import AbstractUser

-    user: Union[AbstractBaseUser, AnonymousUser]
+    user: Union[AbstractUser, AnonymousUser]
```

Since the definition of AbstractUser is
```py
class AbstractUser(AbstractBaseUser, PermissionsMixin):
```

## System information

- OS: Arch linux
- `python` version: 3.8.3
- `django` version: 3.0.7
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by AdrienLemaire** [comment]
Actually, the fix suggested won't do it. My custom user fields also raise issues, so django-stubs needs to do something like this:

```py
from django.contrib.auth import get_user_model

class HttpRequest(BytesIO):
    user: Union[get_user_model(), AnonymousUser]
```

**Comment by sobolevn** [comment]
Related to 
- https://github.com/typeddjango/django-stubs/issues/309
- https://github.com/typeddjango/django-stubs/pull/383

Can you guys please take a look? @kszmigiel @bullfest

**Comment by bullfest** [comment]
> Actually, the fix suggested won't do it. My custom user fields also raise issues, so django-stubs needs to do something like this:
> 
> ```python
> from django.contrib.auth import get_user_model
> 
> class HttpRequest(BytesIO):
>     user: Union[get_user_model(), AnonymousUser]
> ```

I won't be able to access a computer until monday, but I believe this is essentially what's being done (but in a more non-direct way by mypy-magic).

Have you added the plugin to the mypy configuration as instructed here? https://github.com/typeddjango/django-stubs#configuration

**Comment by AdrienLemaire** [comment]
Yes, here's my mypy.ini:
```ini
[mypy]
disallow_untyped_defs = True
ignore_missing_imports = True
follow_imports = skip
show_column_numbers = True
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "project.settings.dev"
```
Is there a way to confirm for sure that django-stubs are loaded by mypy? I'm pretty sure that it's loaded since the number of mypy errors skyrocketed after I installed it, but I might have misunderstood something

**Comment by kszmigiel** [comment]
@AdrienLemaire changing `follow_imports` to `normal` or `silent` should do the job
https://mypy.readthedocs.io/en/stable/running_mypy.html#follow-imports

**Comment by AdrienLemaire** [comment]
@kszmigiel seems to work. Having other request issues, but due to missing stubs for the wagtail framework. request.user looks fine, thanks!
