### ISSUE TITLE
 save incompatible with supertype "Model" 

### ISSUE THREAD

**Issue by AdrienLemaire** [typeddjango/django-stubs#404]
# Bug report

## What's wrong
mypy raises an error for the model save method defined as follow:

```py
class MyModel(models.Model):
    def save(self, *args: list, **kwargs: dict) -> None:
```

error: `[mypy error] [E] Signature of "save" incompatible with supertype "Model"`

## How is that should be
No error, or something more meaningful to help me fix my typing.

I can see the [model type definition here](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/base.pyi#L41), and my save method does look compatible with it.

## System information

- OS: Arch linux
- `python` version: 3.8.3
- `django` version: 3.0.7
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

Related to #402

**Comment by sobolevn** [comment]
Can you please try to use `def save(self, *args, **kwargs) -> None:`?
Because `def save(self, *args: list, **kwargs: dict) -> None:` is indeed incompatible.

**Comment by AdrienLemaire** [comment]
@sobolevn thanks for the reply.
In that case, mypy will still complain about missing type annotations
![](https://i.imgur.com/4kXh1S6.png)


It seems to be due to `disallow_untyped_defs = True`

Do you agree that replacing with the following should fixed the issue while keeping the mypy conf at a "strict" mode?

```
[mypy]
disallow_untyped_defs = False
warn_incomplete_stub = True
```
If yes, we can close the issue, thanks for you support :)

**Comment by sobolevn** [comment]
This happens because of `warn_incomplete_stub` AFAIK. I am not a big fan of this setting. I really recommend to turn it off.

**Comment by ghost** [comment]
On top of that: `*args` isn't a list and `**kwargs` isn't a dict: one should type 1 member, not the container. In most cases, this will mean to type them with Any. But in some cases, one can do better:

```python
def open_files(*args: Path): ...
def add_population_counts(**cities: int): ...
```
Ref: https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values

**Comment by AdrienLemaire** [comment]
Thanks
