### ISSUE TITLE
How to create chain of QuerySet methods?

### ISSUE THREAD

**Issue by b0g3r** [typeddjango/django-stubs#409]
For example we have manager generated from queryset:
```
class EntityQuerySet(models.QuerySet):
    def filter_foo():
        return self.filter(foo=True)
    def filter_bar(bar: str):
        return self.filter(bar=str)

EntityManager = models.Manager.from_queryset(EntityQuerySet)

class Entity(models.Model):
    foo = models.BooleanField()
    bar = models.TextField()

    objects = EntityManager()
```

Which type should I use for return value in filter_foo/filter_bar?

I tried `filter_foo() -> EntityQuerySet:`, but `reveal_type(Entity.objects.filter_foo().get())` returns 'Any :(

It looks like `models.Manager.from_queryset` did magic which I cannot reproduce in my typing. Any ideas?

**Comment by kszmigiel** [comment]
@b0g3r I'm working on fixing this under GSoC program, please be patient 😄

**Comment by flaeppe** [comment]
This is an example of how to add type hints, that should work

```python
class EntityQuerySet(models.QuerySet["Entity"]):
    def filter_foo(self) -> "EntityQuerySet":
        return self.filter(foo=True)

EntityManager = models.Manager.from_queryset(EntityQuerySet)

class Entity(models.Model):
    foo = models.BooleanField()
    bar = models.TextField()

    objects = EntityManager()
```
