### ISSUE TITLE
Bump max mypy version

### ISSUE THREAD

**Issue by mschoettle** [typeddjango/django-stubs#411]
I just updated `mypy` to `0.782` and got the following error:

> ERROR: django-stubs 1.5.0 has requirement mypy<0.780,>=0.770, but you'll have mypy 0.782 which is incompatible.

So far I have not encountered any issues despite this error (it still installed it regardless).

Can the max version requirement be safely increased?

**Comment by kszmigiel** [comment]
@mschoettle Mypy version in requirements was already bumped, but we haven't released 1.6.0 yet
@sobolevn I think updating Mypy requirement to 0.782 should do no harm, I've opened a PR, all tests are passing
