### ISSUE TITLE
ContentType issue

### ISSUE THREAD

**Issue by isac322** [typeddjango/django-stubs#428]
# Bug report

Error occurred while running mypy with django-stubs's mypy plugin.

#### Related code

```python
class Job(models.Model):
    uuid = models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)
    type = models.CharField(max_length=50)  # noqa: A003
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    unit_id = models.BigIntegerField(null=True)
    parent_job_uuid = models.UUIDField(null=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'job'

    @staticmethod
    def from_entity(job: entity.Job):
        return Job(
            uuid=job.uuid,
            type=job.job_type.value,
            start_date=job.start_date,
            end_date=job.end_date,
            unit_id=job.unit_id,
            parent_job_uuid=job.parent_job_uuid,
        )

```

#### Result of `mypy ./src`

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "mypy/checkexpr.py", line 3755, in accept
  File "mypy/checkexpr.py", line 263, in visit_call_expr
  File "mypy/checkexpr.py", line 340, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 817, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 876, in check_call
  File "mypy/checkexpr.py", line 988, in check_callable_call
  File "mypy/checkexpr.py", line 716, in apply_function_plugin
  File "/Users/.../venv/lib/python3.8/site-packages/mypy_django_plugin/transformers/init_create.py", line 62, in redefine_and_typecheck_model_init
    return typecheck_model_method(ctx, django_context, model_cls, '__init__')
  File "/Users/.../venv/lib/python3.8/site-packages/mypy_django_plugin/transformers/init_create.py", line 36, in typecheck_model_method
    expected_types = django_context.get_expected_types(typechecker_api, model_cls, method=method)
  File "/Users/.../venv/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 154, in get_expected_types
    from django.contrib.contenttypes.fields import GenericForeignKey
  File "/Users/.../venv/lib/python3.8/site-packages/django/contrib/contenttypes/fields.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/Users/.../venv/lib/python3.8/site-packages/django/contrib/contenttypes/models.py", line 133, in <module>
    class ContentType(models.Model):
  File "/Users/.../venv/lib/python3.8/site-packages/django/db/models/base.py", line 112, in __new__
    raise RuntimeError(
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
.../models.py:17: error: INTERNAL ERROR -- Please try using mypy master on Github:
```

FYI. Line `17` is `return Job(`

#### `mypy.ini`

```ini
[mypy]
python_version = 3.8

##

allow_redefinition = True

# Plugins

plugins = pydantic.mypy,mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = 'statsdjango.stats_django.settings'

[mypy-*.tests.*,tests.*]
ignore_errors = True

[mypy-*.migrations.*]
ignore_errors = True
```

---

Weird thing is... if I add to `INSTALLED_APPS` of my project's `settings.py` this error is gone.

## How is that should be

No error.

## System information

- OS: macOS Catalina
- `python` version: 3.8
- `django` version: 3.0.6
- `mypy` version: 0.782
- `django-stubs` version: master (https://github.com/typeddjango/django-stubs/commit/97ec2ee43b17bad55c68994c917321f5abdd1a0e)

**Comment by sobolevn** [comment]
That's not really an issue with `django-stubs`. We have to run `django.setup()` while typechecking your code.
And it fails, because there's something wrong with your setup.

The only thing we can do here is to improve our error messages: see https://github.com/typeddjango/django-stubs/pull/421

**Comment by sobolevn** [comment]
@kszmigiel will you please have a look?

**Comment by isac322** [comment]
@sobolevn I have empty `INSTALLED_APPS` and there's no usage of `ContentType` nor `django.contrib.contenttypes`.
but I found [this line](https://github.com/typeddjango/django-stubs/blob/97ec2ee43b17bad55c68994c917321f5abdd1a0e/mypy_django_plugin/django/context.py#L154) (which import `ContentType` internally) in `mypy_django_plugin`. Could this be the cause?

**Comment by sobolevn** [comment]
Yes. It can be.

We should make this optional.

**Comment by snejus** [comment]
@isac322, could you confirm that your application is configured by including line `default_app_config = <path to apps.py>` to `<app-root-path>/__init__.py`? Starting with Django 2, they started discouraging this type of configuration and advise including the dotted path to `INSTALLED_APPS` instead, [see more background here](https://docs.djangoproject.com/en/2.2/ref/applications/#configuring-applications). 

I'll look into whether this can be handled though.

**Comment by lysnikolaou** [comment]
Hey everyone and thanks for the awesome work! :rocket: 

FWIW we're also facing this problem and we'd like to see it fixed. After an initial investigation, there's also a dependency on `django.contrib.auth` with the imports [here](https://github.com/typeddjango/django-stubs/blob/16326e999c6cc1b2bda1155c36b57c729eef5b05/mypy_django_plugin/transformers/request.py#L16). If these could be made optional, that would be awesome.

I'd certainly be up to help out with a PR, but I'd need some guidance, since some changes I did to remove these dependencies, led to a huge amount of errors due to `request.user` not being correctly typed.
