### ISSUE TITLE
models values_list unexpected type warning

### ISSUE THREAD

**Issue by A-Iskakov** [typeddjango/django-stubs#43]
using values_list() on django models gets unexpected type(s) warning

**Comment by mkurnikov** [comment]
More details?

**Comment by mkurnikov** [comment]
cc @syastrov

**Comment by A-Iskakov** [comment]
![image](https://user-images.githubusercontent.com/26543542/54091628-73569200-43ac-11e9-9bf9-67061db2b8d2.png)

**Comment by mkurnikov** [comment]
What about mypy, does it show any errors? mypy output is a reference for this project, pycharm can have it's own bugs.

**Comment by syastrov** [comment]
I think it is due to use of Literal types, which is a mypy extension and also highly experimental according to their docs.
In the interest of compatibility, and because we will probably make values_list smarter in the future, I will make a PR to implement the different return types dependent on parameters in the plugin instead.

**Comment by syastrov** [comment]
There are Literal types used in a few other places in the stubs, so not sure if we should do something about that. It would be nice to keep the stubs clean of mypy-specific stuff, so they are as generally-useful as possible.

If we don't want to make special-cases in the plugin, then we could solve these cases by making a condition in the stubs, something like:
```
if MYPY:
    class _SupportsValuesList(Generic[_T]):
        ... # mypy-specific values_list function overloads using Literal types
else:
    class _SupportsValuesList(Generic[_T]):
        ... # values_list function that would be used by other type-checkers (e.g. PyCharm) and would return a QuerySet[_T, Any]

class QuerySet(..., _SupportsValuesList[_T]):
    ...
```
