### ISSUE TITLE
Module 'django.conf.urls' has no attribute 're_path'mypy

### ISSUE THREAD

**Issue by jaredlockhart** [typeddjango/django-stubs#430]
# Bug report

## What's wrong

`Module 'django.conf.urls' has no attribute 're_path' mypy(error)`

## How is that should be

`re_path` is defined here:

https://github.com/django/django/blob/3.0.7/django/urls/__init__.py#L6
https://github.com/django/django/blob/3.0.7/django/urls/conf.py#L77

and appears here in the typestubs:

https://github.com/typeddjango/django-stubs/blob/v1.5.0/django-stubs/urls/__init__.pyi#L17
https://github.com/typeddjango/django-stubs/blob/v1.5.0/django-stubs/urls/conf.pyi#L8

so it seems that mypy should not be complaining about it?

## System information

- OS: MacOS 10.15.3
- `python` version: 3.8.2
- `django` version: Django==3.0.7
- `mypy` version: mypy==0.770
- `django-stubs` version: django-stubs==1.5.0

**Comment by sobolevn** [comment]
@jaredlockhart thanks a lot! PR is welcome!

**Comment by syastrov** [comment]
You didn't  provide the code that fails, but it looks like you tried importing it from `django.conf.urls` when it should be from `django.urls.conf` :)
So it doesn't seem to be a bug, as far as I can tell.

(As a side note, it would be nice to have a better type for `path`/`re_path` than `Any`... but that's another story).

**Comment by sobolevn** [comment]
I am going to close this due to the reason @syastrov provided. Feel free to reopen if that does not solve your problem.
