### ISSUE TITLE
Incorrect type annotation for update_fields parameter to Model.save

### ISSUE THREAD

**Issue by ljodal** [typeddjango/django-stubs#434]
# Bug report

## What's wrong

Hi there, it looks like the type annotation for the `update_fields` parameter to `Model.save` and `Model.save_base` is incorrect. It's currently typed as `Optional[Union[Sequence[str], str]]` which indicates that a single string can be sent as an argument, but it doesn't look like Django actually supports that. If `update_fields` is not `None`, Django calls `frozenset(update_fields)` which in the case of a single string being submitted will result in a set of one-character strings for each character in the initial string.

The relevant type annotations are here:
https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/base.pyi#L41-L55

The relevant Django code is here:
https://github.com/django/django/blob/stable/3.0.x/django/db/models/base.py#L717

## How is that should be

I think that the correct type for the `update_fields` parameter should be `Optional[Iterable[str]]`. As mentioned above Django passes the value to `frozenset()`, which accepts any `Iterable`, not just `Sequence`.

I realize that this doesn't make much of a difference, as `str` is an `Iterable[str]` so you're allowed to make an invalid call either way, but I think it would be good to have a type annotation that doesn't mislead people into thinking they can pass a single `str` as `update_fields`.

Is there a specific reason why it's typed like this or should I submit a PR to update the type annotation?

## System information

- OS: macOS 10.15.6
- `python` version: `3.7.8`
- `django` version: `3.0.8`
- `mypy` version: `0.770`
- `django-stubs` version: `1.5.0`

**Comment by sobolevn** [comment]
@ljodal PR is more than welcome!
