### ISSUE TITLE
GSoC 2020 Summary

### ISSUE THREAD

**Issue by kszmigiel** [typeddjango/django-stubs#450]
Here's a list of issues I've managed to solve during GSoC 2020, and list of accepted pull requests authored by me. The biggest part of my work (Mypy plugin refactoring) was done in pull request #427, and I continue my work on this at pull request #445 to apply my changes to master branch.

There are few things that needs polishing, at this moment I'm working on passing the CI tests. After that I plan to continue my work on Django Stubs:

- There's a plan to introduce versioning of stubs for different versions of Django Framework.
- There are issues with how the plugin work, causing some minor errors.
- Documentation both for users and contributors needs improvement.

I'd like to thank everyone involved in my GSoC project, especially @sobolevn and @mkurnikov 🙏

Issues solved:
#423 
#388 
#382 
#379 
#378 
#373 

Merged pull requests:
#376 
#384 
#387 
#390 
#391 
#396 
#414 
#424
#427 
#429 

Work in progress pull requests:
#445 
#439

**Comment by sobolevn** [comment]
We can also count #439 as WIP, because we have spent a significant time discussing it.

**Comment by sobolevn** [comment]
This might be closed, I guess.

**Comment by drs12345-SS** [comment]
hey can anyone please tell me about the overview of this project so that i could make out that what it's all about.

**Comment by sobolevn** [comment]
@drs12345-SS which project exactly? 🙂

**Comment by drs12345-SS** [comment]
@sobolevn just want to know  about the project of 2020 on which you people were working but also can you please suggest me some good projects on django to start with

**Comment by sobolevn** [comment]
@drs12345-SS

> just want to know about the project of 2020 on which you people were working

Here you go:
https://summerofcode.withgoogle.com/archive/2020/organizations/5420240042721280/

> but also can you please suggest me some good projects on django to start with

You can check out my repo: https://github.com/wemake-services/wemake-django-template/
It has lots of best practices.
