### ISSUE TITLE
Pleas bump supported mypy versions

### ISSUE THREAD

**Issue by canassa** [typeddjango/django-stubs#463]
Hi,

I am happily using mypy 782 and django-stubs 1.5.0 in all my projects for quite some time without any problem whatsoever. django-stubs 1.5.0 does not allows for mypy 782, but they work fine and I just ignore the pip warning during the installation.

The problem is that they are updating pip/setuptools in a few days. They are adding this "feature" that resolves dependency conflicts:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
django-stubs 1.5.0 requires mypy<0.780,>=0.770, but you'll have mypy 0.782 which is incompatible.
```

This means that in a couple of days any project using the latest django-stub and mypy will break.

**Comment by sobolevn** [comment]
Oh shiiiii 😨

**Comment by kszmigiel** [comment]
@sobolevn I guess in this situation we have to give up on waiting for refactor to be finished, and release 1.6.0 (or 1.5.1) version of django-stubs asap. We have `'mypy>=0.782,<0.790'` dependency in `setup.py` on current master branch, so it should do the job.

**Comment by sobolevn** [comment]
Agreed 👍 

@kszmigiel I can do the release right now. Let's do it?

**Comment by kszmigiel** [comment]
@sobolevn sure, push the button! 😁
Sorry for the delay, I was afk today.

**Comment by garanews** [comment]
can you update also on pypi?

**Comment by gghildyal** [comment]
As @garanews says, PyPi still depends on the older mypy version. Can you  push the latest package to mypy as well please?

**Comment by sobolevn** [comment]
https://pypi.org/project/django-stubs/1.6.0/
