### ISSUE TITLE
Type check model definitions?

### ISSUE THREAD

**Issue by caseydm** [typeddjango/django-stubs#465]
I'm working on type checking a Django project. Do you guys annotate your models? For example like this:

```
MyModel(models.model)
    description: Optional[str] = models.TextField(null=True)
```

When I run that with mypy I get the error: `error: Incompatible types in assignment (expression has type "TextField[Union[str, Combinable, None], Optional[str]]", variable has type "Optional[str]")`

But I was thinking about it and since django-stubs is converting it to the right type, I don't think there is a need to add a type when defining the model. For example when I do this:

```
MyModel(models.model)
    description: Optional[str] = models.TextField(null=True)
    
    def __str__(self) -> str:
        reveal_type(self.description)
```

The response is:  `note: Revealed type is 'Union[builtins.str, None]'` So this means I should just delete the Optional[str] in the model, and know that when I refer to that field elsewhere in the project, the type is reflected properly. Do I understand this correctly?

**Comment by sobolevn** [comment]
Yes, there's no need to annotate your models.

**Comment by sobolevn** [comment]
Moreover, it is not recommended. 

Because when you define a model, you use `Field`-based types to declare fields of your model.
Then, we use these types to infer the attributes of your model instances.
