### ISSUE TITLE
Over-specific return type required for `ListView.get_queryset` overrides

### ISSUE THREAD

**Issue by vgel** [typeddjango/django-stubs#477]
# Bug report

## What's wrong

Right now `django-stubs` requires that the return type of a `views.generic.ListView` subclass' `get_queryset` method be a queryset, which seems reasonable. However, `django` doesn't actually require that, and this bit me while adding typing to a project that uses a non-queryset iterable in a view.

See here:
https://github.com/django/django/blob/f87b0ecd37e64e7a019d472de37d0789a8790f1f/django/views/generic/list.py#L21

> The return value *must* be an iterable and *may* be an instance of `QuerySet` in which case `QuerySet` specific behavior will be enabled. (emphasis mine)

V.s. here:

https://github.com/typeddjango/django-stubs/blob/a8fdd4c67350eea564b7728beae1a87e26b274d2/django-stubs/views/generic/list.pyi#L20

Repro case:
```python
from typing import Iterable, Any
from django.views import generic

class TestcaseView(generic.ListView):
    def get_queryset(self) -> Iterable[Any]:
        return [1, 2, 3]
```

Message:
```
Return type "Iterable[Any]" of "get_queryset" incompatible with return type "QuerySet[Any]" in supertype "MultipleObjectMixin"
```

This issue might also affect other view methods -- for example it seems `DetailView` also is required to require a `QuerySet` right now: https://github.com/typeddjango/django-stubs/blob/a8fdd4c67350eea564b7728beae1a87e26b274d2/django-stubs/views/generic/detail.pyi#L17 , but I haven't tested whether django agrees with that restriction.

## System information

- OS: Linux marina 5.4.0-7634-generic #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC  x86_64 x86_64 x86_64 GNU/Linux
- `python` version: 3.8.2
- `django` version: 3.1.2
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

I can submit a pull for this if there's interest.

**Comment by LucidDan** [comment]
PR #897 seems to be aimed at changing this but isn't linked to the issue.

One concern I have - if this is changed to an Iterable[T] or even Union[Iterable[T], QuerySet[T]], suddenly anyone relying on the Django default CBV behaviour, which is that it WILL always be a QuerySet will need to start doing an isinstance() check before using queryset methods, or they'll get type errors; e.g
```
qs = get_queryset()
ids = qs.values_list("id") if isinstance(QuerySet, qs) else [obj.id for obj in qs]
```

But if you are just using the standard CBV classes, the isinstance check should be unnecessary, it will always be a queryset.

Is there a better solution?

**Comment by flaeppe** [comment]
With the changes in #2191 and the argument in #2174 in mind, I will close this as a won't fix. Since it's totally fair that `get_queryset` returns a `QuerySet`
