### ISSUE TITLE
DateField and TimeField stubs missing auto_now_add and auto_now

### ISSUE THREAD

**Issue by BurningLights** [typeddjango/django-stubs#479]
# Bug report

The type stubs for DateField and TimeField are missing the attributes auto_now_add and auto_now. This also effects DateTimeField, which inherits from DateField.

## What's wrong

The attribute definitions of DateField looks like:
```
class DateField(DateTimeCheckMixin, Field[_ST, _GT]):
    _pyi_private_set_type: Union[str, date, Combinable]
    _pyi_private_get_type: date
    _pyi_lookup_exact_type: Union[str, date]
```

and the attribute definitions of TimeField looks like:
```
class TimeField(DateTimeCheckMixin, Field[_ST, _GT]):
    _pyi_private_set_type: Union[str, time, datetime, Combinable]
    _pyi_private_get_type: time
```

## How is that should be

The definitions should look like:
```
class DateField(DateTimeCheckMixin, Field[_ST, _GT]):
    _pyi_private_set_type: Union[str, date, Combinable]
    _pyi_private_get_type: date
    _pyi_lookup_exact_type: Union[str, date]

    auto_now: bool
    auto_now_add: bool
```

and for TimeField:
```
class TimeField(DateTimeCheckMixin, Field[_ST, _GT]):
    _pyi_private_set_type: Union[str, time, datetime, Combinable]
    _pyi_private_get_type: time

    auto_now: bool
    auto_now_add: bool
```

## System information

- OS: Windows 10 build 18363.1082
- `python` version: Python 3.8.0
- `mypy` version: 0.782
- `django` version: 3.0.9
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
@BurningLights PRs are welcome! Btw, we participate in Hacktoberfest! 🎃

**Comment by adamchainz** [comment]
Thanks @BurningLights , I’ve turned your suggestions into a co-authored PR: #1210.
