### ISSUE TITLE
BaseModelAdmin should be a generic class

### ISSUE THREAD

**Issue by fancysnake** [typeddjango/django-stubs#482]
# Bug report

## What's wrong

I have a class inheriting from `BaseModelAdmin` and a method `delete_model` defined as such:
```python
def delete_model(self, request: HttpRequest, obj: AgendaItem) -> None:
```
`AgendaItem` is a Django model

However, mypy raises an error:

```
app/chronology/admin.py: note: In member "delete_model" of class "AgendaItemAdmin":
app/chronology/admin.py:376: error: Argument 2 of "delete_model" is
incompatible with supertype "ModelAdmin"; supertype defines the argument type as
"Model"  [override]
        def delete_model(self, request: HttpRequest, obj: AgendaItem) -> N...
        ^
```

because in stubs this function is defined as:

```python
def delete_model(self, request: HttpRequest, obj: Model) -> None: ...
```

## How is that should be

The solution is to make `BaseModelAdmin` a generic class with model type variable.

## System information

- OS: ArchLinux
- `python` version: 3.8.6
- `django` version: 3.1.2
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
@radowit do you want to work on this?

**Comment by vgel** [comment]
I can take a shot at this!

**Comment by sobolevn** [comment]
@vgel awesome! Please, feel free to do so!

**Comment by vgel** [comment]
Unfortunately I've been really busy at work and don't think I can do this
task at the moment. I'll try to come back to it later, but in the meantime
if someone else wants to pick it up please feel free. Sorry!
