### ISSUE TITLE
Function is untyped after decorator transformation

### ISSUE THREAD

**Issue by fancysnake** [typeddjango/django-stubs#483]
# Bug report

## What's wrong

I have an inclusion tag defined using a decorator:

```python
@register.inclusion_tag("admin/widgets/related_widget_wrapper.html")
def agenda_cell(
    room: Room, hour: datetime, agenda_item: Optional[AgendaItem] = None
) -> AgendaCellContext:
    ...
```

Mypy gives me here this error:

```
app/chronology/templatetags/agenda.py:34: error: Function is untyped after
decorator transformation  [misc]
    def agenda_cell(
    ^
```

suggesting that `inclusion_tag` returns an untyped function.

## How is that should be

`inclusion_tag` and other templatetag decorators should return the function of the same types.
e.g. using typevars

## System information

- OS: ArchLinux
- `python` version: 3.8.6
- `django` version: 3.1.2
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
Yes, PRs are welcome! 🙏
