### ISSUE TITLE
No compatibility with the new version of mypy

### ISSUE THREAD

**Issue by oladhari** [typeddjango/django-stubs#486]
# Bug report

## What's wrong

After updating mypy to the newest version I got this Error message:
```console
django-stubs 1.6.0 requires mypy<0.790,>=0.782, but you'll have mypy 0.790 which is incompatible.
```

## How is that should be

could you please update django-stubs so it can be compatible with the new version of mypy, thank you

## System information

- OS: ubuntu 20.04
- `python` version: 3.8
- `django` version: 3.1.2
- `mypy` version: 0.790
- `django-stubs` version: 1.6.0

**Comment by michael-k** [comment]
This has been fixed in #501 which is part of release 1.8.0. This issue can be closed.
