### ISSUE TITLE
Projects with no models.py suddenly seem to have missing related fields

### ISSUE THREAD

**Issue by palfrey** [typeddjango/django-stubs#488]
# Bug report

## What's wrong

I've got a project where we've just moved over from having a models.py to splitting out all of the models and their related views, etc into feature-specific files. The project was getting 0 errors from mypy before this, but then suddenly had issues like a model using the default primary key having errors like `has no attribute "id"` and others now missing various related fields.

Notably, the project still works absolutely fine and all the fields, etc are present in the running system.

I've managed to hack around this by making a models.py that imports all the submodules, but I was surprised about this.

## How is that should be

I shouldn't have needed the hack. Or the Django stubs should have complained about this, as it took me most of a day to work out what the problem was...

## System information

- OS:
- `python` version: 3.7.7
- `django` version: 3.0.7
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

**Comment by Goldziher** [comment]
thanks for reporting the issue. 

Can you explain what you mean by "other issues like missing related fields"? I mean actual code / complaint would be helpful.

**Comment by palfrey** [comment]
I can't provide code directly as it's a private project, but the other errors were all things like mypy complaining that class X didn't have field Y, when field Y exists because class Z has a ForeignKey referencing class X. Even when I imported class Z into the file where the error was, it didn't go away.

**Comment by flaeppe** [comment]
I'm closing this off as we'll need more information. Feel free to reopen with a breaking case.
