### ISSUE TITLE
the type signature of AbstractBaseUser.set_password is incorrect

### ISSUE THREAD

**Issue by ghost** [typeddjango/django-stubs#492]
# bug report

## what's wrong

the type signature for `AbstractBaseUser.set_password` is `def set_password(self, raw_password: Optional[str]) -> None` when `raw_password` is actually a required argument (at least in django 2.2.16 and 3.0.7)

## how is that should be

raw_password should be marked as `str`

## system information

- OS: fedora 32
- `python` version: 3.8.6
- `django` version: i've checked 3.0.7 and 2.2.16
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by kalekseev** [comment]
Actually the signature were correct, see https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.set_password you can pass None as password to make it unusable. @sobolevn please revert.

**Comment by ghost** [comment]
@kalekseev thanks for correcting this, sorry i missed it!
