### ISSUE TITLE
django.contrib.auth.login should accept Optional[AbstractBaseUser] as second argument

### ISSUE THREAD

**Issue by giladsheffer** [typeddjango/django-stubs#495]
# Bug report

## What's wrong

Django project's `login` function handles None as second argument- https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L87

However, the stubs only accept `AbstractBaseUser`

## How is that should be

https://github.com/typeddjango/django-stubs/blob/8729a74f8141e24ca630507e4271f984a91a53d2/django-stubs/contrib/auth/__init__.pyi#L26 Should accept `Optional[AbstractBaseUser]` as second argument

## System information

- OS:
- `django` version: 3.1.2
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
PRs are welcome!

**Comment by giladsheffer** [comment]
> PRs are welcome!

Opened one :)
