### ISSUE TITLE
🧵 False positive for strings used in models.functions.Replace

### ISSUE THREAD

**Issue by coiax** [typeddjango/django-stubs#503]
# Bug report

## What's wrong

The stub for `django.db.models.functions.Replace`  is too restrictive, and doesn't permit strings to be used as
an argument, while in reality and in the [Django docs](https://docs.djangoproject.com/en/3.1/ref/models/database-functions/#replace), strings are allowed.

```python

from django.db.models import Value
from django.db.models.functions import Replace

expression = Replace("sketch", Value("spam"), Value("ham"))
# error: Argument 1 to "Replace" has incompatible type "str"; expected "Combinable"  [arg-type]
```

## How is that should be

It should not cause any problems. The expression above should cause no type errors, as it is a perfectly acceptable way of calling the function.

## System information

- OS:
- `python` version: Python 3.8.5
- `django` version: 3.0.10
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

**Comment by MarcinWieczorek** [comment]
It was introduced in fa718b8e55e4ac74b309b0068eeced6f89f48728. I don't know what a `Combinable` is, could you confirm that this is indeed a good type but it's too broad? Should it just be an union with str?

**Comment by sobolevn** [comment]
PRs are welcome!
