### ISSUE TITLE
InlineModelAdmin: Wrong type for formset?

### ISSUE THREAD

**Issue by Eboreg** [typeddjango/django-stubs#519]
# Bug report

## What's wrong

My code:

```python
class StudentInlineFormSet(forms.BaseInlineFormSet):
    [...]

class StudentInline(admin.TabularInline):
    formset = StudentInlineFormSet
    [...]
```

On this, mypy reports error: `Incompatible types in assignment (expression has type "Type[StudentInlineFormSet]", base class "InlineModelAdmin" defined the type as "BaseFormSet")  [assignment]`. And yes, in the stub file `options.pyi` is says `formset: BaseFormSet = ...`. But in the actual `InlineModelAdmin`, `formset` is defined as `BaseInlineFormSet`. So surely, the stub should define it as `Type[BaseInlineFormSet]` (or `Type[BaseFormSet]`) instead?

## System information

- OS: Ubuntu 20.04.1
- `python` version: 3.8.5
- `django` version: 2.2.16
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
PRs are welcome!

**Comment by Eboreg** [comment]
@sobolevn I'm not very used to contributing to other people's projects, but OK: https://github.com/typeddjango/django-stubs/pull/521
