### ISSUE TITLE
Catch type error on django models

### ISSUE THREAD

**Issue by ivanrvpereira** [typeddjango/django-stubs#52]
It is possible to have type errors for django models?

```python
class A(models.Model):
    pass

class B(models.Model):
    pass

def service(a: A) -> int:
    pass

a_instance = A()
b_instance = B()
service(b)  # no type error
```

It would help a lot if this could be caught earlier on the editor.
Because all models inherit from `models.Model` and 

> Every class is also a valid type. Any instance of a subclass is also compatible with all superclasses

I' m trying to figure if there is an option to detect this errors.

**Comment by syastrov** [comment]
Looks like a bug caused by setting fallback_to_any to True on the Model type in the plugin.
I will make a PR with a fix.
