### ISSUE TITLE
[request] push a release of django_stubs_ext to pypi

### ISSUE THREAD

**Issue by ghost** [typeddjango/django-stubs#528]
pip can install subdirectory packages just fine, but poetry currently can't (https://github.com/python-poetry/poetry/pull/1822); that means poetry users are absolutely unable to use django-stubs at all right now, since django-stubs relies on django_stubs_ext which is completely uninstallable

for now, i've split it out into a mirror (https://github.com/3n-k1/django-stubs-ext), but that's just a workaround until the release gets pushed. since django-stubs depends on it now, i think a release should be pushed asap

**Comment by sobolevn** [comment]
Thanks for the report! Will do today 👍

**Comment by ghost** [comment]
awesome, thanks!

**Comment by sobolevn** [comment]
Done! https://pypi.org/project/django-stubs-ext/0.1.0/

**Comment by ghost** [comment]
fantastic, thank you!

**Comment by sobolevn** [comment]
Please, report back if something is wrong!

Btw, you might be interested in this task to contribute: https://github.com/wemake-services/wemake-django-template/issues/1375 ⭐

**Comment by ghost** [comment]
getting poetry to use it over the one that was installed from my mirror was a bit of a hassle, but i ended up just re-creating the virtualenv and it installs and runs fine. there's some weirdness with where to add the monkeypatch calls, and i ended up having to write a mypy plugin for flycheck in emacs, but other than that it's good. when i get all the kinks worked out on my end, i'll send a pr with some qol and documentation fixes

thanks for the link, i'll check it out!
