### ISSUE TITLE
Async test related classes are missing [Django 3.1.x]

### ISSUE THREAD

**Issue by WisdomPill** [typeddjango/django-stubs#539]
# Bug report

From django 3.1.x async tests are available but are missing in django-stubs so IDEs complain

## What's wrong

All the async test related classes are missing, for example `async_client_class` in `django.test.testcase.SimpleTestCase`,
`AsyncClient` in `django.test.client` and so on.

## How is that should be

Support for async tests should be added

**Comment by adamchainz** [comment]
`async_client_class` and `AsyncClient` were added in #909.

**Comment by WisdomPill** [comment]
thanks!
