### ISSUE TITLE
Missing stub for classproperty

### ISSUE THREAD

**Issue by jsatt** [typeddjango/django-stubs#540]
# Missing Stub

The classproperty decorator was made public in Django 3.1 (django.utils.functional), but the stub for this decorator in missing.

## System information

- OS:
- `python` version: 3.8
- `django` version: 3.1
- `mypy` version: 0.770
- `django-stubs` version: 1.7.0

**Comment by mkurnikov** [comment]
Fixed in https://github.com/typeddjango/django-stubs/commit/11c3f8cd11a33a4e16ab207bb835285de5d7ed29
