### ISSUE TITLE
TypeError: object is not subscriptable, with django_stubs_ext

### ISSUE THREAD

**Issue by markedwards** [typeddjango/django-stubs#544]
# Bug report

I'm attempting to implement django_stubs_ext, but I still get a `TypeError` when adding a type parameter to a class that ought to be supported.

## What's wrong

I have installed django_stubs_ext, and added `django_stubs_ext.monkeypatch()` to manage.py, asgi.py, and wsgi.py.  However, I still get `TypeError: ... object is not subscriptable` when trying to add type parameters.

Example:

```
class Test(ModelAdmin[Project]):
    pass
```

This results in: `TypeError: 'MediaDefiningClass' object is not subscriptable`.

The error only manifests when I execute `mypy` from the command line.  My Django application runs fine, and I see that I can do `ModelAdmin[Project]` from inside a django shell.  So it just appears that the monkeypatch doesn't get applied when mypy runs from the command line.

## How is that should be

Maybe I misunderstand something, but shouldn't the above work?

## System information

- OS: Debian
- `python` version: 3.8.6
- `django` version: 3.1.4
- `mypy` version: 0.790
- `django-stubs` version: 1.7.0
- `django-stubs-ext` version: 0.1.0

**Comment by sobolevn** [comment]
Try this approach: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/__init__.py#L19

Basically, use `django_stubs_ext.monkeypatch()` in your settings.

**Comment by markedwards** [comment]
Yes, that works.  Does this eliminate the need to put the `monkeypatch()` call in manage.py, asgi.py, and wsgi.py?

**Comment by sobolevn** [comment]
Yes! 👍 

Thanks for the report. Do you wish to contribute to the docs?

**Comment by markedwards** [comment]
Yep, I will make a PR.  Thanks for the help!
