### ISSUE TITLE
False positive type failure in PasswordResetForm

### ISSUE THREAD

**Issue by coiax** [typeddjango/django-stubs#552]
# Bug report

## What's wrong

False positive type failure in PasswordResetForm:

> error: Argument "request" to "save" of "PasswordResetForm" has incompatible type "HttpRequest"; expected "Optional[WSGIRequest]"

```python
from django.contrib.auth.forms import PasswordResetForm
from django.http import HttpRequest
request = HttpRequest()

form = PasswordResetForm()
form.save(request=request)  # complains about incompatible type.
```

## How is that should be

No error should be thrown in mypy, as the code as written works fine.

## System information

- OS: Ubuntu 20.04
- `python` version: 3.8.5
- `django` version: 3.0.11
- `mypy` version: 0.782
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
@coiax PR with the fix is welcome 👍
