### ISSUE TITLE
Request user is typed wrongly (AbstractBaseUser vs myapp.User)

### ISSUE THREAD

**Issue by Uninen** [typeddjango/django-stubs#561]
# Bug report

## What's wrong

Not sure if this an actual bug or a configuration issue but I have a Django view function with following code:

```
if request.user.is_authenticated:
    return JsonResponse(
        {
            "user": {
                "uid": request.user.uid,
                "username": request.user.username,
                "email": request.user.email,
            }
        }
    )
```

MyPy reports request user as `Union[AbstractBaseUser, AnonymousUser]` instead of `Union[User, AnonymousUser]` that it actually is. I learned that I can work around this by casting ( `user = cast(User, request.user`) ) but that's obviously not optimal.

Settings have `AUTH_USER_MODEL = "dolores.User"` and dolores.User looks like `class User(AbstractUser): ...`

(The other issue that I'm not sure if MyPy can even handle currently is that `is_authenticated` should narrow the type as now the object cannot be AnonymousUser anymore. Anyway, that's another issue.)

## How is that should be

`request.user` should match `settings.`AUTH_USER_MODEL`

## System information

- OS: macOS 10.15
- `python` version: 3.8
- `django` version: 3.1
- `mypy` version: 0.800
- `django-stubs` version: 1.7

(Editor: latest stable VSCode.)

**Comment by supadrupa** [comment]
https://github.com/typeddjango/django-stubs#how-can-i-create-a-httprequest-thats-guaranteed-to-have-an-authenticated-user

**Comment by Uninen** [comment]
Thanks, I missed that 👍 

I still think there's a bug -- or at least a documentation issue -- in the resolving of the user type which should be `AUTH_USER_MODEL` according to the docs. In my case the `AUTH_USER_MODEL = "dolores.User"` but the resolved type is `Union[AbstractBaseUser, AnonymousUser]`.

Still, there is a workaround so closing this for now.

**Comment by samuel-andres** [comment]
how did you solved it @Uninen? 
I'm getting the error here:

```
 class UserViewSet(viewsets.ModelViewSet):
      queryset = get_user_model().objects.all()
      serializer_class = UserSerializer

      def get_queryset(self) -> QuerySet:
          queryset = super().get_queryset()
          if self.request.user.is_verified:  # here resolves to Union[AbstractBaseUser, AnonymousUser]
              return queryset
          return queryset.filter(id=self.request.user.pk)

```
