### ISSUE TITLE
Module has no attribute errors

### ISSUE THREAD

**Issue by jpetuchovas** [typeddjango/django-stubs#562]
# Bug report

## What's wrong

In a Django app, I have a directory `models` that have various Python modules used to define Django models and an `__init__.py` file:

```
models
    __init__.py
	user.py
	...
```

The `__init__.py` file imports Django models from other files in the `models` directory:

```python
from project_name.core.models.users import User
```

To import the `User` model in this case, the following import is then used:

```python
from project_name.core.models import User
```

However, after installing `django-stubs`, I get a lot of errors that the Django models cannot be found in the `models` package when running mypy:

```
Module has no attribute "User"
```

I‘ve tried defining `__all__` in the `__init__.py` file, setting `implicit_reexport` to `True`, and importing the models in the `__init__.py` like so:

```python
from project_name.core.models.users import User as User
```

However, it does not help.

Using a full-path import works without errors:

```python
from project_name.core.models.users import User
```

I am not sure if it’s a bug or am I overlooking something?

## How is that should be

The “Module has no attribute” bugs should not be shown.

## System information

- OS: macOS Big Sur 11.2
- `python` version: 3.6.7
- `django` version: 3.1.1
- `mypy` version: 0.790
- `django-stubs` version: 1.7.0

**Comment by sobolevn** [comment]
Can you please attach a reproduction repo / file?

**Comment by jpetuchovas** [comment]
Sorry for taking a while to respond. I tried to reproduce the problem on a fresh Django project and couldn’t. Unfortunately, the repository in which the problem occurs is private, so I cannot share it.

If you have any ideas about how to debug the problem more easily or if there are some configuration options I might be overlooking, I would appreciate the help.

**Comment by sobolevn** [comment]
> If you have any ideas about how to debug the problem more easily or if there are some configuration options I might be overlooking

Not really 😞 

Let's put it this way: I am going to close this issue for now, feel free to reopen it if you face it again 👍
