### ISSUE TITLE
"headers" missing from http.HttpResponseBase stub?

### ISSUE THREAD

**Issue by ChasNelson1990** [typeddjango/django-stubs#563]
# Bug report

## What's wrong

https://github.com/typeddjango/django-stubs/blob/8f9e77ce39cb581ca220fb6f91197885e462a7c4/django-stubs/http/response.pyi#L21 defines the types for the http.HttpResponseBase class; however, it seems to be missing the 'headers' parameters, as defined in: https://github.com/django/django/blob/50a5f8840fa564dcefdb1fa5c58f06fcd472ee70/django/http/response.py#L99

This is causing me problems in typing my own project but I'm new to mypy so happy to have any misconceptions on my side corrected.

## How is that should be

I believe headers should be `Optional[Dict(str, str)]`?

## System information

- OS: Arch Linux
- `python` version: 3.8
- `django` version: 2.2.13
- `mypy` version: 0.780
- `django-stubs` version: 1.6.0

**Comment by sobolevn** [comment]
@ChasNelson1990 PRs are welcome! 👍

**Comment by ChasNelson1990** [comment]
Hope that's okay @sobolevn
