### ISSUE TITLE
"_meta" field missing in ModelBase

### ISSUE THREAD

**Issue by gustavoaca1997** [typeddjango/django-stubs#574]
# Bug report

## What's wrong
I am trying to access to the `_meta` field of a `ModelBase` object, but there is not such field in the correspondent stub file.

## How is that should be
The field `_meta` should not give a type error.

## System information

- OS: Ubuntu 18.04.5 LTS
- `python` version: 3.6
- `django` version: 2.1
- `mypy` version: 
- `django-stubs` version: 1.7.0
- `pylance` version: v2021.3.0

**Comment by sobolevn** [comment]
I see that you are using `pylance`. Are you using our `mypy` plugin? 

We have a test for `_meta` field: https://github.com/typeddjango/django-stubs/blob
/44151c485d167238889f2afd0b90c1b5f63200bb/tests/typecheck/models/test_meta_options.yml#L18-L22

But, the `_meta` field itself is defined on `Model`: https://github.com/typeddjango/django-stubs/blob/b71c9ad282314a7ac3fe63dcdbd3c2fefb5bac8e/django-stubs/db/models/base.pyi#L27

**Comment by adamchainz** [comment]
Closing due to age.
