### ISSUE TITLE
Docs: about compatibility with mypy version

### ISSUE THREAD

**Issue by oladhari** [typeddjango/django-stubs#575]
# Bug report

## What's wrong

the documentation is mentioning that django-stubs is compatible only with mypy version 0.790 , now we have new version 0.812 in mypy, updating versions does not show any error but wondering why readme file is not mentioning the support of higher mypy versions

## How is that should be

django-stubs | mypy version | django version | python version
-- | -- | -- | --
1.7.0 | >0.790 | 2.2.x \|\| 3.x | ^3.6

## System information

- OS:
- `python` version:3.8
- `django` version:3.1.7
- `mypy` version:0.812
- `django-stubs` version:1.7.0

**Comment by sobolevn** [comment]
@oladhari PR is welcome! I will release a new version soon.

**Comment by oladhari** [comment]
> @oladhari PR is welcome! I will release a new version soon.

do you mean a PR to update documentation?

**Comment by sobolevn** [comment]
yes 🙂
