### ISSUE TITLE
Has version 1.8.0 been published?

### ISSUE THREAD

**Issue by mcranston18** [typeddjango/django-stubs#584]
# Bug report

Hey all. I see version 1.8.0 listed in the [ReadMe](https://github.com/typeddjango/django-stubs#version-compatibility) under versions. However, I don't see it in PyPi:

```
ERROR: Could not find a version that satisfies the requirement django-stubs== (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.5.0, 1.6.0, 1.7.0)
```

## What's wrong

I think version 1.8.0 is meant to be available for install, but it's not.

## How is that should be

I should be able to install 1.8.0, assuming it's been released

## System information

n/a

**Comment by sobolevn** [comment]
I will release it soon, 100% this week

**Comment by mcranston18** [comment]
thank you !
