### ISSUE TITLE
dev-requirements.txt: uses mypy==0.790

### ISSUE THREAD

**Issue by blueyed** [typeddjango/django-stubs#592]
While `pip install -e .` installs "mypy>=0.790" (https://github.com/typeddjango/django-stubs/blob/cc746ab6e5fce1d2f12c7f3206bcb720efcf9adc/setup.py#L24), `pip install -r ./dev-requirements.txt` installs "mypy==0.790" (https://github.com/typeddjango/django-stubs/blob/cc746ab6e5fce1d2f12c7f3206bcb720efcf9adc/dev-requirements.txt#L2, via https://github.com/typeddjango/django-stubs/commit/44151c485d167238889f2afd0b90c1b5f63200bb (https://github.com/typeddjango/django-stubs/pull/485)).

`dev-requirements.txt` is also used on CI, using the pinned/older mypy there for tests: https://github.com/typeddjango/django-stubs/pull/591/checks?check_run_id=2337419461#step:6:124

While I think that pinning (test) dependencies is good in general, I am not sure if this is really intended - and it should probably get upgraded/bumped, or even parametrized on CI maybe?

**Comment by sobolevn** [comment]
Yes, I guess we can remove `mypy` from `dev-requirements`. Because it is specified in `setup.py`.

**Comment by blueyed** [comment]
Ok, same for `typing-extensions` then.

**Comment by blueyed** [comment]
Started in https://github.com/typeddjango/django-stubs/pull/593.

What's your take on testing against specific/different mypy versions on CI?

**Comment by sobolevn** [comment]
> What's your take on testing against specific/different mypy versions on CI?

I think that this can be done, but AFAIK, `mypy` versions are pretty easy to update. And that's what we recommend.
On the other hand, `mypy` can tweak its internals a bit: sometimes some variables change their "inference" status and start / stop using `*` in the output. They can also change the type-var numeration. This can be fatal to our tests (blocked by https://github.com/typeddjango/pytest-mypy-plugins/issues/45). 

So, it is probably a good thing, but I don't see a lot of value.

**Comment by sobolevn** [comment]
@bluetech this is a great example of how different `mypy` versions can fail our CI: https://github.com/typeddjango/django-stubs/pull/593
