### ISSUE TITLE
Not detecting Foreign key reverse relationship

### ISSUE THREAD

**Issue by mabugaj** [typeddjango/django-stubs#596]
# Bug report

I'm playing around with django-stubs and mypy. What I presume from https://github.com/typeddjango/django-stubs/issues/150 reverse relation should be picked up by the mypy with django-stubs.

## What's wrong

I've prepared small repo based on https://github.com/typeddjango/django-stubs/issues/150. Super simple just to be sure it's nothing on my side.

https://github.com/mateusz-geet/django-stubs-reverse-relation

clone and invoke:
`pipenv install`
`pipenv shell`
`cd test` folder containing mypy.ini and manage.py
`mypy test/app/models.py`

mypy throws an error: `test/app/models.py:6: error: "Transaction" has no attribute "transactionlog_set"`

## How is that should be

It shouldn't throw an error.

## System information

- OS: Linux
- `python` version: 3.9.3
- `django` version: 3.2 (3.1.8 also doesn't work)
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by MrkGrgsn** [comment]
Found this after encountering the same issue.  I can reproduce it using the test application in the description in this environment:
- OS: Linux
- `python` 3.6.13
- `django` 2.2.19
- `mypy` 0.812
- `django-stubs` 1.7.0

**Comment by subsonik** [comment]
Same issue here.

- OS: NixOS Linux
- Python 3.9.4
- Django 3.2
- mypy 0.812
- django-stubs 1.8.0

**Comment by mabugaj** [comment]
I'm closing this one as according to:

https://gitter.im/mypy-django/Lobby?at=5d63ab5810bb5d2db071e5aa

all that needs to be done is to add created app to the INSTALLED_APPS. After that everything seems to be working correctly.

**Comment by sobolevn** [comment]
@mateusz-geet PR with the docs is welcome!
