### ISSUE TITLE
Improve monkey-patching for `reveal_{type,locals}

### ISSUE THREAD

**Issue by blueyed** [typeddjango/django-stubs#609]
After doing #591 I've thought that it might be better to only do this patching during the `"django.setup()"` - like initially suggested here.

I think it a) should not require to use the `patch()` method, and b) should not be in place during runtime in general (after the (apparently necessary/unavoidable) "setup").

_Originally posted by @blueyed in https://github.com/typeddjango/django-stubs/issues/590#issuecomment-819423678_

**Comment by sobolevn** [comment]
I agree, it would be closer to real runtime behavior.
