### ISSUE TITLE
Model Field in type annotation runtime error

### ISSUE THREAD

**Issue by cs-cordero** [typeddjango/django-stubs#61]
Originally posted on the gitter:

> I'm coming across this issue where I'm trying to use a `Field` in a type annotation something like: `Dict[Field, Any]`
> 
> If i use mypy on this with django-stubs enabled, i get this error message:

> >     `Missing type parameters for generic type`

> 
> so then i change it to `Dict[Field[Any, Any], Any]`, and that fixes the problem in mypy, but at runtime, it fails:
> 

> >     `TypeError: 'type' object is not subscriptable`

**Comment by mkurnikov** [comment]
Could you confirm whether errors goes away when you specify `disallow_any_generics=False` in the config file? 

Currently `django-stubs` is incompatible with this setting, I've created issue for that https://github.com/mkurnikov/django-stubs/issues/64.

**Comment by cs-cordero** [comment]
Yes, it seems the errors do go away when you specify that setting in the config file.

**Comment by mkurnikov** [comment]
Closing in favor of https://github.com/typeddjango/django-stubs/issues/64
