### ISSUE TITLE
Model ignored when inheriting from third-party abstract model

### ISSUE THREAD

**Issue by salty-horse** [typeddjango/django-stubs#614]
# Bug report

## What's wrong

When a model inherits from an abstract model that is defined in the same file, mypy detects the existence of foreign fields correctly.
However, when a similar abstract model is in a third party library, mypy ignores that model.

It's possible I'm doing something wrong. I apologize if this isn't a real bug.

Sample project: [mysite_mypy](https://github.com/salty-horse/mysite_mypy)

Relevant code in `app_1/models.py`:
```python
from django.db import models
from djext.blame.models import BaseBlameModel

class BaseModel(models.Model):
    some_field = models.CharField()

    def foo(self) -> bool:
        return self.AAA.exists() # This field is defined in the model that inherits from the external library
    def bar(self) -> bool:
        return self.BBB.exists() # This field is defined in the model that inherits from the local model

class ForeignModel(BaseBlameModel): # BaseBlameModel is defined in external library
    base_object = models.ForeignKey(BaseModel, related_name='AAA', on_delete=models.CASCADE)

class AbstractModel(models.Model): # defined locally. Works fine
    class Meta:
        abstract = True

class AnotherForeignModel(AbstractModel):
    base_object = models.ForeignKey(BaseModel, related_name='BBB', on_delete=models.CASCADE)
```

`INSTALLED_APPS` includes `djext.blame` and `app_1`.

```
$ mypy app_1/models.py 
app_1/models.py:4: error: Skipping analyzing 'djext.blame.models': found module but no type hints or library stubs
app_1/models.py:4: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
app_1/models.py:12: error: "BaseModel" has no attribute "AAA"
Found 2 errors in 1 file (checked 1 source file)
```

## How is that should be

While the external library [djext](https://gitlab.com/uda/djext) doesn't have type hints, I expect mypy to still infer that `BaseBlameModel` is a model. The foreign field `AAA` defined in `AnotherForeignModel` should be detected correctly.

## System information

- OS: Ubuntu 21.04
- `python` version: 3.9.4
- `django` version: 3.2.3
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
Hi!

If some library does not have `py.typed` all imports from it would be `Any`. That's how `mypy` works.

**Comment by salty-horse** [comment]
Thanks.
