### ISSUE TITLE
Mypy gives missing stubs error when importing django_stubs_ext 

### ISSUE THREAD

**Issue by ToTheMax** [typeddjango/django-stubs#620]
# Bug report

I'm trying to apply the `django_stubs_ext.monkeypatch()` in order to add types to `admin.ModelAdmin` to prevent mypy errors there. However, when I now run mypy it gives me a module import error.

## What's wrong
Mypy can't find stubs for the `django_stubs_ext` package that I'm trying to import (tried it in different files)
```shell
main/__init__.py:1: error: Skipping analyzing 'django_stubs_ext': found module but no type hints or library
stubs
    import django_stubs_ext
    ^
main/__init__.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```
Ps. I now fixed it by adding `# type: ignore` after the `import django_stubs_ext`

## How is that should be

I should not have to add that ignore comment right? 

## System information

- OS: Ubuntu
- `python` version: 3.8.5
- `django` version: 3.2.3
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
Yes, there was no `py.typed` file in `django_stubs_ext`. I've added one: https://github.com/typeddjango/django-stubs/tree/master/django_stubs_ext/django_stubs_ext

I am going to make a new release soon, so I am closing this issue - it should be fine after the new release! 👍
