### ISSUE TITLE
Release 1.9 version which supports Django 3.2 (LTS version)

### ISSUE THREAD

**Issue by DmytroLitvinov** [typeddjango/django-stubs#624]
Hi @sobolevn ,

As you know [Django@3.2 was released on April 6, 2021](https://docs.djangoproject.com/en/3.2/releases/3.2/). This version is LTS which will be supported for a long time. 
And as far as you know we have started to upgrade [wemake-django-template](https://github.com/wemake-services/wemake-django-template/pull/1608) and we rely on that package :)

From README.md file I see we have `1.9.0-dev` version for `django-stubs` but unfortunately it is not released at [PyPi](https://pypi.org/project/django-stubs/#history) or as a [GitHub tag](https://github.com/typeddjango/django-stubs/tree/v1.9.0-dev).

**Comment by jodal** [comment]
I'd love to see a 1.9 release for the new `pyproject.toml` support too.

**Comment by sobolevn** [comment]
I will release it after we will fix:
- https://github.com/typeddjango/django-stubs/issues/578
- #608

**Comment by christianbundy** [comment]
Is there any chance of getting a release before #608 is resolved? There have been [74 commits since 1.8.0](https://github.com/typeddjango/django-stubs/compare/1.8.0...master) and I'd love to be able to deploy those without pulling directly from GitHub.

**Comment by sobolevn** [comment]
I will fix https://github.com/typeddjango/django-stubs/issues/699 and release it right now 🙂

**Comment by christianbundy** [comment]
‼️ Thanks so much, upgrading to 1.9.0 now.

**Comment by ffedoroff** [comment]
lets do it!
