### ISSUE TITLE
Type of fields on non-model classes resolves to return type

### ISSUE THREAD

**Issue by higherorderfunctor** [typeddjango/django-stubs#63]
Fields on non-model classes are resolving to the return type as if they were on a model.  Use case is binding the field with other data in order to access its field name and to_python methods while doing data collection.

```
from typing import Generic, Text, TypeVar
from django.db import models

A = TypeVar('A')
B = TypeVar('B')

def field_name(field: models.Field[A, B]) -> Text:
    reveal_type(field)  # Revealed type is 'django.db.models.fields.Field[A`-1, B`-2]
    return field.name

class BoundWithField(Generic[A, B]):
    field: models.Field[A, B]
    def field_name(self) -> Text:
        reveal_type(self.field)  # Revealed type is 'B`2
        return self.field.name  # "B" has no attribute "name"
```

**Comment by syastrov** [comment]
At the moment, the stubs represent the most common scenario of fields being instantiated and assigned to attributes inside of model classes.
To make that work, `Field` in the stubs implements the descriptor protocol (e.g. has a `__get__` method).

It's not exactly the truth of how it works in Django (after some poking through the code). `Field` in Django itself isn't a descriptor.
When a model is instantiated, Django's `ModelBase` metaclass actually adds the field to the class wrapped in a `django.db.models.query_utils.DeferredAttribute`, which _is_ a descriptor.

We could choose to represent this in the stubs, and make them "less-usable" in the model field definition scenario if the stubs are used without the mypy django plugin (e.g. with another type-checker). In that case, the mypy django plugin could handle the job of wrapping the attribute in the descriptor on the model when it is defined.

See also https://github.com/python/typing/issues/399

**Comment by mkurnikov** [comment]
I've fixed it in https://github.com/typeddjango/django-stubs/pull/109/commits/ad44a4035365e0869780143624080e1545c6ab62
