### ISSUE TITLE
reveal_type(User.objects.filter) returns UserManager rather than QuerySet[User]

### ISSUE THREAD

**Issue by kracekumar** [typeddjango/django-stubs#635]
# Bug report

```python
from django.contrib.auth.models import User

reveal_type(User.objects.filter(
  email='foo@example.com'))

```

output

```
# mypy filename.py
note: Revealed type is 
  'django.contrib.auth.models.UserManager
  [django.contrib.auth.models.User]'
```
## What's wrong

The output should `QuerySet[django.contrib.auth.models.User]`

I don't know this is mypy bug or stubs bug.
 
## How is that should be

`QuerySet[django.contrib.auth.models.User]`

## System information

- OS: `OSX`
- `python` version: `3.9.4`
- `django` version: `3.2`
- `mypy` version: `0.812`
- `django-stubs` version: `1.8.0`

### Mypy config

```
[mypy]
strict = True
disallow_any_explicit = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
pretty = True
warn_return_any = False

plugins =
        mypy_django_plugin.main,
        mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "koans.dj_koans.mysite.mysite.settings"
```

**Comment by sobolevn** [comment]
@kracekumar does this happen with other models? Or only with `User`?

**Comment by kracekumar** [comment]
@sobolevn It happens for all the models.

```python

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

reveal_type(Question.objects.filter(id=1))
reveal_type(Choice.objects.filter(id=1))
```

output

```
note: Revealed type is 'django.db.models.manager.BaseManager[Any]'
note: Revealed type is 'django.db.models.manager.BaseManager[Any]'
```

**Comment by sobolevn** [comment]
Yes, I can confirm: https://github.com/typeddjango/django-stubs/pull/636/checks?check_run_id=2754398770#step:7:249

```
In [5]: type(ApplicationSubmission.objects.filter(id__gt=0))
Out[5]: django.db.models.query.QuerySet
```

**Comment by p7g** [comment]
I think this is because the stub for QuerySet has `filter` (and other methods) typed like `def filter(self: _QS, *args: Any, **kwargs: Any) -> _QS: ...`, and these queryset method types are copied verbatim to the generated Manager class type. The result is that any chain of QuerySet methods off of the Manager is typed as a Manager, even though at runtime queryset methods on managers return a queryset.

**Comment by sobolevn** [comment]
Yes, this is exactly the cause!
