### ISSUE TITLE
HttpRequest custom attributes

### ISSUE THREAD

**Issue by PyB1l** [typeddjango/django-stubs#643]
Is there a way to validate django request custom atrributes that are set  from middlewares?
I want to avoid errors like: `error: "HttpRequest" has no attribute "x"`
without removing the `def view(request: HttpRequest)` annotation if possible.

**Comment by sobolevn** [comment]
Does this work for you? https://github.com/typeddjango/django-stubs#how-can-i-create-a-httprequest-thats-guaranteed-to-have-an-authenticated-user

TLDR: try subclassing `HttpRequest` with the attributes you need.

**Comment by adamchainz** [comment]
Closing because this is documented.
