### ISSUE TITLE
 User? has no attribute "id"

### ISSUE THREAD

**Issue by Mng-dev-ai** [typeddjango/django-stubs#645]
## What's wrong

I got this error when trying to access User attributes

## Code 

```
from django.contrib.auth import get_user_model 
import json

User = get_user_model()
## Here's where the error comes
users = get_users_by_org(pk) 
responsible_persons = json.dumps( [{'id':user.id, 'name':user.full_name} for user in users])

```
## System information

- OS: Ubuntu 20
- `python` version: 3.8
- `django` version: 3.1
- `mypy` version: 0.782
- `django-stubs` version: 1.8

**Comment by sobolevn** [comment]
Do you have a custom `User` configured? From the look of this error it looks like `User?` is not bound to a type.

**Comment by Mng-dev-ai** [comment]
Yes I have custom user model using AbstractBaseUser. 
So how can i fix it ?

**Comment by Mng-dev-ai** [comment]
I fixed it by importing the User model directly from models file instead of using get_user_model so in my example it should be like this 
```
from accounts.models import User
from django.db.models.query import QuerySet

users : QuerySet[User] = get_users_by_org(pk) 

```
