### ISSUE TITLE
Mypy unable to find out RelatedObjectDoesNotExist

### ISSUE THREAD

**Issue by kracekumar** [typeddjango/django-stubs#649]
# Bug report

Setup

```python
from django.db import models
from django.contrib.auth.models import User

class MyUser(User):
    pass

class Role(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    user = models.OneToOneField(MyUser, on_delete=models.PROTECT)


try:
    user = MyUser.objects.get(pk=1)
    user.role.name
except MyUser.role.RelatedObjectDoesNotExist:
    print('user role mapping is missing')
```

output

```bash
$mypy filename.py
...
user_related.py:15: error: "Type[MyUser]" has no attribute "role"
```

After modifying the code

```python
class MyUser(User):
    role: Role
    pass

```

output

```
...
user_related.py:16: error: "Role" has no attribute "RelatedObjectDoesNotExist"
``` 
## What's wrong

when add the following code in the model and print `MyUser.role.RelatedObjectDoesNotExist` in the shell, you can find the output as `<App.MyUser.role.RelatedObjectDoesNotExist'>`. At runtime, the exception handler works as expected but during type checking the exception is missing to mypy. 

type of `Myuser.role` is `django.db.models.fields.related_descriptors.ForwardOneToOneDescriptor` at runtime.

## How is that should be

Mypy should not complain attribute is missing. 

## System information

- OS: Mac OSX
- `python` version: 3.9.4
- `django` version: 3.2
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by elip-OE** [comment]
Here too. is there any workaround?
