### ISSUE TITLE
BinaryField should have type `memoryview`

### ISSUE THREAD

**Issue by RJPercival** [typeddjango/django-stubs#667]
# Bug report

## What's wrong

`BinaryField` is annotated as type `bytes`.

## How is that should be

`BinaryField` can be of type `memoryview` (see [BinaryField.to_python()](https://github.com/django/django/blob/2a04e24d2dfc8e60a66e4369d970913cb2112d91/django/db/models/fields/__init__.py#L2272)).

## System information

- OS: macOS Big Sur (11.4)
- `python` version: 3.8.3
- `django` version: 3.1.13
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
@RJPercival PRs are welcome!
