### ISSUE TITLE
Error messages refer to private _QuerySet class

### ISSUE THREAD

**Issue by syastrov** [typeddjango/django-stubs#681]
# Bug report

Error messages on `master` now refer to the private `_QuerySet` class.
It's not friendly to users, and doesn't hint about how to properly write the annotations.

We should make the "repr" use either the `QuerySet` alias (if the 2 type parameters are both the same model) or the `django_stubs_ext.ValuesQuerySet` alias.

See https://github.com/python/mypy/issues/6501 for a possible hacky way to do this in the plugin.

**Comment by intgr** [comment]
This has been solved as a side-effect of

* #2104
