### ISSUE TITLE
Field as a part of a union seems to be broken

### ISSUE THREAD

**Issue by budziam** [typeddjango/django-stubs#692]
# Bug report

## What's wrong

Django model Field value as a part of a union results in unexpected behavior. Please find the following example:
```python
from typing import Union
from uuid import UUID

from django.db import models


class User(models.Model):
    uuid = models.UUIDField()


class AnonymousUser:
    uuid: UUID


def example(value: UUID) -> None:
    ...


user_only: User = User()
anonymous_only: AnonymousUser = AnonymousUser()
union_value: Union[AnonymousUser, User] = User()

example(user_only.uuid)
example(anonymous_only.uuid)
example(union_value.uuid)
```

It causes the following error
```
test.py:25: error: Argument 1 to "example" has incompatible type "Union[UUID, UUIDField[Union[str, UUID], UUID]]"; expected "UUID"
```

## How is that should be

No error should be raised.

## System information

- OS: macos
- `python` version: 3.8.9
- `django` version: 3.2.6
- `mypy` version: 0.910
- `django-stubs` version: 1.8.0

**Comment by flaeppe** [comment]
This is an upstream problem for classes with descriptors, ref: https://github.com/python/mypy/issues/5570#issuecomment-541695629

I'm gonna close this in favour of the `mypy` issue.
