### ISSUE TITLE
Cant find section [mypy.plugins.django-stubs]

### ISSUE THREAD

**Issue by AlbertMukarsel** [typeddjango/django-stubs#696]
## What's wrong

Here's my `pyproject.toml`
```
[tool.mypy]
plugins = ["mypy_django_plugin.main"]

ignore_missing_imports = true


[tool.django-stubs]
django_settings_module = "my_website.settings.dev"
```
I'm working on a `virtualenv`

When I try to run mypy on the project I get the following:

```
usage: (config)
...
[mypy.plugins.django_stubs]
    django_settings_module: str (required)
...
(django-stubs) mypy: error: 'django_settings_module' is not set: no section [mypy.plugins.django-stubs]
```

## How is that should be

The plugin should be activated according to the repo readme

## System information

- OS:
- `python` version: 3.9
- `django` version: 3.2.5
- `mypy` version: 0.910
- `django-stubs` version: 1.8

**Comment by sobolevn** [comment]
`pyproject.toml` is only supported in `master`. Please, use it or use `setup.cfg` util we release a new version.
