### ISSUE TITLE
Support `Model.__init__`

### ISSUE THREAD

**Issue by antonagestam** [typeddjango/django-stubs#697]
We've mentioned this in a previous issue, but I thought it was worth having its own tracking issue.

### What's wrong

The problem is that instantiating a model with invalid field types doesn't yield type errors.

```python
class AModel(models.Model):
    a_field = cast("models.Field[int, int]", models.IntegerField())

inst = AModel()
inst.a_field = "not an int"  # this yields an error
AModel(a_field="not an int")  # but this doesn't
```

### How is that should be

Instantiating a model with incorrect field types should yield the same errors as on assignment.

**Comment by sobolevn** [comment]
@antonagestam hi! 👋 🙂 

Do you want to work on this?

**Comment by antonagestam** [comment]
@sobolevn I would, but I'm still pretty intimidated by plugin code. I guess I should be able to look at mypy's builtin dataclasses plugin here though. Perhaps sqlalchemy has a plugin one can get inspired by too. I'll try and find time, but if someone else feels like working on this, please go ahead! 🙂

**Comment by sobolevn** [comment]
Here's the relevant part:

https://github.com/python/mypy/blob/a72fab3b43b0c3ba40abfd4911ec653da5de7230/mypy/plugins/attrs.py#L677-L705
