### ISSUE TITLE
ModelChoiceField could use a type argument

### ISSUE THREAD

**Issue by mthuurne** [typeddjango/django-stubs#698]
# Bug report

## What's wrong

When subclassing `django.forms.ModelChoiceField` and overriding `label_from_instance()`, the type of the method argument is `Model`, but the implementation likely needs to know which concrete model type is being passed.

## How is that should be

While it is possible to work around this using `cast()` or `assert isinstance()`, having a type argument for the model type (`_M`) on `ModelChoiceField` would be a more elegant solution.

## System information

- `django` version: 3.2.6
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
In this case we would need to update both `django-stubs` (types) and `django-stubs-ext` (runtime `__class_getattr__`).
