### ISSUE TITLE
error: "HttpRequest" has no attribute "user"

### ISSUE THREAD

**Issue by snoepkast** [typeddjango/django-stubs#70]
Hi there,

I have the following code:

```python
class MyView(RedirectView):
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> Optional(str):
        if self.request.user.is_authenticated():
            do_something_with_user()
```

Which results in:

```bash
$ mypy
> api/users/authentication/views.py:28: error: "HttpRequest" has no attribute "user"
```

Which is probably because the HttpRequest class doesn't really have the user but it is almost always added through the authentication middleware (either User or AnonymousUser).

So how do I fix this?

**Comment by PeterJCLaw** [comment]
It would be great to have a general solution for this -- Django has several things which are added by middleware (the other one which immediately springs to mind is the `session` attribute).

**Comment by Yobmod** [comment]
I don't know if it makes sense to do, but I tried changing my request type to WSGIRequest, which subclasses HTTPRequest and adds a user attribute (as AbstractUser). 
It silenced the error at least....

**Comment by mkurnikov** [comment]
It could be added as a plugin, like, "if some `AuthenticationMiddleware`", add `user` to some `HttpRequest`". We need some way to describe this fact in the middleware class.
