### ISSUE TITLE
Custom manager causes phantom errors and sometimes crash

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#709]
# Bug report

## What's wrong

Still working on a minimal repro, but here's my stack trace:

```
Traceback (most recent call last):
  File "/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/.venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2697, in dispatch
  File "mypy/build.py", line 3021, in process_graph
  File "mypy/build.py", line 3137, in process_stale_scc
  File "mypy/errors.py", line 565, in file_messages
  File "mypy/errors.py", line 538, in format_messages
IndexError: list index out of range
```

I have a `FooManager`:

```python3
from django.db import models

class FooManager(models.Manager):

    def create_with_foo(self, *args, **kwargs) -> models.Model: # Line 7
        pass

    def save_foo(self, model: models.Model) -> None: # Line 25
        pass
```

It's often used on models like this:

```python3
objects = FooManager()
```

For some reason, three _completely unrelated_ files are getting these errors:

```
some_file.py:7: error: Name "models" is not defined  [name-defined]
    )
    ^
some_file.py:25: error: Name "models" is not defined  [name-defined]
            does_not_matter_anything_could_be_here()
```

I tried adding whitespace to the top of `some_file.py` but the line numbers didn't change. Odd. I looked through my project for files where lines 7 and 25 referenced `models` and found my `FooManager`. I added 1 line to the top of `FooManager` and the mypy errors incremented by 1. I added 100 lines to the top of `FooManager` and got this sweet stack trace.

## How is that should be

There should be no errors.

## System information

- OS:
- `python` version: 3.9.6
- `django` version: 3.1
- `mypy` version: 0.910
- `django-stubs` version: 1.8.0 
- `django-stubs-ext` version: 0.3.1

**Comment by antonagestam** [comment]
I'm running into this too. I realized probably all of our models that define custom managers using `objects = BaseManager.from_queryset(...)()` reveals `Any` for `reveal_type(Models.objects)`, and therefor also for `Model.objects.{get,all,...}()`.

At first sight it looked like moving the manager definition outside of the model class body fixed the issue, but after doing that a whole sea of odd errors appear in the manager module. Things like this:

```
src/catalog/models.py:399: error: Name 'Sequence' is not defined  [name-defined]
            state = getattr(self, annotation)
```

**Comment by flaeppe** [comment]
> At first sight it looked like moving the manager definition outside of the model class body fixed the issue, but after doing that a whole sea of odd errors appear in the manager module. Things like this:
> 
> ```
> src/catalog/models.py:399: error: Name 'Sequence' is not defined  [name-defined]
>             state = getattr(self, annotation)
> ```

@antonagestam I think I've found the cause of these kind of errors. A closer look in https://github.com/typeddjango/django-stubs/blob/fafb200e9084cbd7603a1ebba95bfb6a46626e43/mypy_django_plugin/transformers/managers.py#L9

Where it seems like a new "manager node" is created and from what I can tell, that new manager node ends up where the `... = BaseManager.from_queryset(CustomQuerySet)` call lives https://github.com/typeddjango/django-stubs/blob/fafb200e9084cbd7603a1ebba95bfb6a46626e43/mypy_django_plugin/transformers/managers.py#L52-L59

I'm quite convinced that the error you're encountering appears when:

1. A custom `QuerySet` is declared in a module _different_ from where the using `Model` is declared
2. The custom `QuerySet` declares methods with types that are not present in the module where the using `Model` is declared (e.g. `Sequence`)

---

An additional note regarding

> ... models that define custom managers using `objects = BaseManager.from_queryset(...)()` reveals `Any` for `reveal_type(Models.objects)`, and therefor also for `Model.objects.{get,all,...}()`.

It seems that the reason for `Any` is that `create_new_manager_class_from_from_queryset_method` is never called when doing: `objects = BaseManager.from_queryset(...)()`

**Comment by antonagestam** [comment]
@flaeppe I think your findings could explain why I had a hard time creating a minimal reproduction, I think I missed trying with manager and model in different modules. While I was completely dumbfounded by these errors, it sounds like you've figured it out 👍

**Comment by aleksanb** [comment]
I just hit `Name 'Sequence' is not defined  [name-defined]` when doing
```
MyManager = MyBaseManager.from_queryset(MyBaseQueryset)

class SomeClass(models.Model):
  objects = MyManager()
```

Even though all models / managers / querysets were defined in the same function.
I ended up working around this by removing the manager methods and doing objects = MyBaseQueryset.as_manager() instead.

Using newest django-stubs.

**Comment by flaeppe** [comment]
@aleksanb That's interesting, can you produce a repro? As far as I can tell the test that I found, below, should cover the case you describe:

https://github.com/typeddjango/django-stubs/blob/8d8b8cd1fc8b54eac799905dbbffc4e21708b6da/tests/typecheck/managers/querysets/test_from_queryset.yml#L284-L311

i.e. Custom `QuerySet`, custom `Manager`, building a new manager via `Manager.from_queryset(QuerySet)` where both the custom queryset and manager has method signatures containing imported types.

Also, be aware of that if you use `.as_manager()` I think the type of the manager will be `Any`.

**Comment by aleksanb** [comment]
I'll try making a minimal reproduce, but won't have time till next week.
Perhaps it's some interaction with our model structure or something.

**Comment by flaeppe** [comment]
Cool, think you should open a new issue if you figure out a way to reproduce the error.

**Comment by christianbundy** [comment]
I think I might have a lead.

Pass:

```python3
class FooManager(models.Manager['Foo']):
    pass

FooModelManager = FooManager.from_queryset(FooQuerySet)

class Foo(models.Model):
    objects = FooModelManager()
```

Fail:

```python3
FooModelManager = models.Manager.from_queryset(FooQuerySet)

class Foo(models.Model):
    objects = FooModelManager()
```

I've opened https://github.com/typeddjango/django-stubs/pull/1017 to try to run this failing test in CI.

**Comment by jose-reveni** [comment]
@aleksanb  I have been getting a similar error too!

**Comment by aleksanb** [comment]
> I've opened #1017 to try to run this failing test in CI.

Seems like CI doesn't run automatically anymore?
Someone needs to approve the CI build to run.

**Comment by ljodal** [comment]
I'm seeing the same issue and have traced it back to https://github.com/typeddjango/django-stubs/pull/991, will try to see if I can reproduce it in a test

**Comment by ljodal** [comment]
This test reproduces the issue locally for me, but not on CI for some reason (see #1021):

```yaml
-   case: from_queryset_custom_auth_user_model
    main: |
        from users import User
    custom_settings: |
        AUTH_USER_MODEL = "users.User"
        INSTALLED_APPS = ("django.contrib.auth", "django.contrib.contenttypes", "users")
    files:
        -   path: users/__init__.py
        -   path: users/models.py
            content: |
                from django.contrib.auth.models import AbstractBaseUser
                from django.db import models

                from .querysets import UserQuerySet

                UserManager = models.Manager.from_queryset(UserQuerySet)

                class User(AbstractBaseUser):
                    email = models.EmailField(unique=True)
                    objects = UserManager()
                    USERNAME_FIELD = "email"

        -   path: users/querysets.py
            content: |
                from django.db import models
                from typing import Optional, TYPE_CHECKING

                if TYPE_CHECKING:
                    from .models import User

                class UserQuerySet(models.QuerySet["User"]):
                    pass
```
