### ISSUE TITLE
Field type is Any

### ISSUE THREAD

**Issue by baojd42** [typeddjango/django-stubs#711]
# Bug report

## What's wrong
Field type is inferred as Any.
![image](https://user-images.githubusercontent.com/33564834/132640165-c1afe96a-8051-4bb6-a689-abe3998266ab.png)

I am not sure this is a django-stubs/mypy problem or a vscode issue or I should not expect the type here.

## How is that should be
self.name be inferred as string type or CharField

## System information

- OS:
- `python` version: 3.8.6
- `django` version: 3.1.3
- `mypy` version:  0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version:

**Comment by sobolevn** [comment]
I guess that this is because vscode uses pyright, which does not support `mypy` plugins. So, this is fine.
Try to add `reveal_type(self.name)` and run `mypy` to see that field inference works.

Please, reopen if this is not going to work for you.

**Comment by baojd42** [comment]
> I guess that this is because vscode uses pyright, which does not support `mypy` plugins. So, this is fine.
> Try to add `reveal_type(self.name)` and run `mypy` to see that field inference works.
> 
> Please, reopen if this is not going to work for you.

Yes, you are right, django-stubs and mypy work just fine. The reveal_type gives correct info. Thanks.
