### ISSUE TITLE
`filter(...)` and similar methods returns QuerySet[Any]

### ISSUE THREAD

**Issue by StabbarN** [typeddjango/django-stubs#716]
Same as https://github.com/typeddjango/django-stubs/issues/673
It fails on all custom methods on queryset.

Example:
```
from django.db import models

class EntityQuerySet(models.QuerySet):
    pass


EntityManager = models.Manager.from_queryset(EntityQuerySet)


class Entity(models.Model):
    bar = models.BooleanField()

    objects = EntityManager()


reveal_type(Entity.objects.get())  # Revealed type is "Entity*"
reveal_type(Entity.objects.filter(bar=True))  # Revealed type is "EntityQuerySet[Any]"

```

The last row should reveal something like `EntityQuerySet[Entity*]`.

- OS:
- `python` version: 3.9.2
- `django` version: 3.2.7
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by sobolevn** [comment]
СС @syastrov

**Comment by StabbarN** [comment]
I'm a bit uncertain what's going on. dmypy seems to be working but mypy crashes. My setup is likely incorrect. I'll close this issue until I've investigated it further and have a complete git repository where it can trivially be reproduced.
