### ISSUE TITLE
Python 3.6: ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by andreymal** [typeddjango/django-stubs#72]
Your fix https://github.com/mkurnikov/django-stubs/commit/dcb4da378b50055e338eae95a50fa38357fa66be is actually not working, because it seems that the `.whl` file was built using Python 3.7 and the `dataclasses` dependency was not added to the wheel.

```
$ virtualenv --python /usr/bin/python3.6 py36
$ . py36/bin/activate
(py36) $ pip install django-stubs
Collecting django-stubs
  Using cached https://files.pythonhosted.org/packages/4e/16/03c7804694c16e5f6c159ef527ba6cbdaf2c1cfc76edc2c0f1daeead798d/django_stubs-0.12.1-py3-none-any.whl
Successfully installed django-stubs-0.12.1 mypy-0.701 mypy-extensions-0.4.1 typed-ast-1.3.5 typing-extensions-3.7.2

(py36) $ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mypy_django_plugin
>>> from mypy_django_plugin import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py36/lib/python3.6/site-packages/mypy_django_plugin/main.py", line 13, in <module>
    from mypy_django_plugin.config import Config
  File "py36/lib/python3.6/site-packages/mypy_django_plugin/config.py", line 4, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by mkurnikov** [comment]
Thank you for reporting this! 

Guess it's time to teach travis ci to release wheels, instead of doing it manually... 
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by sobolevn** [comment]
I copy my message from gitter here as well:

Here's a working example of how to release wheels from travis https://github.com/sobolevn/django-split-settings/blob/master/.travis.yml#L20

An extra step is to add protected CI environment like so: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

We also need to build wheels like this: `distributions: "sdist bdist_wheel"`
Docs: https://docs.travis-ci.com/user/deployment/pypi/

`universal = True` also helps: https://github.com/sobolevn/django-split-settings/blob/master/setup.cfg#L1-L2
