### ISSUE TITLE
django.utils.html.format_html_join should allow mixed string and SafeText arguments

### ISSUE THREAD

**Issue by rolandcrosby-check** [typeddjango/django-stubs#721]
# Bug report

## What's wrong

The [type annotation][ann] `List[Tuple[str]]` on `django.utils.html.format_html_join`'s `args_generator` argument is unnecessarily conservative. The tuples in `args_generator` are [passed into `format_html`'s args][format_html_call]. `format_html` [uses `conditional_escape`][cond_escape_call] on its arguments, which [supports][cond_escape_args] plain strings and any pre-escaped object (i.e. an object that has a `__html__` method.). So it's perfectly valid, from Django's perspective, to mix plain and pre-escaped strings in the tuples in `args_generator`, but django-stubs doesn't accept such input as valid.

This can be reproduced by typechecking the following snippet:

```python
from django.utils.html import escape, format_html_join

format_html_join("\n", "{} {}", [(escape("test"), "test")])
```
which for me yields the error:

`error: List item 0 has incompatible type "Tuple[SafeText, str]"; expected "Tuple[str]"`

## How is that should be
`args_generator` in `format_html_join` should be as permissive in what it allows as `format_html` is. Right now I see that [`format_html`'s `*args` parameter is annotated as `Any`][format_html_ann], which isn't great but which might be the best solution here, unless django-stubs has a way to encode the idea of "anything that can be coerced to a string or has a `__html__` method".

## System information

Per the source code links above, this issue appears to be present in the latest versions of Django and django-stubs, but the versions I'm using locally are:

- OS: macOS 11.6
- `python` version: 3.8.11
- `django` version: 3.1.13
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0
- `django-stubs-ext` version: n/a

[ann]: https://github.com/typeddjango/django-stubs/blob/fb125609818057dff8aad807637b3ca9cca5e194/django-stubs/utils/html.pyi#L19-L21
[format_html_call]: https://github.com/django/django/blob/4ffada36097ceccfd6f0d358217ac3c40d2a729c/django/utils/html.py#L133
[cond_escape_call]: https://github.com/django/django/blob/4ffada36097ceccfd6f0d358217ac3c40d2a729c/django/utils/html.py#L113
[cond_escape_args]: https://github.com/django/django/blob/4ffada36097ceccfd6f0d358217ac3c40d2a729c/django/utils/html.py#L92-L104
[format_html_ann]: https://github.com/typeddjango/django-stubs/blob/fb125609818057dff8aad807637b3ca9cca5e194/django-stubs/utils/html.pyi#L18

**Comment by sobolevn** [comment]
@rolandcrosby-check pr is welcome!

**Comment by rolandcrosby-check** [comment]
@sobolevn Happy to put up a PR to change this to `List[Tuple[Any]]` if you think that's the best way forward, just wasn't sure if there's a better alternative.
