### ISSUE TITLE
Type inference for user fails when inside if with multiple conditions

### ISSUE THREAD

**Issue by armisael** [typeddjango/django-stubs#726]
# Bug report

In our codebase I stumbled on something that looks like a bug; the code is messy, and is using an old versions of Django, so I tried to replicate the issue in a new toy project, with the latest versions available. Unfortunately, I succeeded.

## What's wrong

As the title says, inference for `user` fails when inside an `if` with more than one condition; take this example:

```python
def f(user: User | AnonymousUser | None) -> None:
    reveal_type(user)  # Revealed type is "Union[django.contrib.auth.models.User, django.contrib.auth.models.AnonymousUser, None]"

    if user is not None and user.is_authenticated:
        reveal_type(user)  # Revealed type is "Union[django.contrib.auth.models.User, django.contrib.auth.models.AnonymousUser]"

    if user is not None:
        if user.is_authenticated:
            reveal_type(user)  # Revealed type is "django.contrib.auth.models.User"
```

## How is that should be

I would expect `reveal_type(user)` to be `User` inside the first `if`, as it is in the second one.

## System information

- OS: MacOS
- `python` version: 3.9.4
- `django` version: 3.2.8
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by flaeppe** [comment]
This is a `mypy` type narrowing issue rather than a `django-stubs` issue
