### ISSUE TITLE
The functional API for Django's enumeration types isn't supported

### ISSUE THREAD

**Issue by kevinmarsh** [typeddjango/django-stubs#729]
# Bug report

## What's wrong

The functional API for [Django's Enumeration types](https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types) doesn't seem to be supported.

These two run fine:
```python
# Example from https://docs.python.org/3/library/enum.html#functional-api
from enum import Enum
Animal = Enum('Animal', 'ANT BEE CAT DOG')

# Example from: https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types
from django.db import models
class Vehicle(models.TextChoices):
     CAR = 'C'
     TRUCK = 'T'
     JET_SKI = 'J'
```

But this raises an error:
```python
# Example from: https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types
from django.db import models
MedalType = models.TextChoices('MedalType', 'GOLD SILVER BRONZE')
```
```
my_file.py:3: error: No overload variant of "TextChoices" matches argument types "str", "str"
my_file.py:3: note: Possible overload variant:
my_file.py:3: note:     def __new__(cls, o: bytes, encoding: str = ..., errors: str = ...) -> TextChoices
my_file.py:3: note:     <1 more non-matching overload not shown>
```
## How is that should be

The resulting enum's type should be the same whether you use the normal class based approach or the functional API approach.

## System information

- OS: linux
- `python` version: 3.9.7
- `django` version: 3.2.8
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by adamchainz** [comment]
I believe this is due to a Mypy bug: https://github.com/python/mypy/issues/6037 . It sounds like Mypy’s enum support needs extending.

I think we can’t do anything here, so closing, but thank you for the report.
