### ISSUE TITLE
Unrecognised attribute create_user

### ISSUE THREAD

**Issue by petermcd** [typeddjango/django-stubs#735]
# Bug report

## What's wrong

When running mypy after installing django-stubs mypy provides the following error:

before

```
website\views.py:1: error: Skipping analyzing "django.contrib.auth": found module but no type hints or library stub
s
website\views.py:2: error: Skipping analyzing "django.contrib.auth.models": found module but no type hints or libra
ry stubs
website\views.py:3: error: Skipping analyzing "django.db": found module but no type hints or library stubs
website\views.py:4: error: Skipping analyzing "django.http": found module but no type hints or library stubs
website\views.py:5: error: Skipping analyzing "django.shortcuts": found module but no type hints or library stubs
website\apps.py:1: error: Skipping analyzing "django.apps": found module but no type hints or library stubs
website\apps.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
website\urls.py:1: error: Skipping analyzing "django.urls": found module but no type hints or library stubs
```

after

`website\views.py:68: error: "BaseManager[Any]" has no attribute "create_user"`

The line in question is 

`user = User.objects.create_user(username=email, email=email, password=password)`

## How is that should be

The line in question is valid is how users are created when not using the standard dJango forms. This error should not be raised.

## System information

- OS: Winders 11
- `python` version: 3.9.5
- `django` version: 3.2.8
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by SourceSurfer** [comment]
Same problem 
django-admin 2.2.19
pip 21.3.1
Python 3.9.6
mypy 0.910

**Comment by AntoineRondelet** [comment]
I'm experiencing a similar issue.
mypy 0.950
django 4.1
python 3.10.7

Any news on this?

**Comment by AntoineRondelet** [comment]
Have you both properly configured mypy?
i.e. if you used `mypy.ini` did you properly point to your django config via:
```
[mypy.plugins.django-stubs]
django_settings_module = <your_project>.settings
```
? If not that might be the reason of your troubles.

**Comment by flaeppe** [comment]
This looks indeed much like a configuration problem.

I'll close this off, feel free to reopen with a breaking case
