### ISSUE TITLE
CharField(blank=True) treated as nullable

### ISSUE THREAD

**Issue by zach-waggoner** [typeddjango/django-stubs#736]
## What's wrong

When I run mypy with this plugin enabled, it infers the type for CharFields with `blank=True` as `Optional[str]`.

## How is that should be

I believe this is incorrect, as `blank=True` only permits empty strings, not NULL. It seems like this was allegedly fixed in #39, but I'm still having the same issue. I noticed that if I remove the following lines from `DjangoContext.get_field_nullability`, it works:

```python
if not nullable and isinstance(field, CharField) and field.blank:
    return True
```

## System information

- OS:
- `python` version: 3.9.7
- `django` version: 3.2.9
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: N/A

**Comment by sobolevn** [comment]
@zach-waggoner PR is welcome!

**Comment by flaeppe** [comment]
I cannot reproduce this, feel free to reopen with a breaking case.
