### ISSUE TITLE
Error on automatic primary key fields - model has no attribute "id"

### ISSUE THREAD

**Issue by mvernacc** [typeddjango/django-stubs#742]
# Bug report

I am attempting to follow [the tutorial](https://sobolevn.me/2019/08/typechecking-django-and-drf) on @sobolevn's blog. My code is [here](https://github.com/mvernacc/test_django_typing) (mostly copy-paste from that tutorial).

## What's wrong

`mypy` gives errors on the automatic primary key `id` of the model `BlogPost`:

```
mysite/main/models.py:16: error: "BlogPost" has no attribute "id"
mysite/main/models.py:16: note: Revealed type is "Any"
mysite/main/models.py:17: note: Revealed type is "Any"
mysite/main/models.py:18: note: Revealed type is "builtins.str*"
mysite/main/models.py:19: note: Revealed type is "builtins.bool*"
mysite/main/models.py:20: note: Revealed type is "datetime.datetime*"
mysite/main/models.py:21: error: "BlogPost" has no attribute "id"
mysite/main/views.py:6: note: Revealed type is "def () -> builtins.bool"
mysite/main/views.py:7: note: Revealed type is "Union[django.contrib.auth.models.User, django.contrib.auth.models.AnonymousUser]"
mysite/manage.py:22: error: Call to untyped function "main" in typed context
Found 3 errors in 2 files (checked 13 source files)
```

## How is that should be
Based on the [Typechecking models and queryset section of the tutorial](https://sobolevn.me/2019/08/typechecking-django-and-drf#typechecking-models-and-queryset), I do not expect `error: "BlogPost" has no attribute "id"`, and I expect the revealed type of `id` to be `builtins.int*`.

Expected output copied from the tutorial:
```
server/apps/main/models.py:21: note: Revealed type is 'builtins.int*'
server/apps/main/models.py:22: note: Revealed type is 'django.contrib.auth.models.User*'
server/apps/main/models.py:23: note: Revealed type is 'builtins.str*'
server/apps/main/models.py:24: note: Revealed type is 'builtins.bool*'
server/apps/main/models.py:25: note: Revealed type is 'datetime.datetime*'
```

Some possible discrepancies:

 - The example output in the tutorial refers to lines 21-25 of models.py, but the example models.py given at that point in the tutorial is only 21 lines long.

 - That tutorial post is from 2 years ago, so perhaps the behavior has changed in the current versions of django, mypy and django-stubs?

This might be related to #488 or #645, which also mention a `has no attribute "id"`, error.

## System information

- OS: Ubuntu 20.04 (in WSL2)
- `python` version: 3.9.5
- `django` version: 3.2.8
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by mvernacc** [comment]
Any suggestions?

**Comment by sobolevn** [comment]
Related https://github.com/typeddjango/django-stubs/pull/779
