### ISSUE TITLE
Model.Meta type conflicts with runtime use of `class Meta`

### ISSUE THREAD

**Issue by w0rp** [typeddjango/django-stubs#748]
# Bug report

## What's wrong

https://github.com/typeddjango/django-stubs/blob/d5e45db79bcea6d6f4f45eacca3a2fe6e125e2e3/django-stubs/db/models/base.pyi#L23

`Meta` is defined as `class Meta` in the `Model` type, but this causes type errors in Pyright's strictest type checking mode because a new class that happens to be named `Meta` cannot replace another class with the same name `Meta`.

## How is that should be

It might be better to define type type like so:

```py
Meta: object
```

You can assign this issue to me and I'll fix it in some way later. There will be some type that allows it being replaced with a new `class Meta` without errors instead. Generally what you want is that simply writing `class Meta:` doesn't cause a type error in Pyright.

## System information

- OS: Linux
- `python` version: 3.9
- `django` version: 3.2
- `mypy` version: N/A
- `django-stubs` version: 1.7.0
- `django-stubs-ext` version: N/A

**Comment by sobolevn** [comment]
> Generally what you want is that simply writing class Meta: doesn't cause a type error in Pyright.

Not just `class Meta`. But, we want to type DSL as well.

**Comment by w0rp** [comment]
I'm not sure what you mean. Do you mean we want to type the domain-specific language of Django model options?

**Comment by w0rp** [comment]
I think this isn't something that can be fixed in the library, it just needs to be disabled in Pyright by disabling `reportIncompatibleVariableOverride` errors.
