### ISSUE TITLE
functools.partial does not carry over type of ForeignKey

### ISSUE THREAD

**Issue by StefanBrand** [typeddjango/django-stubs#750]
# Bug report

## What's wrong
I have two models:

```python
ProtectedForeignKey = partial(models.ForeignKey, on_delete=models.PROTECT)

class Model(models.Model):
    config = ProtectedForeignKey("Config")

class Config(models.Model):
    version = models.IntegerField()

model = Model.objects.get()
model.config.version  # "_GT" has no attribute "version"
```
___

Without `partial`, it works fine:
```python
class Model(models.Model):
    config = models.ForeignKey("Config", on_delete=models.PROTECT)  # ForeignKey[Union[Config, Combinable], Config]
```

___

Edit: And `cast`ing works in 1.8.0 (but not in 1.9.0 due to #725)
```python
class Model(models.Model):
    config = cast("Config", ProtectedForeignKey("Config"))
```
## How it should be

`partial` should carry over the `ForeignKey` type.

## System information

- OS: Ubuntu 20.04
- `python` version: 3.9.1
- `django` version: 3.1.5
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- ~`django-stubs-ext` version:~

**Comment by flaeppe** [comment]
```python
ProtectedForeignKey = partial(models.ForeignKey, on_delete=models.PROTECT)

class Model(models.Model):
    config = ProtectedForeignKey("Config")
```

`ForeignKey` is generic, but in this situation having unbound arguments. That's why e.g. there's a `_GT` in the error message. That's why I'll close this off.
