### ISSUE TITLE
`ManyToManyField` is not complete

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#754]
Django defines `ManyToManyField` with more precise types that we do.
Django 3.2: https://github.com/django/django/blob/3.2/django/db/models/fields/related.py#L1134-L1142
Our stubs: https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/fields/related.pyi#L180-L187

We need to fix this.

**Comment by StasGC** [comment]
Hello!
I want to solve this.

**Comment by flaeppe** [comment]
I think this has been closed via #909 and #1253
