### ISSUE TITLE
`django.test.testcases.SimpleTestCase` missing `async_client`, `async_client_class`, `assertURLEqual`, and there is a deleted `allow_database_queries`

### ISSUE THREAD

**Issue by star2000** [typeddjango/django-stubs#759]
# Bug report

## What's wrong

as title

## System information

- OS:
- `python` version:3.9.7
- `django` version:3.2.9
- `mypy` version:0.910
- `django-stubs` version:1.9.0
- `django-stubs-ext` version:0.3.1

**Comment by sobolevn** [comment]
PRs are welcome 😉
