### ISSUE TITLE
TypeError: Too many arguments for typing.Annotated[...]; actual 2, expected 1

### ISSUE THREAD

**Issue by johnnymetz** [typeddjango/django-stubs#763]
# Bug report

## What's wrong

I have the following unit test written in pytest and pytest-django:

```
from typing import TypedDict
from django.contrib.auth.models import Group, User
from django.db.models import Count
from django_stubs_ext import WithAnnotations

class AnnotatedUser(TypedDict):
    group_count: int

def print_user_group_count(user: WithAnnotations[User, AnnotatedUser]):
    print(f"{user} belongs to {user.group_count} groups")

@pytest.mark.django_db()
def test_annotated_users():
    group1 = Group.objects.create(name="Group 1")
    group2 = Group.objects.create(name="Group 2")
    group3 = Group.objects.create(name="Group 3")

    user1 = User.objects.create_user(username="user1")
    user2 = User.objects.create_user(username="user2")
    User.objects.create_user(username="user3")

    user1.groups.add(group1, group2, group3)
    user2.groups.add(group1)

    users = User.objects.annotate(group_count=Count("groups"))
    for user in users:
        print_user_group_count(user)
```

It raises an exception with the following traceback:

```
zen/tests.py:87: in <module>
    def print_user_group_count(user: WithAnnotations[User, AnnotatedUser]):
/usr/local/lib/python3.10/typing.py:309: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.10/typing.py:1037: in __getitem__
    _check_generic(self, params, len(self.__parameters__))
/usr/local/lib/python3.10/typing.py:228: in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
E   TypeError: Too many arguments for typing.Annotated[~_T, django_stubs_ext.annotations.Annotations[+_Annotations]]; actual 2, expected 1
```

## How is that should be

Unit test should run successfully to completion.

It works fine if I change `print_user_group_count` to:

```
def print_user_group_count(user: WithAnnotations[User]): ...
```

## System information

- OS:
- `python` version: 3.9.9, 3.10.0
- `django` version: 3.2.9
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by sobolevn** [comment]
Looks like we've messed up something here: https://github.com/typeddjango/django-stubs/blob/master/django_stubs_ext/django_stubs_ext/annotations.py#L10-L22

Can you please take a look? 🙂

**Comment by johnnymetz** [comment]
Looked into it for a few hours but wasn't able to figure it out.

Some notes:
- According to [PEP-593](https://www.python.org/dev/peps/pep-0593/), `Annotated` can take multiple arguments. As matter of fact, it must take multiple arguments.

> Annotated must be called with at least two arguments (Annotated[int] is not valid)

- `Annotated` is now part of the core `typing` module so we can change the import in [this file](https://github.com/typeddjango/django-stubs/blob/master/django_stubs_ext/django_stubs_ext/annotations.py) to `from typing import Annotated`

**Comment by sobolevn** [comment]
Here's the self-repro example:

```python
from typing import Any, Generic, Mapping, TypeVar, TypedDict

from typing_extensions import Annotated

# Really, we would like to use TypedDict as a bound, but it's not possible
_Annotations = TypeVar("_Annotations", covariant=True, bound=Mapping[str, Any])

class Model:
    pass

class Annotations(Generic[_Annotations]):
    """Use as `Annotations[MyTypedDict]`"""

    pass


_T = TypeVar("_T", bound=Model)

WithAnnotations = Annotated[_T, Annotations[_Annotations]]

class User(TypedDict):
    age: int

Y = WithAnnotations[Model]  # ok
X = WithAnnotations[Model, User]  # error, but should be passing
```

Looks like `Annotations[_Annotations]` does not get replaced or even counted as a type var in `Annotated` 🤔

**Comment by ObiWanKeoni** [comment]
Isn’t this the same error as #719 ?

**Comment by johnnymetz** [comment]
Yes, this is exactly the same issue. The workaround in [this comment](https://github.com/typeddjango/django-stubs/issues/719#issuecomment-928067545) helped. Thanks!

**Comment by intgr** [comment]
Closing as duplicate of #719.
