### ISSUE TITLE
Can't import RelatedManager

### ISSUE THREAD

**Issue by oren0e** [typeddjango/django-stubs#765]
If I write:
```python
if typing.TYPE_CHECKING:
    from django_stubs.db.models.manager import RelatedManager
```
I get "import could not be resolved". It seems that the `.db.models.manager` part is not "seen".. (I also can't "go to definition" there). Any ideas?

**Comment by intgr** [comment]
This should work:

```python
if typing.TYPE_CHECKING:
    from django.db.models.manager import RelatedManager
```

**Comment by sobolevn** [comment]
Please, reopen if it does not.

**Comment by tylerlaprade** [comment]
@sobolevn, this worked fine for me in 4.2.6, but is now broken after upgrading to 4.2.7
<img width="660" alt="image" src="https://github.com/typeddjango/django-stubs/assets/5475199/012c079c-9788-40ba-be0f-7e3aa14e0e64">

**Comment by intgr** [comment]
@tylerlaprade Yes, this changed in 4.2.7, it was [covered in the release notes](https://github.com/typeddjango/django-stubs/releases/tag/4.2.7):

* If you previously imported RelatedManager or ManyRelatedManager, update those to django-stubs-ext:
  `from django_stubs_ext.db.models.manager import ManyRelatedManager, RelatedManager`

But we have another issue #1868 that suggests this may not work in Pylance/pyright. If you could help us troubleshoot it, it would be appreciated.

**Comment by intgr** [comment]
In any case, please report back if that works for you or not.

**Comment by tylerlaprade** [comment]
Oh nice, `from django_stubs_ext.db.models.manager import RelatedManager` actually works perfectly for me in Pylance/pyright!

**Comment by paulrogov** [comment]
> Oh nice, `from django_stubs_ext.db.models.manager import RelatedManager` actually works perfectly for me in Pylance/pyright!

Update for 2025: for me this results in an import error
```python
from django_stubs_ext.db.models.manager import RelatedManager ❌
# "RelatedManager" is unknown import symbolPylance[reportAttributeAccessIssue]
```

However, another solution has **worked**:
```python
from django.db.models.manager import Manager ✅
```

p.s.
VS Code: `1.102.0`
Python: `3.10.18`
Django: `4.2`
Linux .devcontainer

Originally mentioned here: [stackoverflow (ref)](https://stackoverflow.com/questions/72535133/django-resolve-a-related-field-to-queryset-type?utm_source=chatgpt.com)
