### ISSUE TITLE
FormMixin is incompatible with SuccessMessageMixin

### ISSUE THREAD

**Issue by PeterJCLaw** [typeddjango/django-stubs#79]
From what I can tell, the Django sources for these two are fine to be mixed together, however the type annotations seem to disagree:

``` python
from django.views.generic.edit import FormMixin
from django.contrib.messages.views import SuccessMessageMixin

reveal_type(FormMixin.form_valid)
# Revealed type is 'def (self: ..., form: django.forms.forms.BaseForm) -> django.http.response.HttpResponse'
reveal_type(SuccessMessageMixin.form_valid)
# Revealed type is 'def (self: ..., form: django.forms.forms.Form) -> django.http.response.HttpResponseRedirect'

class FooView(FormMixin, SuccessMessageMixin):
    pass

# Definition of "form_valid" in base class "FormMixin" is incompatible with definition in base class "SuccessMessageMixin"
```

I suspect that the signature of `FormMixin` is the one we want to use, so the fix is to update `SuccessMessageMixin` to match. (If you agree that's a good solution I'd be happy to put up a PR)

**Comment by antonagestam** [comment]
Yes, I believe restricting `SuccessMessageMixin.form_valid` to take `Form` instead of `BaseForm` violates the Liskov substitution principle.

**Comment by PeterJCLaw** [comment]
Unfortunately that fix doesn't seem to completely resolve the issue for me. I'll put up a PR with a proposed fix.

**Comment by antonagestam** [comment]
@PeterJCLaw Oh yeah, that makes sense I guess.

Is there a way to use an ABC to make sure view-mixins have the right shape in typestubs?

**Comment by PeterJCLaw** [comment]
I'm not sure if that's possible in type stubs. I'd guess it probably is, though not a pattern I've seen.

I'm guessing you mean something like this:
``` python
# common.pyi
class _FormMixinCommon(abc.ABC):
    def form_valid(self, ...): ...

# forms.pyi
from ...common import _FormMixinCommon
class FormMixin(_FormMixinCommon):
    ...

# forms.pyi
from ...common import _FormMixinCommon
class SuccessMessageMixin(_FormMixinCommon):
    ...
```

I'm not sure whether that's any better than just duplicating the signature and adding a test (the latter being what I've done in that PR).

I suspect that duplicating the signature is probably clearer and (at least for small numbers of duplicates) doesn't represent much maintenance burden.

There's probably benefit in keeping the type definitions reasonably close to the shape of the actual source we're typing.

Are there other places where you think the ABC pattern might be useful? (If it just ends up being this place I suspect it would be more confusing to readers.)
