### ISSUE TITLE
PyCharm gets weird about self.request.GET.get

### ISSUE THREAD

**Issue by Crocmagnon** [typeddjango/django-stubs#799]
# Bug report
## What's wrong

```python
class ArticleDetailView(generic.DetailView):
    model = Article

    def get_queryset(self):
        key = self.request.GET.get("draft_key")
```

<img width="985" alt="Screenshot 2021-12-28 at 23 22 50" src="https://user-images.githubusercontent.com/3630554/147611456-f8b538f2-dad9-4ffe-9184-393209d2a934.png">

PyCharm complains about the types here, even though `mypy` doesn't.

Hinting `request: WSGIRequest` solves the issue with PyCharm though.

## How is that should be

There should not be any issue with the types. Is PyCharm wrong about complaining here? Is django-stubs wrong about typing `request` with `HttpRequest` and not something else like `WSGIRequest`?

## System information

- OS: macOS 12.1 (21C52)
- `python` version: Python 3.10.0
- `django` version: 4.0
- `mypy` version: mypy 0.930
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by sobolevn** [comment]
Can you please paste `reveal_type(self.request)`? What it was initially?

Looks related to https://github.com/python/typeshed/issues/6597

**Comment by Crocmagnon** [comment]
```
src/articles/views/html.py:133: note: Revealed type is "django.http.request.HttpRequest"
```

My guess is that comes from the existing type hinting in `TemplateResponseMixin`:

https://github.com/typeddjango/django-stubs/blob/9483865284bfe199961085d52765a83270e84611/django-stubs/views/generic/base.pyi#L27

**Comment by sobolevn** [comment]
Ok, here's what I think is going on. 

`HttpRequest` has `.GET` defined `QueryDict`, which is a `MuttableMapping` subtype: https://github.com/typeddjango/django-stubs/blob/9483865284bfe199961085d52765a83270e84611/django-stubs/utils/datastructures.pyi#L36

Related https://github.com/python/typeshed/pull/6694

**Comment by Crocmagnon** [comment]
So it’s an error in pycharm? As a matter of fact I don’t understand their message. My `.get` call looks fine according to their pop up, right?

It nearly seems like they think I’m missing the `self`, like if `GET` were a type, not an instance. I’ll try to check the revealed type of `GET`

**Comment by sobolevn** [comment]
It looks like it is a error with PyCharm. Do they use our stubs? Or do the use their own version?

You can send a PR with this sample as a test case (if we don't have one). Just to be sure.

**Comment by Crocmagnon** [comment]
This looks related to #555, [this thread](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003433179-Pycharm-suddenly-not-detecting-ANY-Django-tags-in-template) and [this YouTrack issue](https://youtrack.jetbrains.com/issue/PY-37744). Nothing we can fix here I'm afraid.

BTW, `Revealed type is "django.http.request.QueryDict"` in both cases (with HttpRequest or WSGIRequest as type for self.request).
