### ISSUE TITLE
Expressions on UniqueConstraint aren't supported

### ISSUE THREAD

**Issue by knyghty** [typeddjango/django-stubs#805]
# Bug report

## What's wrong

Django 4.0 added support for a [positional `expressions` argument](https://docs.djangoproject.com/en/4.0/ref/models/constraints/#expressions), but it doesn't look like it's supported here yet.

Example:

```
class User:
    ...
    class Meta:
        constraints = [
            models.UniqueConstraint(Upper("email"), name="email_key"),
        ]
```

Output:

```
mypy .
xxx/models.py:74: error: Too many positional arguments for "UniqueConstraint"
xxx/models.py:74: error: Argument 1 to "UniqueConstraint" has incompatible type "Upper"; expected "Sequence[str]"
xxx/migrations/0001_initial.py:111: error: Too many positional arguments for "UniqueConstraint"
xxx/migrations/0001_initial.py:112: error: Argument 1 to "UniqueConstraint" has incompatible type "Upper"; expected "Sequence[str]"
```

## How is that should be

Shouldn't output errors.

## System information

- OS: Mac OS
- `python` version: 3.10
- `django` version: 4.0
- `mypy` version: 0.930
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by sobolevn** [comment]
PR is welcome! 👍
