### ISSUE TITLE
Support django 4

### ISSUE THREAD

**Issue by quentinelwin** [typeddjango/django-stubs#808]
Hi,
Do you plan to support django 4.0.x anytime soon? (or to officialize its support with the current version of django-stubs)
Thanks

**Comment by sobolevn** [comment]
Yes, we do! It is already tested in our CI, some types are added as well.

**Comment by mylesdawson** [comment]
Hello! Has there been any progress on supporting Django 4.0.x? Me and my team would love to use this awesome library that you guys have built

**Comment by JohnLiehr** [comment]
Any status update on Django 4 support? Just kicking off a new Django project and would love to use Django 4 + Django Stubs 🔥

**Comment by johnthagen** [comment]
@sobolevn Curious is there a list of what remains for Django 4.0 support? I see `django-stubs` 1.10.1 was released only a month ago. Does it have preliminary support for Django 4?

**Comment by sobolevn** [comment]
Yes, some bits ;)

**Comment by jd-solanki** [comment]
Hi, I am not pressurizing here but I am going to start a new project with Django 4 next week.

Should I wait for the new release?

Regards.

**Comment by matclayton** [comment]
We're currently using the latest version against Django 4.0.4, I've yet to see a mismatch, however there is surely going to be quite a few, especially if using some of the async features (which we are not). We needed to bump to Django 4, so it forced our hand to go this route for now.

**Comment by intgr** [comment]
Django 4.0 is decently well supported by now. If there are omissions, please open specific issues describing what is wrong.
