### ISSUE TITLE
CHANGELOG?  Release notes?

### ISSUE THREAD

**Issue by tony** [typeddjango/django-stubs#809]
Hi and thank you for the project!

For recent versions, could changelogs be added to the releases https://github.com/typeddjango/django-stubs/releases for a high level overview?

When releases are tagged, I think it's easier to read the ones where there's a few bullet points of changes, example: [v1.2.0](https://github.com/typeddjango/django-stubs/releases/tag/v1.2.0)

I've had very good luck with dedicated changelog files on other projects. Have those been considered before?  As an example of what I mean (while the tagging wouldn't be possible going backwards): [flask's 1.1.3 changes](https://github.com/pallets/flask/blob/1.1.3/CHANGES.rst)). Would a PR be welcome for this?

**Comment by tony** [comment]
@typeddjango: Is there a plan to have a rudimentary changelog at any point?  I suppose whoever tags the version may be in the best position to do that.

The reason why I am curious is django has very descriptive release notes: https://docs.djangoproject.com/en/4.0/releases/ 

I still can't tell what's happening between django-stubs releases. 🤷 


https://user-images.githubusercontent.com/26336/159682300-6663fc88-4209-43e6-b097-e0305313ddc6.mp4

**Comment by tony** [comment]
@sobolevn Any chance we can have release notes for [1.13.0](https://github.com/typeddjango/django-stubs/releases/tag/1.13.0)?

**Comment by intgr** [comment]
There is a lot of stuff. I have autogenerated the [relase notes for 1.13.0](https://github.com/typeddjango/django-stubs/releases/tag/1.13.0) now, I hope that's helpful. :)

I guess it was by mistake that the release notes were missing.

**Comment by tony** [comment]
@intgr Thank you!!

😄 I am somewhat begging, but these would be a dream to have:

If it were curated (e.g. had sections and weighted by what the release manager thinks would be important to users) that would be superb.

If it were in a single changelog file ([like Flask's](https://github.com/pallets/flask/blob/1.1.3/CHANGES.rst)), it'd be even easier to stay on top of things.

**Comment by intgr** [comment]
For the 1.13.1 release, I sorted the PRs into sections by topic: https://github.com/typeddjango/django-stubs/releases/tag/1.13.1

**Comment by intgr** [comment]
I consider this fixed, latest release notes on GitHub have been more detailed.

**Comment by tony** [comment]
@intgr Much better (release [v1.14](https://github.com/typeddjango/django-stubs/releases/tag/1.14.0))!

Is it fine if I make an issue for keeping the changes in a single Changelog file?

**Comment by intgr** [comment]
I'm not a fan of putting this information exclusively into the database of a proprietary cloud service (GitHub).

But the process is currently convenient for me: creating a release also automagically creates a git tag, the "Generate release notes" button gives me a good draft for fleshing out the release notes, and I can edit the release notes later after the release is done.

I don't want any additional steps in this process. If someone has suggestions for an alternative process that doesn't add extra steps, that would be welcome.

**Comment by intgr** [comment]
Adding links from the PyPI page and README to the GitHub release page would be helpful I guess.

**Comment by tony** [comment]
> Adding links from the PyPI page and README to the GitHub release page would be helpful I guess.

These are a possibility

> But the process is currently convenient for me: creating a release also automagically creates a git tag, the "Generate release notes" button gives me a good draft for fleshing out the release notes, and I can edit the release notes later after the release is done.

I appreciate it being more convenient from a maintenainer / upkeep standpoint. 

But I think the downstream ramification of using solely GitHub Releases is so hindering I feel the need to go out of my way to mention it.  It's a lot more difficult as an end user to reason about the changes across a few versions.

> I don't want any additional steps in this process. If someone has suggestions for an alternative process that doesn't add extra steps, that would be welcome.

Drop GitHub releases and use a changelog file - and curate the version changes before cutting the git tag.  There can also be a requirement for PRs that they contain docs / changelog info - which minimizes the burden of the maintaner.

**Comment by intgr** [comment]
> the downstream ramification of using solely GitHub Releases is so hindering I feel the need to go out of my way to mention it. It's a lot more difficult as an end user to reason about the changes across a few versions.

OK I must be missing something. How is it different looking at the GitHub releases page (https://github.com/typeddjango/django-stubs/releases) compared to reading a typical CHANGELOG.md file? You can see a list of versions as section headers, and a bunch of headings and bullet points under each version. Also these are available via the GitHub releases API, other applications can query it and present the results in different ways.

> There can also be a requirement for PRs that they contain docs / changelog info - which minimizes the burden of the maintaner.

I've seen projects do this. Honestly I think it would increase the burden because getting consistent release notes with the PR would often require extra back-and-forth with the author. Also I adapt the section titles in release notes based on the themes of the changes, which isn't known in advance.
