### ISSUE TITLE
Errors on explicitly typed model fields

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAzure** [typeddjango/django-stubs#810]
# Bug report
I'm unsure whether this is me doing something wrong, an oversight in django-stubs, or something that's just not possible.

## What's wrong
We are adding type hints and docstrings to our models and mypy with django-stubs is complaining about that.

Example model:
```python
class Product(BaseModel):
    name: str = models.CharField(max_length=350)
    """Name of this product"""
    supplier: Supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT)
    """Supplier of this product"""
    location: Location = models.ForeignKey(Location, on_delete=models.PROTECT)
    """Location of product"""
    description: str = models.TextField(max_length=1500, blank=True, null=True)
    """Description of product"""
    about_the_place: str = models.TextField(max_length=1500, blank=True, null=True)
    """Description of property (maybe of the apartment complex)"""
    is_active: bool = models.BooleanField(default=False)
    """Is the product actively posted"""
    cancellation_policy_type: ProductCancellationTypeChoices = models.CharField(
            choices=ProductCancellationTypeChoices.CANCELLATION_POLICY_TYPE_CHOICES,
            default=ProductCancellationTypeChoices.FLEXIBLE,
            max_length=10
    )
    """Cancellation policy (flexible/strict/etc)"""
    minimum_days: int = models.PositiveIntegerField(blank=True, null=True)
    """Minimum number of days for reservation of this product"""
```
mypy output (line numbers won't match up as I've omitted some code):
```
core/models/product_model.py:30: error: Incompatible types in assignment (expression has type "ForeignKey[Union[Supplier, Combinable], Supplier]", variable has type "Supplier")
core/models/product_model.py:32: error: Incompatible types in assignment (expression has type "ForeignKey[Union[Location, Combinable], Location]", variable has type "Location")
core/models/product_model.py:17: error: Incompatible types in assignment (expression has type "CharField[Union[str, int, Combinable], str]", variable has type "str")
core/models/product_model.py:23: error: Incompatible types in assignment (expression has type "TextField[Union[str, Combinable, None], Optional[str]]", variable has type "str")
core/models/product_model.py:25: error: Incompatible types in assignment (expression has type "TextField[Union[str, Combinable, None], Optional[str]]", variable has type "str")
core/models/product_model.py:37: error: Incompatible types in assignment (expression has type "BooleanField[Union[bool, Combinable], bool]", variable has type "bool")
core/models/product_model.py:68: error: Incompatible types in assignment (expression has type "CharField[Union[str, int, Combinable], str]", variable has type "ProductCancellationTypeChoices")
core/models/product_model.py:69: error: Incompatible types in assignment (expression has type "PositiveIntegerField[Union[float, int, str, Combinable, None], Optional[int]]", variable has type "int")
```

The comments and types show up in PyCharm, which is why we're even bothering to add types to them:
![image](https://user-images.githubusercontent.com/1719461/148449212-4c5435b9-219a-44c6-ba81-5229200f597f.png)Not super useful on obvious ones like bool/int/text fields, but fields with predefined choices it's a really handy reference:
![image](https://user-images.githubusercontent.com/1719461/148449244-590c9493-8c0b-492f-811b-93bc766bd0fc.png)
## How is that should be
I would like mypy to ignore the typing on these fields or, better yet, have some way of checking that the types are compatible (ie.     `supplier: str = models.ForeignKey(Supplier, on_delete=models.PROTECT)` throws an error).

Or if there's a better way of doing this, please tell me that I'm an idiot.

## System information

- OS: alpine 3.14 (Docker)
- `python` version: 3.9.5
- `django` version: 3.2.4
- `mypy` version: 0.930
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by nuschk** [comment]
So, I'm not an expert, but I think the intention is for you to *not* annotate yourself, e.g.:

```python
class Product(BaseModel):
    name = models.CharField(max_length=350)
```

django-stubs annotates those types via the plugin (in `mypy.ini`), such that `resolve_type(Product.objects.first().name)` will be a string later.

I'm still a bit sad though that this doesn't work, as it prevents django models to work against mypy protocols. You can't just do the following:

```python
class ProductProcol(Procol):
    name: str

def f(p: ProductProcol):
    pass

f(p=Product.objects.last())
```

This would be nice for all kinds of intermediary service-layer type code.

**Comment by flaeppe** [comment]
I'm gonna close this off as there's descriptors involved behind these types. Meaning that `field: str = CharField(...)` won't be correct, as it's not the approach for trying to hint the field type on an instance.

These kind of field types should be inferred by `django-stubs`, otherwise there's something else getting in the way.

Please feel free to reopen with a breaking case.
