### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by aleksanb** [typeddjango/django-stubs#818]
Hello 👋.
Could we make a new pypi release?

**Comment by sobolevn** [comment]
Things we need before a new release:
- Change supported mypy version to latest
- Add `do_not_cache` flag to our `Annotated` field

**Comment by aleksanb** [comment]
I made a pr for 931: https://github.com/typeddjango/django-stubs/pull/819.
Unsure how to approach for do_not_cache

**Comment by sobolevn** [comment]
@aleksanb see https://github.com/python/mypy/blob/master/mypy/nodes.py#L3153-L3164

**Comment by AustinScola** [comment]
@sobolevn would you mind explaining the `do_not_cache` flag that you are talking about? I don't see how that link is related?

**Comment by adamchainz** [comment]
@sobolevn didn't press "y" on GitHub to fix to a commit, when copying that link, and the file changed since. I think this is the intended link: https://github.com/python/mypy/blob/6de254ef00f99ce5284ab947f2dd1179db6d28f6/mypy/nodes.py#L3153-L3164

Looks like the attr is named `no_serialize`.

**Comment by AustinScola** [comment]
Thanks @adamchainz. I'm still not sure what is meant by:

> * Add `do_not_cache` flag to our `Annotated` field

What  is the `Annotated` field being referred to here?

**Comment by adamchainz** [comment]
I'm not sure either, I haven't looked at mypy internals much. But `Annotated` is this class in typing: https://docs.python.org/3.10/library/typing.html#typing.Annotated . I assume it's used inside django-stubs.

**Comment by sobolevn** [comment]
https://github.com/typeddjango/django-stubs/releases/tag/1.10.0

Sorry for the delay! :)
