### ISSUE TITLE
fields type in bulk_update

### ISSUE THREAD

**Issue by jerch** [typeddjango/django-stubs#822]
# Bug report

## What's wrong
The `fields` argument in `bulk_update` is typed as `Sequence[str]`: https://github.com/typeddjango/django-stubs/blob/a9e41a8ba97820cb6be7d85083dce23cab3ba2c1/django-stubs/db/models/query.pyi#L62

This prevents using `Set[str]`, as it is not a subtype of `Sequence` (thats my actual issue with it).

## How is that should be
Looking at the django source `bulk_update` transforms the `fields` argument by a list comprehension early, thus any iterable should work here. I suggest to widen the type info to `Iterable[str]`.

**Comment by sobolevn** [comment]
PR is welcome.
