### ISSUE TITLE
error: "Collector" has no attribute "data"

### ISSUE THREAD

**Issue by benwhalley** [typeddjango/django-stubs#842]
Mypy complains about this code:

```
collector = Collector(using="default")
collector.collect([self])
children = list(itertools.chain(*[v for k, v in collector.data.items()]))
```

saying error: "Collector" has no attribute "data"

I'm not sure what the most general type should be, but collectors do have a data attribute.

**Comment by intgr** [comment]
This has been fixed some time ago.
