### ISSUE TITLE
Version 1.10 release

### ISSUE THREAD

**Issue by patrick91** [typeddjango/django-stubs#853]
Hi folks! I see that the readme mentions version 1.10 here: https://github.com/typeddjango/django-stubs#version-compatibility

I don't see this on MyPy, is it still pending release? if so do you recommend using django-stubs from git for the time being? ^^

**Comment by patrick91** [comment]
I've used versions from github if someone wants to try this before it gets released :D

```
git+https://github.com/typeddjango/django-stubs@ab50fb987604445d13285bf4a21511428da951ff#egg=django-stubs
git+https://github.com/typeddjango/django-stubs@ab50fb987604445d13285bf4a21511428da951ff#subdirectory=django_stubs_ext
```

**Comment by sobolevn** [comment]
https://github.com/typeddjango/django-stubs/releases/tag/1.10.0
