### ISSUE TITLE
Mypy version 0.940 released, causes tests to fail

### ISSUE THREAD

**Issue by himanshu-balasamanta** [typeddjango/django-stubs#870]
On [11th March 2022, Mypy version 0.940](https://pypi.org/project/mypy/#history) was released, causing django-stubs tests run by pytest to fail in Github Actions started on or after 11th Match.
We either need to use version 0.931 of mypy for local testing and Github actions, or find a way around the error `Cannot determine type of "Any"` being thrown due to mypy version 0.940 on running the pytest command.

**Comment by patrick91** [comment]
@Himanshu-Balasamanta this seems to be an issue on MyPy side, version 0.941 should fix this: https://github.com/python/mypy/issues/12339
