### ISSUE TITLE
MultipleObjectMixin and SingleObjectMixin has incompatible types for queryset and context_object_name

### ISSUE THREAD

**Issue by PetrDlouhy** [typeddjango/django-stubs#873]
# Bug report

## What's wrong

I have view class in [django-hordak](https://github.com/adamcharnock/django-hordak/blob/1.10.0/hordak/views/accounts.py#L76) defined as:
```python
class AccountTransactionsView(LoginRequiredMixin, SingleObjectMixin, ListView):
    ...
```

Which gives the following mypy errors:
```
# mypy .
hordak/views/accounts.py:86: error: Definition of "context_object_name" in base class "SingleObjectMixin" is incompatible with definition in base class "MultipleObjectMixin"
hordak/views/accounts.py:86: error: Definition of "queryset" in base class "SingleObjectMixin" is incompatible with definition in base class "MultipleObjectMixin"
Found 2 errors in 1 file (checked 56 source files)
```

## How is that should be

Types for `queryset` and `context_object_name` should be made less strict to be compatible similar to solution of issue #152

## System information

- OS: Ubuntu
- `python` version: 3.9.7
- `django` version: 4.0.2
- `mypy` version: 0.931
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by sterliakov** [comment]
Probably I misunderstand something, but it looks like unsafe code. `SingleObjectMixin.queryset` is a queryset to `get_object` from, it should be `QuerySet[Account]` (if it is "view listing transactions for account"). `MultipleObjectMixin.queryset` is queryset you operate on (e.g. render in `ListView`) - it should be `QuerySet[Transaction]`. These two bases are really incompatible.

**Comment by flaeppe** [comment]
As previously mentioned, `SingleObjectMixin` and `ListView` classes are, typing wise, incompatible. Currently over the `get_context_object_name` method
