### ISSUE TITLE
Django2.2 support

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/django-stubs#89]
HI, @mkurnikov! Thanks for building this package.

Are there any plans on `django@2.2` support? Since it is LTS, it might be a good idea to use this version.

And a general question: what is your idea about different versions support? 
Is there any existing discussion about it?

**Comment by mkurnikov** [comment]
There was no discussion yet.

I think two possibilities here is to: 
1. Support only the latest version of Django, luckily it's LTS, so it's the additional incentive. Also, we probably should work on DEP and integrating the package officially. 
2. Go `if DJANGO_2_1 else` route (I don't like it). 

I have some time to work on a package now, so expect it to be updated to 2.2 soon.

**Comment by sobolevn** [comment]
Awesome! Looking forward to test it and provide a feedback.

**Comment by mkurnikov** [comment]
Fixed in https://github.com/mkurnikov/django-stubs/pull/98
