### ISSUE TITLE
Changed the semantics of Annotated.

### ISSUE THREAD

**Issue by mvaled** [typeddjango/django-stubs#893]
# Bug report

## What's wrong

`typing.Annotated` is being reported incorrectly by changing their semantics.  I have a small dataclass like:

```python
@dataclass(unsafe_hash=True)
class RatingComposite(LoweringComposite):
    require_picture: Annotated[bool, ExtendedBooleanType(labels={True: "Always", False: "Never")] = True
    max_value: Annotated[int, IntegerType(min_value=1, max_value=10)] = 5
```

We're using [xotl.plato](https://merchise-autrement.gitlab.io/xotl.plato/) to parse and dump this kind of structures to JSON.  However, this code fails to type-check with:

```
error: Invalid type comment or annotation
note: Suggestion: use ExtendedBooleanType[...] instead of ExtendedBooleanType(...)
error: Incompatible types in assignment (expression has type "bool", variable has type "WithAnnotations[builtins.bool]")

error: Invalid type comment or annotation
note: Suggestion: use IntegerType[...] instead of IntegerType(...)
error: Incompatible types in assignment (expression has type "int", variable has type "WithAnnotations[builtins.int]")
``` 

Without `django-stubs-ext` mypy would accept that annotations and their default values.
 

## How is that should be

- The extension should not impose any syntax to the annotation.  The purpose of `Annotated` is to annotate with 3rd party objects and django-stub-ext should not change the semantics of it.  If it doesn't know about `ExtendedBooleanType`  or `IntegerType`, it should completly ignore them.  Notice the second example is quite similar to the use cases described in [PEP 593](https://peps.python.org/pep-0593/#motivating-examples).

- The final erased type `WithAnnotations[builtins.bool]` should only be introduced for the cases `django-stub-ext` knows about; in this case I'd expect the final type would be just `bool`.

## System information

- OS: Linux (mostly, Manjaro and also Debian-based containers in a CI pipeline)
- `python` version: 3.10.2
- `django` version: 4.0.3 (but is actually not Django related code)
- `mypy` version: 0.941
- `django-stubs` version: 1.9.0
- `django-stubs-ext` version: 0.3.1

**Comment by g-as** [comment]
Same here, with a pydantic model.
