### ISSUE TITLE
django-stubs 1.10.1 missing from github

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#918]
# Bug report

## What's wrong

django-stubs 1.10.1 is on pypi but not github
 
## How is that should be

thanks for the release! please push your tags ❤️ 

## System information

N/A

**Comment by sobolevn** [comment]
Done! https://github.com/typeddjango/django-stubs/releases/tag/1.10.1

Thanks!

**Comment by christianbundy** [comment]
Thank you!
