### ISSUE TITLE
SearchHeadline in `django.contrib.postgres.search` missing definition

### ISSUE THREAD

**Issue by nbhargava** [typeddjango/django-stubs#929]
# Bug report

## What's wrong

`SearchHeadline` is defined in `django.contrib.postgres.search`, but it seems to be missing from the stubs. It seems like virtually all other stubs for this file hav ebeen provided.

Failing test case:
```python
from django.contrib.postgres.search import SearchHeadline
```

## How is that should be

The stub should roughly match the contents that are here: https://github.com/django/django/blob/main/django/contrib/postgres/search.py#L267

## System information

- OS:
- `python` version: 3.10.2
- `django` version: 4.0.3
- `mypy` version: 0.942
- `django-stubs` version: 1.10.1
- `django-stubs-ext` version: 0.4.0

**Comment by vin-ai** [comment]
+1 Same here. I found this error too

- OS: WSL2
- python version: 3.8.10
- django version: 3.2.13
- mypy version: 0.950
- django-stubs version: 1.11.1
- django-stubs-ext version: 0.4.0

**Comment by nbhargava** [comment]
This was fixed by #909 and seems to be present in the latest release.
