### ISSUE TITLE
v0.12.1 broke the mypy_django_plugin

### ISSUE THREAD

**Issue by emilgoldsmith** [typeddjango/django-stubs#93]
I was just trying to install this package for the first time, but kept getting import errors `Error importing plugin 'mypy_django_plugin.main'` which seems to be the same error you get if you just write something gibberish, aka it can't find the package. I was super stumped for a while and was debugging a lot, ending up also trying to install another plugin just to see if it was mypy but that worked. I also tried just importing `mypy_django_plugin` but that would tell me `Plugin 'mypy_django_plugin' does not define entry point function "plugin"`, so I tried importing the `plugin` function into `__init__.py` but then the previous error came again.

I then saw that it was a pretty recent release I'd downloaded so I tried downgrading to `0.12.0` and it suddenly worked, so it looks like you somehow broke an import in `0.12.1` ?

I'm on Ubuntu 18.04 using python 3.6.7 if that helps

**Comment by theriverman** [comment]
I can confirm the very same have happened to me. Spent way too many minutes to figure out why am I getting `Error importing plugin 'mypy_django_plugin.main'`. Then rolled one release back and suddenly everything seems to be OK.

**Comment by asfaltboy** [comment]
Can confirm same happened to me, downgrade to 0.12.0 helps, am on MacOS and Python 3.6.4

**Comment by bygri** [comment]
This appears to be only an issue with both 0.12.1 and Python 3.6. 0.12.1 with Python 3.7 works fine.

**Comment by sobolevn** [comment]
Versions `1.0.x` are released.
