### ISSUE TITLE
Support mypy 0.950

### ISSUE THREAD

**Issue by DamianZaremba** [typeddjango/django-stubs#938]
mypy 0.950 was released a short while ago (https://github.com/python/mypy/releases/tag/v0.950).

`django-stubs` currently enforces a version less than 0.950 (https://github.com/typeddjango/django-stubs/blob/master/setup.py#L23), please enable support for 0.950.

**Comment by dimbleby** [comment]
per a comment in https://github.com/typeddjango/djangorestframework-stubs/pull/203

- `mypy` releases much more frequently than either `django-stubs` or `djangorestframework-stubs`
- although `mypy` might in principle release a breaking change at any point, such things seem to be very rare.  (I don't know of any example where a `mypy` release has broken these projects, perhaps it has happened?)
- if `mypy` ever does release a breaking change I can easily work around that in my own project by pinning to an older version, whereas I cannot force a newer version while `django*-stubs` explicitly prevents me from doing so

All of which is to say: please consider removing the upper bounds on `mypy` in both projects.
