### ISSUE TITLE
v0.12.0 seems to have been published with dev code

### ISSUE THREAD

**Issue by emilgoldsmith** [typeddjango/django-stubs#94]
So as I mentioned in my previous issue I got this package to work by downgrading to 0.12.0, after a few runs it started once in a while crashing with this error message though:

![django-stubs bug](https://user-images.githubusercontent.com/18149242/59655591-25b3a780-919b-11e9-84a5-0c92b7fbd5d9.jpg)

After some more debugging I found that there was a function in my distro version that's not in the Github v0.12.0 tag, and that was where the bug was, I also realized that this function that doesn't exist on Github at any time I can find (was looking through the git history of the main.py file) was being called like this (line 350):

![Screenshot from 2019-06-18 07-35-07](https://user-images.githubusercontent.com/18149242/59655749-a2df1c80-919b-11e9-8668-a8451d7a2188.png)

which not only has a commented out print statement but much more suspiciously has a return statement before all that logic below which is on Github but can't run in my distro. This leads me to believe the publisher was probably debugging before publishing and forgot to do a `git checkout` or something of the like to clear their code of debug statements before publishing. Not sure if it's possible to overwrite a publish on Pypi, probably not, and I guess this is already fixed in future releases but if there is a way of fixing it that would be cool. For me deleting that return statement seems to make the code work again

**Comment by emilgoldsmith** [comment]
For anyone out there having the same problems as I, I just cloned this repo and published the v0.12.0 tag under the package name `emil-fixed-django-stubs` until this package becomes stable again.

On a side note, I know I've been logging some pretty critical bugs here lately, but I really do enjoy the package, thank you so much for it! As soon as I got it to work the first time it found a 500 server error for me that I didn't know existed as I had used a settings key incorrectly in code that doesn't run frequently and wasn't tested well enough

**Comment by sobolevn** [comment]
Versions `1.0.x` are released. And it is a complete rewrite. `0.12.x` are no longer supported.
