### ISSUE TITLE
Patch View to be generic to support djangorestframework-stubs?

### ISSUE THREAD

**Issue by henribru** [typeddjango/django-stubs#946]
This isn't actually needed for django-stubs, but djangorestframework-stubs uses generic views, so could we add it to the classes monkeypatched by django_stubs_ext? If so I'd be happy to create a PR for that

**Comment by henribru** [comment]
Or perhaps we could allow passing in additional classes to `monkeypatch`?

**Comment by sobolevn** [comment]
Yes, extra classes to `monkeypatch` seem like a good idea.
