### ISSUE TITLE
error: Need type annotation for dependencies/operations

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#948]
# Bug report

I'm not sure what I'm doing wrong, but I'm getting an unexpected Mypy error whenever I make a new migration.

## What's wrong

```python3
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = []
```

## How is that should be

I would expect that this is fine, but I get a `var-annotated` error for `dependencies` and `operations`:

```
error: Need type annotation for "dependencies" (hint: "dependencies: List[<type>] = ...")
error: Need type annotation for "operations" (hint: "operations: List[<type>] = ...")
```

## System information

- OS:
- `python` version: 3.10.3
- `django` version: 3.2.x
- `mypy` version: 0.941
- `django-stubs` version: 1.9.x
- `django-stubs-ext` version: 0.4.x

**Comment by sobolevn** [comment]
This is a mypy bug 😒 
Please, use `List[Migration]` (or whatever it is) to make it happy.

Right now this type is considered "partial", so it does not really work for mypy.

Going to close this, because there's nothing I can do here.

**Comment by christianbundy** [comment]
> This is a mypy bug 😒

Thanks for the info! Is there a ticket on the mypy repo for this?

EDIT: Nevermind, looks like https://github.com/python/mypy/issues/4547 maybe?
