### ISSUE TITLE
Look for settings in setup.cfg

### ISSUE THREAD

**Issue by takkaria** [typeddjango/django-stubs#95]
It would be useful if the plugin looked for `setup.cfg` as well as `./mypy_django.ini` to avoid having to set env vars / type out a long string every time I use mypy.  Happy to submit a patch.

**Comment by blueyed** [comment]
Yeah, thought the same.. :+1:

**Comment by sobolevn** [comment]
@takkaria would be awesome to have it! 🚀

**Comment by mkurnikov** [comment]
Current way of configuration using `mypy.ini` is quite ergonomic, for more enhancements on top of it please refer to upstream issue https://github.com/python/mypy/issues/3532
