### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#959]
Hey there! Is there a release schedule for this project? I'll often bump into bugs and then see the fix merged, but we'll often go a while without a new release. Is there a regular cadence that we're aiming to make releases on, or anything that I can do to help reduce the maintenance burden of cutting a new release?

**Comment by sobolevn** [comment]
No 🙂 

I am the only one doing releases in my free time.

I think that there's only one way we can automate this: https://github.com/semantic-release/semantic-release

But, I am not sure that this is a good idea.

**Comment by christianbundy** [comment]
Is this something that I can help with? Totally understand if you aren't comfortable adding permissions,  but I've maintained loads of open source projects (mostly in the Node.js ecosystem) and would love to help with the "create a tag and push a release" chore.

**Comment by sobolevn** [comment]
I am totally fine with automating this process 🙂 
I think that we can push to PyPI from GitHub itself.

**Comment by SmileyChris** [comment]
For a bit more control, you can have the action to push to pypi trigger only when you create a github release rather than implicitly when a tag is created: https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/

**Comment by intgr** [comment]
I notice that Kurnikov has also made releases in the past. Since Sobolev is busy, any chance @mkurnikov you have time to make a release? This is holding up mypy 0.950 adoption (released on 27 April).

**Comment by mkurnikov** [comment]
Hi, I've made a `1.11.0` release from the latest master, please check that everything works as expected.

**Comment by mkurnikov** [comment]
I think new PyPI releases could be created on every release tag in the repo, it will simplify release maintenance a little bit. I do not have enough time and experience with GitHub actions to be able to do it though. 
So, @christianbundy, if you'd like to create such a workflow, I can add the PyPI token to the Github Secrets later. 

Also, feel free to tag me if you need a release. I do not have enough context to review code anymore, but I can manage that much.

**Comment by christianbundy** [comment]
Excellent. I know I'll be pretty busy with work this week, but I'll ping you when I've got something put together.

**Comment by mkurnikov** [comment]
I'll try to implement it myself this week, feel free to take it over if
it's not yet done by the end of Sunday.

**Comment by mkurnikov** [comment]
Aaand I probably won't have time for that, sorry, please take over. Tag me later if you need anything from me.

**Comment by terencehonles** [comment]
@christianbundy / @mkurnikov I added a simple workflow in #980

**Comment by intgr** [comment]
The latest discussion about release schedule has been in #1095, I'm closing this duplicate.
