### ISSUE TITLE
Mypy 0.710 support

### ISSUE THREAD

**Issue by henribru** [typeddjango/django-stubs#96]
Mypy 0.710 was released last week, but the setup.py is specifying `<0.710`. Are there compatibility issues with this version that makes this necessary?

**Comment by sobolevn** [comment]
See https://github.com/mkurnikov/pytest-mypy-plugins/issues/3

I am sure there might be other issues as well.

**Comment by mkurnikov** [comment]
I have updated `master` to 0.710, please test it.
