### ISSUE TITLE
error: "Response" has no attribute "json"  [attr-defined]

### ISSUE THREAD

**Issue by jdahlin** [typeddjango/django-stubs#962]
This started happening in django-stubs 1.11.0. Previous version, 1.10.1 worked fine. Using mypy 0.940, djangorestframework 3.13.1, djangorestframework-stubs 1.5.0.

Can be reproduced with:

```python
from rest_framework.test import APIClient
api_client = APIClient()
response = api_client.post('https://example.com', json.dumps({}), content_type="application/json")
response.json()
```

`error: "Response" has no attribute "json"  [attr-defined]`

**Comment by andersk** [comment]
django-stubs knows about `response.json()`:

https://github.com/typeddjango/django-stubs/blob/4a90ad9edc280ddc3e4b3abc1f7e108e94992a0e/django-stubs/test/client.pyi#L123-L124 https://github.com/typeddjango/django-stubs/blob/4a90ad9edc280ddc3e4b3abc1f7e108e94992a0e/django-stubs/test/client.pyi#L131-L132

So perhaps this is actually a djangorestframework-stubs bug.

**Comment by sobolevn** [comment]
Yes, looks like so.
Please, reopen there.
